// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : 1.28
// File generated on 2008/5/15 ¤U¤È 12:59:31 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\SpeedySolution\Simulator\COM\MarketDataConnection\MarketDataConnection.tlb (1)
// LIBID: {D889F05C-9C8F-41B4-AC64-E8E3C0DCC825}
// LCID: 0
// Helpfile: 
// HelpString: MarketDataConnection Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINDOWS\system32\stdole2.tlb)
//   (2) v1.0 OrderMessage, (C:\MBus\Lib\OrderMessage.dll)
// ************************************************************************ //
#ifndef   MarketDataConnection_TLBH
#define   MarketDataConnection_TLBH

#pragma option push -b -w-inl

#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif
#include "OrderMessage_TLB.h"


// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)    
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Marketdataconnection_tlb
{

// *********************************************************************//
// HelpString: MarketDataConnection Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLSID_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
extern __declspec (package) const GUID LIBID_MarketDataConnection;
extern __declspec (package) const GUID IID_IMarketDataConnection;
extern __declspec (package) const GUID DIID_IMarketDataConnectionEvents;
extern __declspec (package) const GUID CLSID_MarketDataConnection_;

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
interface DECLSPEC_UUID("{FDD6ECC5-EB36-4362-A59B-60254E8A2E7A}") IMarketDataConnection;
typedef TComInterface<IMarketDataConnection, &IID_IMarketDataConnection> IMarketDataConnectionPtr;

interface DECLSPEC_UUID("{E8ED3073-F69C-4CB1-8532-72F59C759A18}") IMarketDataConnectionEvents;
typedef TComInterface<IMarketDataConnectionEvents, &DIID_IMarketDataConnectionEvents> IMarketDataConnectionEventsPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library                       
// (NOTE: Here we map each CoClass to its Default Interface)              
//                                                                        
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this  
// TypeLibrary. It simplifies the updating of macros when CoClass name    
// change.                                                                
// *********************************************************************//
typedef IMarketDataConnection MarketDataConnection_;
typedef IMarketDataConnectionPtr MarketDataConnection_Ptr;

#define LIBID_OF_MarketDataConnection_ (&LIBID_MarketDataConnection)
// *********************************************************************//
// Interface: IMarketDataConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {FDD6ECC5-EB36-4362-A59B-60254E8A2E7A}
// *********************************************************************//
interface IMarketDataConnection  : public IDispatch
{
public:
  // [201] Create A connection object with a unique name.
  virtual HRESULT STDMETHODCALLTYPE Create(BSTR AppName/*[in]*/) = 0;
  // [202] Destroy the connection object.
  virtual HRESULT STDMETHODCALLTYPE Destroy(void) = 0;
  // [203] Connect to StarWave Server.
  virtual HRESULT STDMETHODCALLTYPE Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/) = 0;
  // [204] Disconnect.
  virtual HRESULT STDMETHODCALLTYPE Disconnect(void) = 0;
  // [205] Subscribe the commodity's market data by unique market ID and SecurityID.
  virtual HRESULT STDMETHODCALLTYPE Subscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/) = 0;
  // [206] Unsubscribe the market data.
  virtual HRESULT STDMETHODCALLTYPE Unsubscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/) = 0;
  // [207] Send a security definition request to StarWave Server.
  virtual HRESULT STDMETHODCALLTYPE SecurityDefinitionRequest(Ordermessage_tlb::ISecurityDefinitionRequestMessage* Msg/*[in]*/) = 0;

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

// *********************************************************************//
// Interface: IMarketDataConnectionEvents
// Flags:     (4096) Dispatchable
// GUID:      {E8ED3073-F69C-4CB1-8532-72F59C759A18}
// *********************************************************************//
interface IMarketDataConnectionEvents : public TDispWrapper<IDispatch>
{
  void __fastcall OnConnected()
  {
    _TDispID _dispid(/* OnConnected */ DISPID(201));
    OleProcedure(_dispid);
  }

  void __fastcall OnDisconnected()
  {
    _TDispID _dispid(/* OnDisconnected */ DISPID(202));
    OleProcedure(_dispid);
  }

  void __fastcall OnMarketData(Ordermessage_tlb::IMarketDataMessage* Msg/*[in]*/)
  {
    _TDispID _dispid(/* OnMarketData */ DISPID(203));
    TAutoArgs<1> _args;
    _args[1] = (LPDISPATCH)(Ordermessage_tlb::IMarketDataMessage*)Msg /*[VT_USERDEFINED:1]*/;
    OleProcedure(_dispid, _args);
  }

  void __fastcall OnQuoteRequest(Ordermessage_tlb::IMDQuoteRequestMessage* Msg/*[in]*/)
  {
    _TDispID _dispid(/* OnQuoteRequest */ DISPID(204));
    TAutoArgs<1> _args;
    _args[1] = (LPDISPATCH)(Ordermessage_tlb::IMDQuoteRequestMessage*)Msg /*[VT_USERDEFINED:1]*/;
    OleProcedure(_dispid, _args);
  }

  void __fastcall OnSecurityDefinition(Ordermessage_tlb::ISecurityDefinitionMessage* Msg/*[in]*/)
  {
    _TDispID _dispid(/* OnSecurityDefinition */ DISPID(205));
    TAutoArgs<1> _args;
    _args[1] = (LPDISPATCH)(Ordermessage_tlb::ISecurityDefinitionMessage*)Msg /*[VT_USERDEFINED:1]*/;
    OleProcedure(_dispid, _args);
  }

  void __fastcall OnNews(Ordermessage_tlb::INewsMessage* Msg/*[in]*/)
  {
    _TDispID _dispid(/* OnNews */ DISPID(206));
    TAutoArgs<1> _args;
    _args[1] = (LPDISPATCH)(Ordermessage_tlb::INewsMessage*)Msg /*[VT_USERDEFINED:1]*/;
    OleProcedure(_dispid, _args);
  }


};
#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMIMarketDataConnection
// Interface: IMarketDataConnection
// *********************************************************************//
template <class T /* IMarketDataConnection */ >
class TCOMIMarketDataConnectionT : public TComInterface<IMarketDataConnection>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMIMarketDataConnectionT() {}
  TCOMIMarketDataConnectionT(IMarketDataConnection *intf, bool addRef = false) : TComInterface<IMarketDataConnection>(intf, addRef) {}
  TCOMIMarketDataConnectionT(const TCOMIMarketDataConnectionT& src) : TComInterface<IMarketDataConnection>(src) {}
  TCOMIMarketDataConnectionT& operator=(const TCOMIMarketDataConnectionT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall Create(BSTR AppName/*[in]*/);
  HRESULT         __fastcall Destroy(void);
  HRESULT         __fastcall Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/);
  HRESULT         __fastcall Disconnect(void);
  HRESULT         __fastcall Subscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/);
  HRESULT         __fastcall Unsubscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/);
  HRESULT         __fastcall SecurityDefinitionRequest(Ordermessage_tlb::ISecurityDefinitionRequestMessage* Msg/*[in]*/);

};
typedef TCOMIMarketDataConnectionT<IMarketDataConnection> TCOMIMarketDataConnection;

// *********************************************************************//
// DispIntf:  IMarketDataConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {FDD6ECC5-EB36-4362-A59B-60254E8A2E7A}
// *********************************************************************//
template<class T>
class IMarketDataConnectionDispT : public TAutoDriver<IMarketDataConnection>
{
public:
  IMarketDataConnectionDispT(){}

  IMarketDataConnectionDispT(IMarketDataConnection *pintf)
  {
    TAutoDriver<IMarketDataConnection>::Bind(pintf, false);
  }

  IMarketDataConnectionDispT(IMarketDataConnectionPtr pintf)
  {
    TAutoDriver<IMarketDataConnection>::Bind(pintf, true);
  }

  IMarketDataConnectionDispT& operator=(IMarketDataConnection *pintf)
  {
    TAutoDriver<IMarketDataConnection>::Bind(pintf, false);
    return *this;
  }

  IMarketDataConnectionDispT& operator=(IMarketDataConnectionPtr pintf)
  {
    TAutoDriver<IMarketDataConnection>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_MarketDataConnection_));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_MarketDataConnection_);
  }

  HRESULT         __fastcall Create(BSTR AppName/*[in]*/);
  HRESULT         __fastcall Destroy();
  HRESULT         __fastcall Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/);
  HRESULT         __fastcall Disconnect();
  HRESULT         __fastcall Subscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/);
  HRESULT         __fastcall Unsubscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/);
  HRESULT         __fastcall SecurityDefinitionRequest(Ordermessage_tlb::ISecurityDefinitionRequestMessage* Msg/*[in]*/);

};
typedef IMarketDataConnectionDispT<IMarketDataConnection> IMarketDataConnectionDisp;

// *********************************************************************//
// DispIntf:  IMarketDataConnectionEvents
// Flags:     (4096) Dispatchable
// GUID:      {E8ED3073-F69C-4CB1-8532-72F59C759A18}
// *********************************************************************//
template <class T>
class IMarketDataConnectionEventsDispT : public TAutoDriver<IMarketDataConnectionEvents>
{
public:
  IMarketDataConnectionEventsDispT(){}

  void Attach(LPUNKNOWN punk)
  { m_Dispatch = static_cast<T*>(punk); }

  void            __fastcall OnConnected();
  void            __fastcall OnDisconnected();
  void            __fastcall OnMarketData(Ordermessage_tlb::IMarketDataMessage* Msg/*[in]*/);
  void            __fastcall OnQuoteRequest(Ordermessage_tlb::IMDQuoteRequestMessage* Msg/*[in]*/);
  void            __fastcall OnSecurityDefinition(Ordermessage_tlb::ISecurityDefinitionMessage* Msg/*[in]*/);
  void            __fastcall OnNews(Ordermessage_tlb::INewsMessage* Msg/*[in]*/);

};
typedef IMarketDataConnectionEventsDispT<IMarketDataConnectionEvents> IMarketDataConnectionEventsDisp;

// *********************************************************************//
// SmartIntf: TCOMIMarketDataConnection
// Interface: IMarketDataConnection
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMIMarketDataConnectionT<T>::Create(BSTR AppName/*[in]*/)
{
  return (*this)->Create(AppName);
}

template <class T> HRESULT __fastcall
TCOMIMarketDataConnectionT<T>::Destroy(void)
{
  return (*this)->Destroy();
}

template <class T> HRESULT __fastcall
TCOMIMarketDataConnectionT<T>::Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/)
{
  return (*this)->Connect(RemoteIP, RemotePort);
}

template <class T> HRESULT __fastcall
TCOMIMarketDataConnectionT<T>::Disconnect(void)
{
  return (*this)->Disconnect();
}

template <class T> HRESULT __fastcall
TCOMIMarketDataConnectionT<T>::Subscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/)
{
  return (*this)->Subscribe(Market, Symbol);
}

template <class T> HRESULT __fastcall
TCOMIMarketDataConnectionT<T>::Unsubscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/)
{
  return (*this)->Unsubscribe(Market, Symbol);
}

template <class T> HRESULT __fastcall
TCOMIMarketDataConnectionT<T>::SecurityDefinitionRequest(Ordermessage_tlb::ISecurityDefinitionRequestMessage* Msg/*[in]*/)
{
  return (*this)->SecurityDefinitionRequest(Msg);
}

// *********************************************************************//
// DispIntf:  IMarketDataConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {FDD6ECC5-EB36-4362-A59B-60254E8A2E7A}
// *********************************************************************//
template <class T> HRESULT __fastcall
IMarketDataConnectionDispT<T>::Create(BSTR AppName/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Create"), DISPID(201));
  TAutoArgs<1> _args;
  _args[1] = AppName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMarketDataConnectionDispT<T>::Destroy()
{
  _TDispID _dispid(*this, OLETEXT("Destroy"), DISPID(202));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
IMarketDataConnectionDispT<T>::Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Connect"), DISPID(203));
  TAutoArgs<2> _args;
  _args[1] = RemoteIP /*[VT_BSTR:0]*/;
  _args[2] = RemotePort /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMarketDataConnectionDispT<T>::Disconnect()
{
  _TDispID _dispid(*this, OLETEXT("Disconnect"), DISPID(204));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
IMarketDataConnectionDispT<T>::Subscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Subscribe"), DISPID(205));
  TAutoArgs<2> _args;
  _args[1] = Market /*[VT_BSTR:0]*/;
  _args[2] = Symbol /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMarketDataConnectionDispT<T>::Unsubscribe(BSTR Market/*[in]*/, BSTR Symbol/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Unsubscribe"), DISPID(206));
  TAutoArgs<2> _args;
  _args[1] = Market /*[VT_BSTR:0]*/;
  _args[2] = Symbol /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMarketDataConnectionDispT<T>::SecurityDefinitionRequest(Ordermessage_tlb::ISecurityDefinitionRequestMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SecurityDefinitionRequest"), DISPID(207));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::ISecurityDefinitionRequestMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// DispIntf:  IMarketDataConnectionEvents
// Flags:     (4096) Dispatchable
// GUID:      {E8ED3073-F69C-4CB1-8532-72F59C759A18}
// *********************************************************************//
template <class T> void __fastcall
IMarketDataConnectionEventsDispT<T>::OnConnected()
{
  _TDispID _dispid(/* OnConnected */ DISPID(201));
  OleProcedure(_dispid);
}

template <class T> void __fastcall
IMarketDataConnectionEventsDispT<T>::OnDisconnected()
{
  _TDispID _dispid(/* OnDisconnected */ DISPID(202));
  OleProcedure(_dispid);
}

template <class T> void __fastcall
IMarketDataConnectionEventsDispT<T>::OnMarketData(Ordermessage_tlb::IMarketDataMessage* Msg/*[in]*/)
{
  _TDispID _dispid(/* OnMarketData */ DISPID(203));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IMarketDataMessage*)Msg /*[VT_USERDEFINED:1]*/;
  OleProcedure(_dispid, _args);
}

template <class T> void __fastcall
IMarketDataConnectionEventsDispT<T>::OnQuoteRequest(Ordermessage_tlb::IMDQuoteRequestMessage* Msg/*[in]*/)
{
  _TDispID _dispid(/* OnQuoteRequest */ DISPID(204));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IMDQuoteRequestMessage*)Msg /*[VT_USERDEFINED:1]*/;
  OleProcedure(_dispid, _args);
}

template <class T> void __fastcall
IMarketDataConnectionEventsDispT<T>::OnSecurityDefinition(Ordermessage_tlb::ISecurityDefinitionMessage* Msg/*[in]*/)
{
  _TDispID _dispid(/* OnSecurityDefinition */ DISPID(205));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::ISecurityDefinitionMessage*)Msg /*[VT_USERDEFINED:1]*/;
  OleProcedure(_dispid, _args);
}

template <class T> void __fastcall
IMarketDataConnectionEventsDispT<T>::OnNews(Ordermessage_tlb::INewsMessage* Msg/*[in]*/)
{
  _TDispID _dispid(/* OnNews */ DISPID(206));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::INewsMessage*)Msg /*[VT_USERDEFINED:1]*/;
  OleProcedure(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that       
// provide static Create() and CreateRemote(LPWSTR machineName) methods   
// for creating an instance of an exposed object. These functions can     
// be used by client wishing to automate CoClasses exposed by this        
// typelibrary.                                                           
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : MarketDataConnection_
// Interface: TCOMIMarketDataConnection
// *********************************************************************//
typedef TCoClassCreatorT<TCOMIMarketDataConnection, IMarketDataConnection, &CLSID_MarketDataConnection_, &IID_IMarketDataConnection> CoMarketDataConnection_;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


#if !defined(__TLB_NO_EVENT_WRAPPERS) && defined(USING_ATLVCL)
// *********************************************************************//
// CONNECTIONPOINT/EVENT PROXY
// CoClass         : MarketDataConnection_
// Event Interface : IMarketDataConnectionEvents
// *********************************************************************//
template <class T>
class TEvents_MarketDataConnection_ : public IConnectionPointImpl<T,
                                                 &DIID_IMarketDataConnectionEvents,
#if !defined(_TLB_DYNAMIC_CONNECTIONPOINT_ARRAY)
                                                 CComUnkArray<CONNECTIONPOINT_ARRAY_SIZE> >
#else
                                                 CComDynamicArray>
#endif
{
public:
  void            Fire_OnConnected(void);
  void            Fire_OnDisconnected(void);
  void            Fire_OnMarketData(Ordermessage_tlb::IMarketDataMessage* Msg);
  void            Fire_OnQuoteRequest(Ordermessage_tlb::IMDQuoteRequestMessage* Msg);
  void            Fire_OnSecurityDefinition(Ordermessage_tlb::ISecurityDefinitionMessage* Msg);
  void            Fire_OnNews(Ordermessage_tlb::INewsMessage* Msg);
protected:
  IMarketDataConnectionEventsDisp m_EventIntfObj;
};

template <class T> void
TEvents_MarketDataConnection_<T>::Fire_OnConnected(void)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnConnected();
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_MarketDataConnection_<T>::Fire_OnDisconnected(void)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnDisconnected();
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_MarketDataConnection_<T>::Fire_OnMarketData(Ordermessage_tlb::IMarketDataMessage* Msg)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnMarketData(Msg);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_MarketDataConnection_<T>::Fire_OnQuoteRequest(Ordermessage_tlb::IMDQuoteRequestMessage* Msg)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnQuoteRequest(Msg);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_MarketDataConnection_<T>::Fire_OnSecurityDefinition(Ordermessage_tlb::ISecurityDefinitionMessage* Msg)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnSecurityDefinition(Msg);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_MarketDataConnection_<T>::Fire_OnNews(Ordermessage_tlb::INewsMessage* Msg)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnNews(Msg);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

#endif  //   __TLB_NO_EVENT_WRAPPERS

};     // namespace Marketdataconnection_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Marketdataconnection_tlb;
#endif

#pragma option pop

#endif // MarketDataConnection_TLBH
