// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : 1.28
// File generated on 2008/5/15 ¤U¤È 12:59:32 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\MBus\Lib\OrderMessage.dll (1)
// LIBID: {4C3ACC93-9EC6-44E5-BFC2-883EED3A05DA}
// LCID: 0
// Helpfile: 
// HelpString: OrderMessage Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINDOWS\system32\stdole2.tlb)
// Parent TypeLibrary:
//   (0) v1.0 MarketDataConnection, (C:\SpeedySolution\Simulator\COM\MarketDataConnection\MarketDataConnection.tlb)
// ************************************************************************ //
#ifndef   OrderMessage_OCXH
#define   OrderMessage_OCXH

#pragma option push -b -w-inl

#include <olectrls.hpp>
#include <oleserver.hpp>
#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "OrderMessage_TLB.h"
namespace Ordermessage_tlb
{

// *********************************************************************//
// HelpString: OrderMessage Library
// Version:    1.0
// *********************************************************************//

// SKIPPING COCLASS: BaseMessage          - Is in dependent type library
// SKIPPING COCLASS: NewOrderMessage      - Is in dependent type library
// SKIPPING COCLASS: ReplaceOrderMessage  - Is in dependent type library
// SKIPPING COCLASS: CancelOrderMessage   - Is in dependent type library
// SKIPPING COCLASS: QuoteMessage         - Is in dependent type library
// SKIPPING COCLASS: QuoteCancelMessage   - Is in dependent type library
// SKIPPING COCLASS: QuoteRequestMessage  - Is in dependent type library
// SKIPPING COCLASS: ExecutionReportMessage - Is in dependent type library
// SKIPPING COCLASS: MDBaseMessage        - Is in dependent type library
// SKIPPING COCLASS: MarketDataMessage    - Is in dependent type library
// SKIPPING COCLASS: MDQuoteRequestMessage - Is in dependent type library
// SKIPPING COCLASS: NewsMessage          - Is in dependent type library
// SKIPPING COCLASS: SecurityDefinitionRequestMessage - Is in dependent type library
// SKIPPING COCLASS: SecurityDefinitionMessage - Is in dependent type library
};     // namespace Ordermessage_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Ordermessage_tlb;
#endif

#pragma option pop

#endif // OrderMessage_OCXH
