// Do not edit. This file is machine generated by the Resource DLL Wizard.

library MarketDataComponent;

{ITE} {DFMFileType} {SortListForm.dfm}
{ITE} {DFMFileType} {StopOrderSetting.dfm}
{ITE} {RCFileType} {MarketDataComponent_DRC.rc}

{$R 'SortListForm.dfm' SortForm:TForm}
{$R 'StopOrderSetting.dfm' StopOrderSettingForm:TForm}
{$R 'MarketDataComponent_DRC.res' 'MarketDataComponent_DRC.rc'}

{$E CHS}

begin
end.