object CancelWorkingForm: TCancelWorkingForm
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = #23450#26178#22996#35351#20840#21034
  ClientHeight = 122
  ClientWidth = 233
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  Scaled = False
  OnCreate = FormCreate
  PixelsPerInch = 120
  TextHeight = 16
  object Label15: TLabel
    Left = 33
    Top = 10
    Width = 126
    Height = 23
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = #22996#35351#21934#20840#21034#26178#38291
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -18
    Font.Name = #24494#36575#27491#40657#39636
    Font.Style = []
    ParentFont = False
  end
  object OKButton: TButton
    Left = 33
    Top = 86
    Width = 75
    Height = 25
    Caption = #21855#29992
    ModalResult = 1
    TabOrder = 0
    OnClick = OKButtonClick
  end
  object CancelButton: TButton
    Left = 121
    Top = 86
    Width = 75
    Height = 25
    Caption = #20572#29992
    ModalResult = 2
    TabOrder = 1
    OnClick = CancelButtonClick
  end
  object HourEdit: TEdit
    Left = 33
    Top = 42
    Width = 33
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -18
    Font.Name = 'Arial'
    Font.Style = []
    ImeMode = imSAlpha
    MaxLength = 2
    ParentFont = False
    TabOrder = 2
    Text = '8'
  end
  object HUpDown: TUpDown
    Left = 66
    Top = 42
    Width = 20
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Associate = HourEdit
    Min = 8
    Max = 23
    Position = 8
    TabOrder = 3
  end
  object MinutesEdit: TEdit
    Left = 88
    Top = 42
    Width = 33
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -18
    Font.Name = 'Arial'
    Font.Style = []
    ImeMode = imSAlpha
    MaxLength = 2
    ParentFont = False
    TabOrder = 4
    Text = '59'
  end
  object MinutesUpDown: TUpDown
    Left = 121
    Top = 42
    Width = 20
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Associate = MinutesEdit
    Min = 1
    Max = 59
    Position = 59
    TabOrder = 5
  end
  object SecEdit: TEdit
    Left = 143
    Top = 42
    Width = 33
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -18
    Font.Name = 'Arial'
    Font.Style = []
    ImeMode = imSAlpha
    MaxLength = 2
    ParentFont = False
    TabOrder = 6
    Text = '50'
  end
  object SecUpDown: TUpDown
    Left = 176
    Top = 42
    Width = 20
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Associate = SecEdit
    Max = 59
    Position = 50
    TabOrder = 7
  end
  object RoundFormEx: TRoundFormEx
    Resource = MainForm.RoundFormExRes
    InactiveFontColor = 19
    Lockbox = True
    CaptionFont.Charset = ANSI_CHARSET
    CaptionFont.Color = clWhite
    CaptionFont.Height = -17
    CaptionFont.Name = #24494#36575#27491#40657#39636
    CaptionFont.Style = []
    Left = 232
  end
end
