// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// $Rev: 87174 $
// File generated on 2019/7/23 下午 08:35:29 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\MEGASECCAPIATL.dll (1)
// LIBID: {B44F8C2D-F257-43B4-8904-961E87889EC6}
// LCID: 0
// Helpfile: 
// HelpString: MEGASECCAPIATL 1.0 ���O�{���w
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
// SYS_KIND: SYS_WIN32
// ************************************************************************ //
#ifndef   MEGASECCAPIATLLib_OCXH
#define   MEGASECCAPIATLLib_OCXH

#pragma option push -b -a4 -w-inl -w-8118

#include <olectrls.hpp>
#include <oleserver.hpp>
#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <System.Win.StdVCL.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "MEGASECCAPIATLLib_TLB.h"
namespace Megaseccapiatllib_tlb
{

// *********************************************************************//
// HelpString: MEGASECCAPIATL 1.0 ���O�{���w
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TMEGASECCAPI
// Help String      : MEGASECCAPI Class
// Default Interface: IMEGASECCAPI
// Def. Intf. Object: TCOMIMEGASECCAPI
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (34) CanCreate Control
// *********************************************************************//

// *********************************************************************//
// Definition of closures to allow VCL handlers to catch OCX events.      
// *********************************************************************//
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
// Proxy class to host MEGASECCAPI Class in CBuilder IDE/Applications.
//-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
class PACKAGE TMEGASECCAPI : public Vcl::Olectrls::TOleControl
{
  OVERLOADED_PROP_METHODS;
  static TNoParam  OptParam;
  static GUID      DEF_CTL_INTF;

  // Instance of Closures to expose OCX Events as VCL ones
  //

  // Default Interace of OCX
  //
  TCOMIMEGASECCAPI m_OCXIntf;

  // VCL Property Getters/Setters which delegate to OCX
  //

  // Static variables used by all instances of OCX proxy
  //
  static Vcl::Olectrls::TControlData2 CControlData;
  static GUID          CTL_DEF_INTF;

  // Method providing access to interface as __property 
  //
  TCOMIMEGASECCAPI __fastcall GetDefaultInterface();
  TCOMIMEGASECCAPI __fastcall GetControlInterface()
  { return GetDefaultInterface(); }

protected:
  void     __fastcall CreateControl  ();
  void     __fastcall InitControlData();

public:
  virtual  __fastcall TMEGASECCAPI(System::Classes::TComponent* AOwner) : Vcl::Olectrls::TOleControl(AOwner)
  {};
  virtual  __fastcall TMEGASECCAPI(HWND        Parent) : Vcl::Olectrls::TOleControl(Parent)
  {};

  // OCX methods
  //
  void            __fastcall SetCodePage(int codepage/*[in]*/);
  BSTR            __fastcall CAPIEncrypt(BSTR strSubject/*[in]*/, int istore/*[in]*/, 
                                         int iSelCertFlags/*[in]*/, BSTR bData/*[in]*/, 
                                         int Flags/*[in]*/, int iKeyUsage/*[in]*/);
  BSTR            __fastcall CAPIDecrypt(BSTR strCipher/*[in]*/, int Flags/*[in]*/, 
                                         int iKeyUsage/*[in]*/);
  int             __fastcall CAPIExportPKCS12(BSTR strSubject/*[in]*/, int Flags/*[in]*/, 
                                              int iKeyUsage/*[in]*/, BSTR strPassword/*[in]*/, 
                                              BSTR strFilePath/*[in]*/, BSTR strFileName/*[in]*/);
  long            __fastcall GetErrorCode(void);
  BSTR            __fastcall CAPISymmetricEncrypt(int iAlgor/*[in]*/, BSTR strPasswd/*[in]*/, 
                                                  BSTR bData/*[in]*/);
  BSTR            __fastcall CAPISymmetricDecrypt(int iAlgor/*[in]*/, BSTR strPasswd/*[in]*/, 
                                                  BSTR cipher/*[in]*/);
  BSTR            __fastcall CAPICertGetSerialNumber(BSTR strCert/*[in]*/, int iFlags/*[in]*/);
  void            __fastcall CheckKeyUsage(int iCheck/*[in]*/);
  BSTR            __fastcall GetVerifyRtnSignerInfo(void);
  BSTR            __fastcall GetVerifyRtnCert(void);
  BSTR            __fastcall CAPICertGetDigest(BSTR strCert/*[in]*/, int iFlags/*[in]*/);
  int             __fastcall CAPIShowCertificateDlg(BSTR strMsg/*[in]*/, BSTR strCert/*[in]*/);
  int             __fastcall CAPISetLanguage(BSTR strLanguage/*[in]*/);
  int             __fastcall CAPIImportPKCS12(BSTR strPwd/*[in]*/, BSTR strFilePath/*[in]*/, 
                                              BSTR strFileName/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall CAPIEncode(BSTR strData/*[in]*/, VARIANT strPemTitle/*[in]*/);
  BSTR            __fastcall CAPIDecode(BSTR strEncoded/*[in]*/, VARIANT strPemTitle/*[in]*/);
  BSTR            __fastcall CAPICertGetSubject(BSTR strCert/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall CAPICertGetIssuer(BSTR strCert/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall CAPICertGetNotBefore(BSTR strCert/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall CAPICertGetNotAfter(BSTR strCert/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall CAPICertEncrypt(BSTR strCert/*[in]*/, BSTR bData/*[in]*/, 
                                             int iFlags/*[in]*/);
  void            __fastcall CAPISetDisplayMessage(BSTR strMessage/*[in]*/);
  int             __fastcall CAPIPureSign(BSTR strData/*[in]*/, BSTR strSubject/*[in]*/, 
                                          int iFlags/*[in]*/, int iHashalg/*[in,def,opt]*/, 
                                          int iKeyUsage/*[in,def,opt]*/);
  BSTR            __fastcall CAPIGetRtnSignature(void);
  BSTR            __fastcall CAPIGetRtnCert(void);
  long            __fastcall CAPIRegisterCertificate(BSTR strProvider/*[in]*/);
  BSTR            __fastcall CAPIPKCS7GetUserCertificate(BSTR p7cert/*[in]*/);
  VARIANT         __fastcall CAPIGetCertSubject(BSTR subject/*[in]*/, BSTR field/*[in]*/, 
                                                int flag/*[in]*/, int keyUsage/*[in]*/);
  void            __fastcall CAPIShowDebugMessage(long bShow/*[in]*/);
  VARIANT         __fastcall CAPIGetCertsEx(BSTR provider/*[in]*/, BSTR subject/*[in]*/, 
                                            int flag/*[in]*/, int keyUsage/*[in]*/, 
                                            int disableATKeySpec/*[in]*/);
  long            __fastcall CAPIRegisterCertificateEx(BSTR strProvider/*[in]*/, 
                                                       long iDisableFlag/*[in]*/);
  BSTR            __fastcall CAPIFileSign(BSTR strFilePath/*[in]*/, BSTR strSubject/*[in]*/, 
                                          BSTR strProvider/*[in]*/, BSTR strPin/*[in]*/, 
                                          int iFlags/*[in]*/, int iHashFlag/*[in]*/, 
                                          int iKeyUsage/*[in]*/);
  int             __fastcall CAPI_MultiSignInit(BSTR strProvider/*[in]*/, int iFlags/*[in]*/);
  void            __fastcall CAPI_MultiSignEnd(int iFlags/*[in]*/);
  BSTR            __fastcall CAPISelectCert(BSTR subject/*[in]*/, int Flags/*[in]*/, 
                                            int iKeyUsage/*[in]*/);
  BSTR            __fastcall GetSignRtnContent(void);
  BSTR            __fastcall CAPIFileEncryptByCert(BSTR strCert/*[in]*/, BSTR strFilePath/*[in]*/, 
                                                   int iFlags/*[in]*/);
  int             __fastcall CAPIDecrypt2File(BSTR strCipher/*[in]*/, BSTR strOutFilePath/*[in]*/, 
                                              int Flags/*[in]*/, int iKeyUsage/*[in]*/);
  long            __fastcall CAPIPFXImportSC(BSTR sPFXfilepath/*[in]*/, BSTR strPasswd/*[in]*/, 
                                             BSTR strCSP/*[in]*/, int iFlags/*[in]*/);
  long            __fastcall ssInit(BSTR strCert/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall ssGetEncSessionKey(int iFlags/*[in]*/);
  BSTR            __fastcall CAPI_UsrCertGetProvName(BSTR subject/*[in]*/, int Flags/*[in]*/, 
                                                     int iKeyUsage/*[in]*/);
  long            __fastcall CAPI_DeleteUsrCert(BSTR subject/*[in]*/, int flag/*[in]*/, 
                                                int keyUsage/*[in]*/);
  BSTR            __fastcall CAPI_XGetUserCertificate(BSTR strProvider/*[in]*/, BSTR subject/*[in]*/, 
                                                      int Flags/*[in]*/, int iKeyUsage/*[in]*/, 
                                                      BSTR strSubjectAltName/*[in,def,opt]*/);
  long            __fastcall CAPI_AcceptPKCS7(BSTR strCertificate/*[in]*/, long iFlags/*[in]*/);
  BSTR            __fastcall CAPICertGetPublicKey(BSTR strCert/*[in]*/, int iFlags/*[in]*/);
  long            __fastcall CAPI_ChangeP12Pwd(BSTR strPFXFilepath/*[in]*/, BSTR strOldPwd/*[in]*/, 
                                               BSTR strNewPwd/*[in]*/, long iFlags/*[in]*/);
  BSTR            __fastcall CAPI_PFXSign(BSTR sPFXfilepath/*[in]*/, BSTR strPasswd/*[in]*/, 
                                          BSTR bData/*[in]*/, long iFlags/*[in]*/, 
                                          int iHashFlags/*[in,def,opt]*/, 
                                          long iKeyUsage/*[in,def,opt]*/);
  long            __fastcall CAPI_GetPFXCertCount(BSTR sPFXfilepath/*[in]*/, BSTR strPasswd/*[in]*/);
  BSTR            __fastcall GetVersion(long flag/*[in]*/);
  BSTR            __fastcall CAPI_ReadFile(BSTR strFilePath/*[in]*/, long Flags/*[in]*/);
  BSTR            __fastcall CAPI_GetFilePath(BSTR title/*[in]*/, BSTR typeDesc/*[in]*/, 
                                              BSTR fileType/*[in]*/, BSTR initPath/*[in]*/, 
                                              BSTR initFile/*[in]*/);
  BSTR            __fastcall CAPISign(BSTR strData/*[in]*/, BSTR signcodepage/*[in]*/, 
                                      BSTR strSubject/*[in]*/, BSTR bstrIssuer, 
                                      BSTR strProvider/*[in]*/, BSTR strPin/*[in]*/, 
                                      int iFlags/*[in]*/, int iHashFlag/*[in,def,opt]*/, 
                                      int iKeyUsage/*[in,def,opt]*/);
  int             __fastcall CAPIVerify(BSTR strSignature/*[in]*/, BSTR bData/*[in]*/, 
                                        BSTR signcodepage/*[in]*/, BSTR strSubject/*[in]*/, 
                                        int Flags/*[in]*/, int iKeyUsage/*[in]*/, int nTime/*[in]*/);
  BSTR            __fastcall CAPI_PKCS7GetSignerCert(BSTR pkcs7signature/*[in]*/, long index/*[in]*/, 
                                                     long Flags/*[in]*/);
  BSTR            __fastcall CAPIGetVerifiedContent(BSTR pkcs7signature/*[in]*/, 
                                                    BSTR reserved/*[in]*/, long Flags/*[in]*/);
  long            __fastcall CAPIVerifiedContent2File(BSTR pkcs7signature/*[in]*/, 
                                                      BSTR reserved/*[in]*/, long Flags/*[in]*/, 
                                                      BSTR outfile/*[in]*/);
  BSTR            __fastcall CAPIComposePKCS7(BSTR strCert/*[in]*/, BSTR B64RawSignature/*[in]*/, 
                                              BSTR strData/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall GetTempPath(void);
  BSTR            __fastcall enumProviders(long dwIndex/*[in]*/, long dwFlags/*[in]*/);
  void            __fastcall acceptPKCS7(BSTR strCert/*[in]*/);
  BSTR            __fastcall createPKCS10(BSTR dn/*[in]*/, BSTR oid/*[in]*/);
  BSTR            __fastcall CAPI_PFXSignEx(BSTR sB64PFX/*[in]*/, BSTR strPasswd/*[in]*/, 
                                            BSTR bData/*[in]*/, long iFlags/*[in]*/, 
                                            int iHashFlag/*[in,def,opt]*/, 
                                            long iKeyUsage/*[in,def,opt]*/);
  long            __fastcall CAPI_CheckPFX(BSTR sB64PFX/*[in]*/, BSTR strPasswd/*[in]*/, 
                                           BSTR strSubject/*[in]*/, long iFlags/*[in]*/, 
                                           long iKeyUsage/*[in]*/);
  long            __fastcall CAPI_DeleteUsrCertEx(BSTR strProvider/*[in]*/, BSTR subject/*[in]*/, 
                                                  int flag/*[in]*/, int keyUsage/*[in]*/);
  long            __fastcall CAPI_CheckPermission(void);
  int             __fastcall CAPIPureVerify(BSTR strSignature/*[in]*/, BSTR strData/*[in]*/, 
                                            BSTR strSubject/*[in]*/, int iFlags/*[in]*/, 
                                            int iHashalg/*[in,def,opt]*/, 
                                            int iKeyUsage/*[in,def,opt]*/);
  void            __fastcall CAPISetDisplayMessageFont(BSTR font/*[in]*/, int size/*[in]*/);
  BSTR            __fastcall CAPISignAndEncrypt(BSTR bSignerSubject/*[in]*/, 
                                                BSTR bEncryptCert/*[in]*/, BSTR bData/*[in]*/, 
                                                int iFlags/*[in]*/, int iHashFlags/*[in,def,opt]*/, 
                                                int iKeyUsage/*[in,def,opt]*/);
  BSTR            __fastcall CAPIDecryptAndVerify(BSTR bCipher/*[in]*/, int iSignerIndex/*[in]*/, 
                                                  int iFlags/*[in]*/);
  BSTR            __fastcall GetDecryptRtnCert(void);
  int             __fastcall CAPI_PFXPureSign(BSTR sPFXfilepath/*[in]*/, BSTR strPasswd/*[in]*/, 
                                              BSTR bData/*[in]*/, int iFlags/*[in]*/, 
                                              int iHashalg/*[in,def,opt]*/, 
                                              int iKeyUsage/*[in,def,opt]*/);
  long            __fastcall CAPIUnRegisterCertificateEx(BSTR strProvider/*[in]*/, 
                                                         long iFlags/*[in]*/);
  void            __fastcall acceptPKCS7Ex(BSTR bCert/*[in]*/, BSTR bPIN/*[in]*/);
  BSTR            __fastcall CAPISymmetricRawKeyEncrypt(int iAlgor/*[in]*/, BSTR strRawKey, 
                                                        BSTR strRawIV/*[in]*/, BSTR bData/*[in]*/, 
                                                        int iFlags/*[in,def,opt]*/);
  BSTR            __fastcall CAPISymmetricRawKeyDecrypt(int iAlgor/*[in]*/, BSTR strRawKey, 
                                                        BSTR strRawIV/*[in]*/, BSTR bCipher/*[in]*/, 
                                                        int iFlags/*[in,def,opt]*/);
  BSTR            __fastcall CAPIPKCS7GetEncryptedDigest(BSTR pkcs7signature/*[in]*/, 
                                                         long Flags/*[in]*/);
  long            __fastcall CAPI_InstallCert(BSTR strCertificate/*[in]*/, long iFlags/*[in]*/);
  long            __fastcall CAPI_WriteFile(BSTR strB64Data/*[in]*/, BSTR strFilePath/*[in]*/, 
                                            long iFlags/*[in]*/);
  BSTR            __fastcall GetMyDocumentsPath(void);
  int             __fastcall CAPISymmetricEncryptFile(int iAlgor/*[in]*/, BSTR strPasswd/*[in]*/, 
                                                      BSTR bSrcPath/*[in]*/, BSTR bDstPath/*[in]*/);
  int             __fastcall CAPISymmetricDecryptFile(int iAlgor/*[in]*/, BSTR strPasswd/*[in]*/, 
                                                      BSTR bSrcPath/*[in]*/, BSTR bDstPath/*[in]*/);
  BSTR            __fastcall CAPI_UsrCertGetContainerName(BSTR subject/*[in]*/, int Flags/*[in]*/, 
                                                          int iKeyUsage/*[in]*/);
  long            __fastcall CAPIPFXImportSCEx(BSTR sPFXfilepath/*[in]*/, BSTR strPasswd/*[in]*/, 
                                               BSTR strCSP/*[in]*/, BSTR strPin/*[in]*/, 
                                               int iFlags/*[in]*/);
  int             __fastcall CAPIImportPKCS12Ex(BSTR strPwd/*[in]*/, BSTR strFilePath/*[in]*/, 
                                                BSTR strFileName/*[in]*/, 
                                                BSTR strFriendlyName/*[in]*/, int iFlags/*[in]*/);
  void            __fastcall CGCAPIStockCertRegist(BSTR bUserID/*[in]*/, BSTR bConsoleCode/*[in]*/, 
                                                   BSTR bSubject/*[in]*/, BSTR bCAPath/*[in]*/, 
                                                   BSTR bPassword/*[in]*/, BSTR bCertSetFlag/*[in]*/);
  void            __fastcall CGCAPIStockCertConfig(BSTR bUserID/*[in]*/, BSTR bConsoleCode/*[in]*/, 
                                                   BSTR bSubject/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall CGCAPIStockSign(BSTR bUserID/*[in]*/, BSTR bConsoleCode/*[in]*/, 
                                             BSTR bSubject/*[in]*/, BSTR bData/*[in]*/, 
                                             int iFlags/*[in]*/, int iKeyUsage/*[in]*/, 
                                             int iHashFlags/*[in,def,opt]*/);
  BSTR            __fastcall CGCAPIStockPureSign(BSTR bUserID/*[in]*/, BSTR bConsoleCode/*[in]*/, 
                                                 BSTR bSubject/*[in]*/, BSTR bData/*[in]*/, 
                                                 int iFlags/*[in]*/, int iKeyUsage/*[in]*/, 
                                                 int iHashFlags/*[in,def,opt]*/);
  BSTR            __fastcall CGCAPIStockGetSN(void);
  BSTR            __fastcall CGCAPIStockGetCert(void);
  BSTR            __fastcall CGCAPIStockPFXPureSign(BSTR bFilepath/*[in]*/, BSTR bPassword/*[in]*/, 
                                                    BSTR bData/*[in]*/, BSTR bSubject/*[in]*/, 
                                                    int iFlags/*[in]*/, int iHashFlag/*[in]*/, 
                                                    int iKeyUsage/*[in]*/);
  int             __fastcall createFolder(BSTR bPath/*[in]*/);
  BSTR            __fastcall selectFolder(BSTR bTitle/*[in]*/);
  BSTR            __fastcall CAPISymmetricRawKeyEncryptEx(int iAlgor/*[in]*/, int iMode/*[in]*/, 
                                                          BSTR strRawKey/*[in]*/, 
                                                          BSTR strRawIV/*[in]*/, BSTR bData/*[in]*/, 
                                                          int iFlags/*[in,def,opt]*/);
  BSTR            __fastcall CAPISymmetricRawKeyDecryptEx(int iAlgor/*[in]*/, int iMode/*[in]*/, 
                                                          BSTR strRawKey/*[in]*/, 
                                                          BSTR strRawIV/*[in]*/, 
                                                          BSTR bCipher/*[in]*/, 
                                                          int iFlags/*[in,def,opt]*/);
  BSTR            __fastcall createPKCS10Ex(BSTR dn/*[in]*/, BSTR oid/*[in]*/, BSTR bPIN/*[in]*/);
  int             __fastcall WriteReg(BSTR key/*[in]*/, BSTR path/*[in]*/, BSTR name/*[in]*/, 
                                      BSTR type/*[in]*/, BSTR value/*[in]*/, int iFlags/*[in]*/);
  BSTR            __fastcall ReadReg(BSTR key/*[in]*/, BSTR path/*[in]*/, BSTR name/*[in]*/, 
                                     BSTR type/*[in]*/, int iFlags/*[in]*/);
  int             __fastcall CAPISetDisplayLogo(BSTR strCustomize/*[in]*/, int iFlags/*[in]*/);
  int             __fastcall CAPIPureSignEx(BSTR strData/*[in]*/, BSTR signcodepage/*[in]*/, 
                                            BSTR strSubject/*[in]*/, BSTR bstrIssuer, 
                                            BSTR strProvider/*[in]*/, BSTR strPin/*[in]*/, 
                                            int iFlags/*[in]*/, int iHashFlag/*[in,def,opt]*/, 
                                            int iKeyUsage/*[in,def,opt]*/);
  int             __fastcall CAPIDecrypt2File2(BSTR strInputFilePath/*[in]*/, 
                                               BSTR strOutFilePath/*[in]*/, int Flags/*[in]*/, 
                                               int iKeyUsage/*[in]*/);

  // OCX properties
  //
  __property TCOMIMEGASECCAPI ControlInterface={ read=GetDefaultInterface };

  // Published properties
  //
__published:

  // Standard/Extended properties
  //
  __property TabStop;
  __property Align;
  __property DragCursor;
  __property DragMode;
  __property ParentShowHint;
  __property PopupMenu;
  __property ShowHint;
  __property TabOrder;
  __property Visible;
  __property OnDragDrop;
  __property OnDragOver;
  __property OnEndDrag;
  __property OnEnter;
  __property OnExit;
  __property OnStartDrag;

  // OCX properties
  //
  __property System::WideString HashAlgorithm={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=79 };
  __property int providerType={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=80 };
  __property System::WideString providerName={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=81 };
  __property int KeySpec={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=82 };
  __property int GenKeyFlags={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=83 };
  __property int DeleteRequestCert={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=84 };
  __property int WriteCertToCSP={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=85 };
  __property System::WideString friendlyName={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=122 };
  __property System::WideString SubjectAltName={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=139 };

  // OCX Events
  //
};
typedef TMEGASECCAPI  TMEGASECCAPIProxy;

};     // namespace Megaseccapiatllib_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Megaseccapiatllib_tlb;
#endif

#pragma option pop

#endif // MEGASECCAPIATLLib_OCXH
