// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SpeedyCenter;

{ITE} {DFMFileType} {AccountInput.dfm}
{ITE} {DFMFileType} {AlarmForm.dfm}
{ITE} {DFMFileType} {AppInfo.dfm}
{ITE} {DFMFileType} {ChangeSessionStatus.dfm}
{ITE} {DFMFileType} {EventViewer.dfm}
{ITE} {DFMFileType} {FormAbout.dfm}
{ITE} {DFMFileType} {GroupServer.dfm}
{ITE} {DFMFileType} {ItemListForm.dfm}
{ITE} {DFMFileType} {LineEditForm.dfm}
{ITE} {DFMFileType} {Login.dfm}
{ITE} {DFMFileType} {MDIMain.dfm}
{ITE} {DFMFileType} {NewAccountForm.dfm}
{ITE} {DFMFileType} {NewSession.dfm}
{ITE} {DFMFileType} {NewUser.dfm}
{ITE} {DFMFileType} {PATSFrame.dfm}
{ITE} {DFMFileType} {PrcoessSettingForm.dfm}
{ITE} {DFMFileType} {ProfileGraph.dfm}
{ITE} {DFMFileType} {SearchSpeedyForm.dfm}
{ITE} {DFMFileType} {SelChannelForm.dfm}
{ITE} {DFMFileType} {SeqSettingForm.dfm}
{ITE} {DFMFileType} {SettingForm.dfm}
{ITE} {DFMFileType} {SimTFXMain.dfm}
{ITE} {DFMFileType} {SpeedyServerForm.dfm}
{ITE} {DFMFileType} {StarWaveFrame.dfm}
{ITE} {DFMFileType} {SystemInfoForm.dfm}
{ITE} {DFMFileType} {TagViewer.dfm}
{ITE} {DFMFileType} {TerminalForm.dfm}
{ITE} {DFMFileType} {VersionUnit.dfm}
{ITE} {DFMFileType} {WarningDialog.dfm}
{ITE} {DFMFileType} {C\src\VCL\NewValueForm.dfm}
{ITE} {RCFileType} {Debug\SpeedyCenter_DRC.rc}

USEFORMRES("AccountInput.dfm", AccountInputForm, Form); /* TForm: DesignClass */
#pragma resource "AccountInput.dfm"
USEFORMRES("AlarmForm.dfm", AlarmSettingForm, Form); /* TForm: DesignClass */
#pragma resource "AlarmForm.dfm"
USEFORMRES("AppInfo.dfm", AppInfoForm, Form); /* TForm: DesignClass */
#pragma resource "AppInfo.dfm"
USEFORMRES("ChangeSessionStatus.dfm", ChangeSessionStatusForm, Form); /* TForm: DesignClass */
#pragma resource "ChangeSessionStatus.dfm"
USEFORMRES("EventViewer.dfm", EventForm, Form); /* TForm: DesignClass */
#pragma resource "EventViewer.dfm"
USEFORMRES("FormAbout.dfm", AboutForm, Form); /* TForm: DesignClass */
#pragma resource "FormAbout.dfm"
USEFORMRES("GroupServer.dfm", ServerGroupForm, Form); /* TForm: DesignClass */
#pragma resource "GroupServer.dfm"
USEFORMRES("ItemListForm.dfm", ItemsForm, Form); /* TForm: DesignClass */
#pragma resource "ItemListForm.dfm"
USEFORMRES("LineEditForm.dfm", PVCSettingForm, Form); /* TForm: DesignClass */
#pragma resource "LineEditForm.dfm"
USEFORMRES("Login.dfm", LoginForm, Form); /* TForm: DesignClass */
#pragma resource "Login.dfm"
USEFORMRES("MDIMain.dfm", MDIForm, Form); /* TForm: DesignClass */
#pragma resource "MDIMain.dfm"
USEFORMRES("NewAccountForm.dfm", AccountForm, Form); /* TForm: DesignClass */
#pragma resource "NewAccountForm.dfm"
USEFORMRES("NewSession.dfm", SessionForm, Form); /* TForm: DesignClass */
#pragma resource "NewSession.dfm"
USEFORMRES("NewUser.dfm", NewUserForm, Form); /* TForm: DesignClass */
#pragma resource "NewUser.dfm"
USEFORMRES("PATSFrame.dfm", ConnectionFrame, Frame); /* TFrame: DesignClass */
#pragma resource "PATSFrame.dfm"
USEFORMRES("PrcoessSettingForm.dfm", ProcessForm, Form); /* TForm: DesignClass */
#pragma resource "PrcoessSettingForm.dfm"
USEFORMRES("ProfileGraph.dfm", ProfileFrame, Frame); /* TFrame: DesignClass */
#pragma resource "ProfileGraph.dfm"
USEFORMRES("SearchSpeedyForm.dfm", SearchForm, Form); /* TForm: DesignClass */
#pragma resource "SearchSpeedyForm.dfm"
USEFORMRES("SelChannelForm.dfm", ChannelForm, Form); /* TForm: DesignClass */
#pragma resource "SelChannelForm.dfm"
USEFORMRES("SeqSettingForm.dfm", SequenceForm, Form); /* TForm: DesignClass */
#pragma resource "SeqSettingForm.dfm"
USEFORMRES("SettingForm.dfm", FormSetting, Form); /* TForm: DesignClass */
#pragma resource "SettingForm.dfm"
USEFORMRES("SimTFXMain.dfm", SimTFXForm, Form); /* TForm: DesignClass */
#pragma resource "SimTFXMain.dfm"
USEFORMRES("SpeedyServerForm.dfm", ServerForm, Form); /* TForm: DesignClass */
#pragma resource "SpeedyServerForm.dfm"
USEFORMRES("StarWaveFrame.dfm", SWFrame, Frame); /* TFrame: DesignClass */
#pragma resource "StarWaveFrame.dfm"
USEFORMRES("SystemInfoForm.dfm", SystemForm, Form); /* TForm: DesignClass */
#pragma resource "SystemInfoForm.dfm"
USEFORMRES("TagViewer.dfm", TagForm, Form); /* TForm: DesignClass */
#pragma resource "TagViewer.dfm"
USEFORMRES("TerminalForm.dfm", TermForm, Form); /* TForm: DesignClass */
#pragma resource "TerminalForm.dfm"
USEFORMRES("VersionUnit.dfm", VersionForm, Form); /* TForm: DesignClass */
#pragma resource "VersionUnit.dfm"
USEFORMRES("WarningDialog.dfm", WarningForm, Form); /* TForm: DesignClass */
#pragma resource "WarningDialog.dfm"
USEFORMRES("C\src\VCL\NewValueForm.dfm", AddValueForm, Form); /* TForm: DesignClass */
#pragma resource "C\src\VCL\NewValueForm.dfm"
USERC("Debug\SpeedyCenter_DRC.rc");

{$E CHT}

begin
end.
