// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SpeedyCenter;

{ITE} {DFMFileType} {AccountInput.dfm}
{ITE} {DFMFileType} {AlarmForm.dfm}
{ITE} {DFMFileType} {AppInfo.dfm}
{ITE} {DFMFileType} {ChangeSessionStatus.dfm}
{ITE} {DFMFileType} {EventViewer.dfm}
{ITE} {DFMFileType} {ExceptionProd.dfm}
{ITE} {DFMFileType} {ExecptionAccount.dfm}
{ITE} {DFMFileType} {FormAbout.dfm}
{ITE} {DFMFileType} {GroupServer.dfm}
{ITE} {DFMFileType} {ItemListForm.dfm}
{ITE} {DFMFileType} {LineEditForm.dfm}
{ITE} {DFMFileType} {Login.dfm}
{ITE} {DFMFileType} {MDIMain.dfm}
{ITE} {DFMFileType} {MessageDialog.dfm}
{ITE} {DFMFileType} {NewAccountForm.dfm}
{ITE} {DFMFileType} {NewSession.dfm}
{ITE} {DFMFileType} {NewUser.dfm}
{ITE} {DFMFileType} {PATSFrame.dfm}
{ITE} {DFMFileType} {PrcoessSettingForm.dfm}
{ITE} {DFMFileType} {ProfileGraph.dfm}
{ITE} {DFMFileType} {SearchSpeedyForm.dfm}
{ITE} {DFMFileType} {SelChannelForm.dfm}
{ITE} {DFMFileType} {SeqSettingForm.dfm}
{ITE} {DFMFileType} {SettingForm.dfm}
{ITE} {DFMFileType} {SimTFXMain.dfm}
{ITE} {DFMFileType} {SpeedyServerForm.dfm}
{ITE} {DFMFileType} {StarWaveFrame.dfm}
{ITE} {DFMFileType} {SystemInfoForm.dfm}
{ITE} {DFMFileType} {TagViewer.dfm}
{ITE} {DFMFileType} {TerminalForm.dfm}
{ITE} {DFMFileType} {ThroughputLimit.dfm}
{ITE} {DFMFileType} {VersionUnit.dfm}
{ITE} {DFMFileType} {WarningDialog.dfm}
{ITE} {DFMFileType} {C\src\VCL\NewValueForm.dfm}
{ITE} {RCFileType} {Debug\SpeedyCenter_DRC.rc}

{$R 'AccountInput.dfm' 'AccountInputForm:TForm'}
{$R 'AlarmForm.dfm' 'AlarmSettingForm:TForm'}
{$R 'AppInfo.dfm' 'AppInfoForm:TForm'}
{$R 'ChangeSessionStatus.dfm' 'ChangeSessionStatusForm:TForm'}
{$R 'EventViewer.dfm' 'EventForm:TForm'}
{$R 'ExceptionProd.dfm' 'ExceptionProdForm:TForm'}
{$R 'ExecptionAccount.dfm' 'ExceptionAccForm:TForm'}
{$R 'FormAbout.dfm' 'AboutForm:TForm'}
{$R 'GroupServer.dfm' 'ServerGroupForm:TForm'}
{$R 'ItemListForm.dfm' 'ItemsForm:TForm'}
{$R 'LineEditForm.dfm' 'PVCSettingForm:TForm'}
{$R 'Login.dfm' 'LoginForm:TForm'}
{$R 'MDIMain.dfm' 'MDIForm:TForm'}
{$R 'MessageDialog.dfm' 'MessageForm:TForm'}
{$R 'NewAccountForm.dfm' 'AccountForm:TForm'}
{$R 'NewSession.dfm' 'SessionForm:TForm'}
{$R 'NewUser.dfm' 'NewUserForm:TForm'}
{$R 'PATSFrame.dfm' 'ConnectionFrame:TForm'}
{$R 'PrcoessSettingForm.dfm' 'ProcessForm:TForm'}
{$R 'ProfileGraph.dfm' 'ProfileFrame:TForm'}
{$R 'SearchSpeedyForm.dfm' 'SearchForm:TForm'}
{$R 'SelChannelForm.dfm' 'ChannelForm:TForm'}
{$R 'SeqSettingForm.dfm' 'SequenceForm:TForm'}
{$R 'SettingForm.dfm' 'FormSetting:TForm'}
{$R 'SimTFXMain.dfm' 'SimTFXForm:TForm'}
{$R 'SpeedyServerForm.dfm' 'ServerForm:TForm'}
{$R 'StarWaveFrame.dfm' 'SWFrame:TForm'}
{$R 'SystemInfoForm.dfm' 'SystemForm:TForm'}
{$R 'TagViewer.dfm' 'TagForm:TForm'}
{$R 'TerminalForm.dfm' 'TermForm:TForm'}
{$R 'ThroughputLimit.dfm' 'ThroughputForm:TForm'}
{$R 'VersionUnit.dfm' 'VersionForm:TForm'}
{$R 'WarningDialog.dfm' 'WarningForm:TForm'}
{$R 'C\src\VCL\NewValueForm.dfm' 'AddValueForm:TForm'}
{$R 'Debug\SpeedyCenter_DRC.res' 'Debug\SpeedyCenter_DRC.rc'}

{$E CHT}

begin
end.
