// ************************************************************************ //
// WARNING
// -------
// The types declared in this file were generated from data read from a
// Type Library. If this type library is explicitly or indirectly (via
// another type library referring to this type library) re-imported, or the
// 'Refresh' command of the Type Library Editor activated while editing the
// Type Library, the contents of this file will be regenerated and all
// manual modifications will be lost.
// ************************************************************************ //

// $Rev: 18756 $
// File generated on 2014/3/25 ¤U¤È 06:30:52 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\src\COM\TMPOrderConnection\TMPOrderConnection (1)
// LIBID: {FED2C287-FC0C-4106-ACA4-817040DF9F3C}
// LCID: 0
// Helpfile:
// HelpString: TMPOrderConnection Library
// DepndLst:
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
//   (2) v1.0 OrderMessage, (C:\MBus\lib\OrderMessage.dll)
// ************************************************************************ //
#ifndef   TMPOrderConnection_TLBH
#define   TMPOrderConnection_TLBH

#pragma option push -b -a4 -w-inl

#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif
#include "OrderMessage_TLB.h"


// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Tmporderconnection_tlb
{

// *********************************************************************//
// HelpString: TMPOrderConnection Library
// Version:    2.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:
//   Type Libraries     : LIBID_xxxx
//   CoClasses          : CLSID_xxxx
//   DISPInterfaces     : DIID_xxxx
//   Non-DISP interfaces: IID_xxxx
// *********************************************************************//
extern __declspec (package) const GUID LIBID_TMPOrderConnection;
extern __declspec (package) const GUID IID_ITaifexTMPConnection;
extern __declspec (package) const GUID DIID_ITaifexTMPConnectionEvents;
extern __declspec (package) const GUID CLSID_TaifexTMPConnection;
extern __declspec (package) const GUID GUID_RecoverTypeEnum;
extern __declspec (package) const GUID GUID_RecoverMarketEnum;
extern __declspec (package) const GUID GUID_MessageLanguageEnum;
extern __declspec (package) const GUID GUID_ConnectionTypeEnum;
extern __declspec (package) const GUID GUID_LogonResultEnum;
extern __declspec (package) const GUID GUID_ExecDupEnum;

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary
// *********************************************************************//
enum class    RecoverTypeEnum;
enum class    RecoverMarketEnum;
enum class    MessageLanguageEnum;
enum class    ConnectionTypeEnum;
enum class    LogonResultEnum;
enum class    ExecDupEnum;
interface DECLSPEC_UUID("{95454FF6-318C-4EAB-8F98-3AF16F56FB7E}") ITaifexTMPConnection;
typedef TComInterface<ITaifexTMPConnection, &IID_ITaifexTMPConnection> ITaifexTMPConnectionPtr;

interface DECLSPEC_UUID("{45612375-8A01-4B68-BE17-139F20CC483D}") ITaifexTMPConnectionEvents;
typedef TComInterface<ITaifexTMPConnectionEvents, &DIID_ITaifexTMPConnectionEvents> ITaifexTMPConnectionEventsPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library
// (NOTE: Here we map each CoClass to its Default Interface)
//
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this
// TypeLibrary. It simplifies the updating of macros when CoClass name
// change.
// *********************************************************************//
typedef ITaifexTMPConnection TaifexTMPConnection;
typedef ITaifexTMPConnectionPtr TaifexTMPConnectionPtr;

#define LIBID_OF_TaifexTMPConnection (&LIBID_TMPOrderConnection)

// *********************************************************************//
// Declaration of Enumerations defined in Type Library
// *********************************************************************//
enum class RecoverTypeEnum
{
  rtConfirm = 0,
  rtFilled = 1,
  rtAll = 2
};

enum class RecoverMarketEnum
{
  rmFutures = 0,
  rmOption = 1,
  rmTSE = 2,
  rmOTC = 3,
  rmAll = 4
};

enum class MessageLanguageEnum
{
  mlEnglish = 0,
  mlChinese = 1
};

enum class ConnectionTypeEnum
{
  ctSendOrder = 0,
  ctRecvExecution = 1,
  ctBoth = 2
};

enum class LogonResultEnum
{
  lrOK = 1,
  lrFailed = 0,
  lrAlreadyLogon = 0xFFFFFFFF
};

enum class ExecDupEnum
{
  edNewExecution = 0,
  edPossibleDuplicate = 1,
  edSpeedyGenerate = 2
};

// *********************************************************************//
// Interface: ITaifexTMPConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {95454FF6-318C-4EAB-8F98-3AF16F56FB7E}
// *********************************************************************//
interface ITaifexTMPConnection  : public IDispatch
{
public:
  // [1] Create a connection object with a unique name.
  virtual HRESULT STDMETHODCALLTYPE Create(BSTR AppName/*[in]*/) = 0;
  // [2] Destroy a connection object.
  virtual HRESULT STDMETHODCALLTYPE Destroy(void) = 0;
  // [3] Connect to the Speedy Order Gateway
  virtual HRESULT STDMETHODCALLTYPE Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/) = 0;
  // [4] Disconnect.
  virtual HRESULT STDMETHODCALLTYPE Disconnect(void) = 0;
  // [5] Logon to the Speedy Order Gateway
  virtual HRESULT STDMETHODCALLTYPE Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                          Tmporderconnection_tlb::ConnectionTypeEnum Type/*[in]*/) = 0;
  // [6] Place a new order
  virtual HRESULT STDMETHODCALLTYPE NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/) = 0;
  // [7] Send an order replace message.
  virtual HRESULT STDMETHODCALLTYPE ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/) = 0;
  // [8] Send an order cancel message.
  virtual HRESULT STDMETHODCALLTYPE CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/) = 0;
  // [9] Send a quote message.
  virtual HRESULT STDMETHODCALLTYPE Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/) = 0;
  // [10] Send a quote cancel message.
  virtual HRESULT STDMETHODCALLTYPE QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/) = 0;
  // [11] Send a quote request message.
  virtual HRESULT STDMETHODCALLTYPE QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/) = 0;
  // [12] Recover executions from Order Gateway.
  virtual HRESULT STDMETHODCALLTYPE Recover(BSTR BeginTime/*[in]*/,
                                            Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                            Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_ClearMemberID(BSTR* Value/*[out,retval]*/) = 0; // [14]
  virtual HRESULT STDMETHODCALLTYPE set_ClearMemberID(BSTR Value/*[in]*/) = 0; // [14]
  virtual HRESULT STDMETHODCALLTYPE get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [15]
  virtual HRESULT STDMETHODCALLTYPE SetLanguage(Tmporderconnection_tlb::MessageLanguageEnum Lang/*[in]*/) = 0; // [16]
  virtual HRESULT STDMETHODCALLTYPE GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                                     long* NID/*[out,retval]*/) = 0; // [201]
  virtual HRESULT STDMETHODCALLTYPE get_BrokerID(BSTR* Value/*[out,retval]*/) = 0; // [205]
  virtual HRESULT STDMETHODCALLTYPE set_BrokerID(BSTR Value/*[in]*/) = 0; // [205]
  virtual HRESULT STDMETHODCALLTYPE SetDebugLog(BSTR FileName/*[in]*/) = 0; // [207]
  virtual HRESULT STDMETHODCALLTYPE OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/) = 0; // [208]
  virtual HRESULT STDMETHODCALLTYPE Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                             Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                             Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/) = 0; // [209]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  BSTR __fastcall get_ClearMemberID(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_ClearMemberID((BSTR*)&Value));
    return Value;
  }

  VARIANT_BOOL __fastcall get_IsAdministrator(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->get_IsAdministrator((VARIANT_BOOL*)&Value));
    return Value;
  }

  long __fastcall GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/)
  {
    long NID;
    OLECHECK(this->GenerateUniqueID(Type, (long*)&NID));
    return NID;
  }

  BSTR __fastcall get_BrokerID(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_BrokerID((BSTR*)&Value));
    return Value;
  }


  __property   BSTR            ClearMemberID = {read = get_ClearMemberID, write = set_ClearMemberID};
  __property   VARIANT_BOOL    IsAdministrator = {read = get_IsAdministrator};
  __property   BSTR            BrokerID = {read = get_BrokerID, write = set_BrokerID};

#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

// *********************************************************************//
// Interface: ITaifexTMPConnectionEvents
// Flags:     (0)
// GUID:      {45612375-8A01-4B68-BE17-139F20CC483D}
// *********************************************************************//
interface ITaifexTMPConnectionEvents : public TDispWrapper<IDispatch>
{
  void __fastcall OnConnected()
  {
    _TDispID _dispid(/* OnConnected */ DISPID(1));
    OleProcedure(_dispid);
  }

  void __fastcall OnDisconnected()
  {
    _TDispID _dispid(/* OnDisconnected */ DISPID(2));
    OleProcedure(_dispid);
  }

  void __fastcall OnLogonReply(BSTR ReplyString/*[in]*/,
                               Tmporderconnection_tlb::LogonResultEnum Result/*[in]*/,
                               long ConnectionID/*[in]*/)
  {
    _TDispID _dispid(/* OnLogonReply */ DISPID(3));
    TAutoArgs<3> _args;
    _args[1] = ReplyString /*[VT_BSTR:0]*/;
    _args[2] = (int)Result /*[VT_USERDEFINED:0]*/;
    _args[3] = ConnectionID /*[VT_I4:0]*/;
    OleProcedure(_dispid, _args);
  }

  void __fastcall OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg/*[in]*/,
                                    Tmporderconnection_tlb::ExecDupEnum ExecPossDup/*[in]*/)
  {
    _TDispID _dispid(/* OnExecutionReport */ DISPID(4));
    TAutoArgs<2> _args;
    _args[1] = (LPDISPATCH)(Ordermessage_tlb::IExecutionReportMessage*)Msg /*[VT_USERDEFINED:1]*/;
    _args[2] = (int)ExecPossDup /*[VT_USERDEFINED:0]*/;
    OleProcedure(_dispid, _args);
  }

  void __fastcall OnRecoverFinished(long Count/*[in]*/)
  {
    _TDispID _dispid(/* OnRecoverFinished */ DISPID(5));
    TAutoArgs<1> _args;
    _args[1] = Count /*[VT_I4:0]*/;
    OleProcedure(_dispid, _args);
  }


};
#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMITaifexTMPConnection
// Interface: ITaifexTMPConnection
// *********************************************************************//
template <class T /* ITaifexTMPConnection */ >
class TCOMITaifexTMPConnectionT : public TComInterface<ITaifexTMPConnection>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMITaifexTMPConnectionT() {}
  TCOMITaifexTMPConnectionT(ITaifexTMPConnection *intf, bool addRef = false) : TComInterface<ITaifexTMPConnection>(intf, addRef) {}
  TCOMITaifexTMPConnectionT(const TCOMITaifexTMPConnectionT& src) : TComInterface<ITaifexTMPConnection>(src) {}
  TCOMITaifexTMPConnectionT& operator=(const TCOMITaifexTMPConnectionT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall Create(BSTR AppName/*[in]*/);
  HRESULT         __fastcall Destroy(void);
  HRESULT         __fastcall Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/);
  HRESULT         __fastcall Disconnect(void);
  HRESULT         __fastcall Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                   Tmporderconnection_tlb::ConnectionTypeEnum Type/*[in]*/);
  HRESULT         __fastcall NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/);
  HRESULT         __fastcall QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/);
  HRESULT         __fastcall QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/);
  HRESULT         __fastcall Recover(BSTR BeginTime/*[in]*/,
                                     Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                     Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/);
  HRESULT         __fastcall get_ClearMemberID(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_ClearMemberID(void);
  HRESULT         __fastcall set_ClearMemberID(BSTR Value/*[in]*/);
  HRESULT         __fastcall get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_IsAdministrator(void);
  HRESULT         __fastcall SetLanguage(Tmporderconnection_tlb::MessageLanguageEnum Lang/*[in]*/);
  HRESULT         __fastcall GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                              long* NID/*[out,retval]*/);
  long            __fastcall GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/);
  HRESULT         __fastcall get_BrokerID(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_BrokerID(void);
  HRESULT         __fastcall set_BrokerID(BSTR Value/*[in]*/);
  HRESULT         __fastcall SetDebugLog(BSTR FileName/*[in]*/);
  HRESULT         __fastcall OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/);
  HRESULT         __fastcall Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                      Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                      Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/);

  __property   BSTR            ClearMemberID = {read = get_ClearMemberID, write = set_ClearMemberID};
  __property   VARIANT_BOOL    IsAdministrator = {read = get_IsAdministrator};
  __property   BSTR            BrokerID = {read = get_BrokerID, write = set_BrokerID};
};
typedef TCOMITaifexTMPConnectionT<ITaifexTMPConnection> TCOMITaifexTMPConnection;

// *********************************************************************//
// DispIntf:  ITaifexTMPConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {95454FF6-318C-4EAB-8F98-3AF16F56FB7E}
// *********************************************************************//
template<class T>
class ITaifexTMPConnectionDispT : public TAutoDriver<ITaifexTMPConnection>
{
public:
  ITaifexTMPConnectionDispT(){}

  ITaifexTMPConnectionDispT(ITaifexTMPConnection *pintf)
  {
    TAutoDriver<ITaifexTMPConnection>::Bind(pintf, false);
  }

  ITaifexTMPConnectionDispT(ITaifexTMPConnectionPtr pintf)
  {
    TAutoDriver<ITaifexTMPConnection>::Bind(pintf, true);
  }

  ITaifexTMPConnectionDispT& operator=(ITaifexTMPConnection *pintf)
  {
    TAutoDriver<ITaifexTMPConnection>::Bind(pintf, false);
    return *this;
  }

  ITaifexTMPConnectionDispT& operator=(ITaifexTMPConnectionPtr pintf)
  {
    TAutoDriver<ITaifexTMPConnection>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_TaifexTMPConnection));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_TaifexTMPConnection);
  }

  HRESULT         __fastcall Create(BSTR AppName/*[in]*/);
  HRESULT         __fastcall Destroy();
  HRESULT         __fastcall Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/);
  HRESULT         __fastcall Disconnect();
  HRESULT         __fastcall Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                   Tmporderconnection_tlb::ConnectionTypeEnum Type/*[in]*/);
  HRESULT         __fastcall NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/);
  HRESULT         __fastcall QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/);
  HRESULT         __fastcall QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/);
  HRESULT         __fastcall Recover(BSTR BeginTime/*[in]*/,
                                     Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                     Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/);
  HRESULT         __fastcall get_ClearMemberID(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_ClearMemberID(void);
  HRESULT         __fastcall set_ClearMemberID(BSTR Value/*[in]*/);
  HRESULT         __fastcall get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_IsAdministrator(void);
  HRESULT         __fastcall SetLanguage(Tmporderconnection_tlb::MessageLanguageEnum Lang/*[in]*/);
  HRESULT         __fastcall GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                              long* NID/*[out,retval]*/);
  long            __fastcall GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/);
  HRESULT         __fastcall get_BrokerID(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_BrokerID(void);
  HRESULT         __fastcall set_BrokerID(BSTR Value/*[in]*/);
  HRESULT         __fastcall SetDebugLog(BSTR FileName/*[in]*/);
  HRESULT         __fastcall OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/);
  HRESULT         __fastcall Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                      Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                      Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/);

  __property   BSTR            ClearMemberID = {read = get_ClearMemberID, write = set_ClearMemberID};
  __property   VARIANT_BOOL    IsAdministrator = {read = get_IsAdministrator};
  __property   BSTR            BrokerID = {read = get_BrokerID, write = set_BrokerID};
};
typedef ITaifexTMPConnectionDispT<ITaifexTMPConnection> ITaifexTMPConnectionDisp;

// *********************************************************************//
// DispIntf:  ITaifexTMPConnectionEvents
// Flags:     (0)
// GUID:      {45612375-8A01-4B68-BE17-139F20CC483D}
// *********************************************************************//
template <class T>
class ITaifexTMPConnectionEventsDispT : public TAutoDriver<ITaifexTMPConnectionEvents>
{
public:
  ITaifexTMPConnectionEventsDispT(){}

  void Attach(LPUNKNOWN punk)
  { m_Dispatch = static_cast<T*>(punk); }

  void            __fastcall OnConnected();
  void            __fastcall OnDisconnected();
  void            __fastcall OnLogonReply(BSTR ReplyString/*[in]*/,
                                          Tmporderconnection_tlb::LogonResultEnum Result/*[in]*/,
                                          long ConnectionID/*[in]*/);
  void            __fastcall OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg/*[in]*/
                                               ,
                                               Tmporderconnection_tlb::ExecDupEnum ExecPossDup/*[in]*/);
  void            __fastcall OnRecoverFinished(long Count/*[in]*/);

};
typedef ITaifexTMPConnectionEventsDispT<ITaifexTMPConnectionEvents> ITaifexTMPConnectionEventsDisp;

// *********************************************************************//
// SmartIntf: TCOMITaifexTMPConnection
// Interface: ITaifexTMPConnection
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::Create(BSTR AppName/*[in]*/)
{
  return (*this)->Create(AppName);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::Destroy(void)
{
  return (*this)->Destroy();
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/)
{
  return (*this)->Connect(RemoteIP, RemotePort);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::Disconnect(void)
{
  return (*this)->Disconnect();
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                    Tmporderconnection_tlb::ConnectionTypeEnum Type/*[in]*/)
{
  return (*this)->Logon(ID, PASSWD, ACCOUNT, Type);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/)
{
  return (*this)->NewOrder(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/)
{
  return (*this)->ReplaceOrder(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/)
{
  return (*this)->CancelOrder(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/)
{
  return (*this)->Quote(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/)
{
  return (*this)->QuoteCancel(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/)
{
  return (*this)->QuoteRequest(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::Recover(BSTR BeginTime/*[in]*/,
                                      Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                      Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/)
{
  return (*this)->Recover(BeginTime, Type, Market);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::get_ClearMemberID(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_ClearMemberID(Value);
}

template <class T> BSTR __fastcall
TCOMITaifexTMPConnectionT<T>::get_ClearMemberID(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_ClearMemberID((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::set_ClearMemberID(BSTR Value/*[in]*/)
{
  return (*this)->set_ClearMemberID(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->get_IsAdministrator(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMITaifexTMPConnectionT<T>::get_IsAdministrator(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->get_IsAdministrator((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::SetLanguage(Tmporderconnection_tlb::MessageLanguageEnum Lang/*[in]*/)
{
  return (*this)->SetLanguage(Lang);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                               long* NID/*[out,retval]*/)
{
  return (*this)->GenerateUniqueID(Type, NID);
}

template <class T> long __fastcall
TCOMITaifexTMPConnectionT<T>::GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/)
{
  long NID;
  OLECHECK(this->GenerateUniqueID(Type/*[in]*/, (long*)&NID));
  return NID;
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::get_BrokerID(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_BrokerID(Value);
}

template <class T> BSTR __fastcall
TCOMITaifexTMPConnectionT<T>::get_BrokerID(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_BrokerID((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::set_BrokerID(BSTR Value/*[in]*/)
{
  return (*this)->set_BrokerID(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::SetDebugLog(BSTR FileName/*[in]*/)
{
  return (*this)->SetDebugLog(FileName);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/)
{
  return (*this)->OrderStatusRequest(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexTMPConnectionT<T>::Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                       Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                       Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/)
{
  return (*this)->Recover2(BeginTime, EndTime, Type, Market);
}

// *********************************************************************//
// DispIntf:  ITaifexTMPConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {95454FF6-318C-4EAB-8F98-3AF16F56FB7E}
// *********************************************************************//
template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::Create(BSTR AppName/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Create"), DISPID(1));
  TAutoArgs<1> _args;
  _args[1] = AppName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::Destroy()
{
  _TDispID _dispid(*this, OLETEXT("Destroy"), DISPID(2));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Connect"), DISPID(3));
  TAutoArgs<2> _args;
  _args[1] = RemoteIP /*[VT_BSTR:0]*/;
  _args[2] = RemotePort /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::Disconnect()
{
  _TDispID _dispid(*this, OLETEXT("Disconnect"), DISPID(4));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                    Tmporderconnection_tlb::ConnectionTypeEnum Type/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Logon"), DISPID(5));
  TAutoArgs<4> _args;
  _args[1] = ID /*[VT_BSTR:0]*/;
  _args[2] = PASSWD /*[VT_BSTR:0]*/;
  _args[3] = ACCOUNT /*[VT_BSTR:0]*/;
  _args[4] = (int)Type /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("NewOrder"), DISPID(6));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::INewOrderMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("ReplaceOrder"), DISPID(7));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IReplaceOrderMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("CancelOrder"), DISPID(8));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::ICancelOrderMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Quote"), DISPID(9));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IQuoteMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("QuoteCancel"), DISPID(10));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IQuoteCancelMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("QuoteRequest"), DISPID(11));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IQuoteRequestMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::Recover(BSTR BeginTime/*[in]*/,
                                      Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                      Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Recover"), DISPID(12));
  TAutoArgs<3> _args;
  _args[1] = BeginTime /*[VT_BSTR:0]*/;
  _args[2] = (int)Type /*[VT_USERDEFINED:0]*/;
  _args[3] = (int)Market /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::get_ClearMemberID(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("ClearMemberID"), DISPID(14));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
ITaifexTMPConnectionDispT<T>::get_ClearMemberID(void)
{
  BSTR Value;
  this->get_ClearMemberID((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::set_ClearMemberID(BSTR Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("ClearMemberID"), DISPID(14));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BSTR:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("IsAdministrator"), DISPID(15));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
ITaifexTMPConnectionDispT<T>::get_IsAdministrator(void)
{
  VARIANT_BOOL Value;
  this->get_IsAdministrator((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::SetLanguage(Tmporderconnection_tlb::MessageLanguageEnum Lang/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetLanguage"), DISPID(16));
  TAutoArgs<1> _args;
  _args[1] = (int)Lang /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                               long* NID/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GenerateUniqueID"), DISPID(201));
  TAutoArgs<1> _args;
  _args[1] = (int)Type /*[VT_USERDEFINED:0]*/;
  return OutRetValSetterPtr(NID /*[VT_I4:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> long __fastcall
ITaifexTMPConnectionDispT<T>::GenerateUniqueID(Ordermessage_tlb::MessageTypeEnum Type/*[in]*/)
{
  long NID;
  this->GenerateUniqueID(Type, (long*)&NID);
  return NID;
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::get_BrokerID(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("BrokerID"), DISPID(205));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
ITaifexTMPConnectionDispT<T>::get_BrokerID(void)
{
  BSTR Value;
  this->get_BrokerID((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::set_BrokerID(BSTR Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("BrokerID"), DISPID(205));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BSTR:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::SetDebugLog(BSTR FileName/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetDebugLog"), DISPID(207));
  TAutoArgs<1> _args;
  _args[1] = FileName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("OrderStatusRequest"), DISPID(208));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IOrderStatusRequestMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexTMPConnectionDispT<T>::Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                       Tmporderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                       Tmporderconnection_tlb::RecoverMarketEnum Market/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Recover2"), DISPID(209));
  TAutoArgs<4> _args;
  _args[1] = BeginTime /*[VT_BSTR:0]*/;
  _args[2] = EndTime /*[VT_BSTR:0]*/;
  _args[3] = (int)Type /*[VT_USERDEFINED:0]*/;
  _args[4] = (int)Market /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// DispIntf:  ITaifexTMPConnectionEvents
// Flags:     (0)
// GUID:      {45612375-8A01-4B68-BE17-139F20CC483D}
// *********************************************************************//
template <class T> void __fastcall
ITaifexTMPConnectionEventsDispT<T>::OnConnected()
{
  _TDispID _dispid(/* OnConnected */ DISPID(1));
  OleProcedure(_dispid);
}

template <class T> void __fastcall
ITaifexTMPConnectionEventsDispT<T>::OnDisconnected()
{
  _TDispID _dispid(/* OnDisconnected */ DISPID(2));
  OleProcedure(_dispid);
}

template <class T> void __fastcall
ITaifexTMPConnectionEventsDispT<T>::OnLogonReply(BSTR ReplyString/*[in]*/,
                                                 Tmporderconnection_tlb::LogonResultEnum Result/*[in]*/
                                                 , long ConnectionID/*[in]*/)
{
  _TDispID _dispid(/* OnLogonReply */ DISPID(3));
  TAutoArgs<3> _args;
  _args[1] = ReplyString /*[VT_BSTR:0]*/;
  _args[2] = (int)Result /*[VT_USERDEFINED:0]*/;
  _args[3] = ConnectionID /*[VT_I4:0]*/;
  OleProcedure(_dispid, _args);
}

template <class T> void __fastcall
ITaifexTMPConnectionEventsDispT<T>::OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg/*[in]*/
                                                      ,
                                                      Tmporderconnection_tlb::ExecDupEnum ExecPossDup/*[in]*/)
{
  _TDispID _dispid(/* OnExecutionReport */ DISPID(4));
  TAutoArgs<2> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IExecutionReportMessage*)Msg /*[VT_USERDEFINED:1]*/;
  _args[2] = (int)ExecPossDup /*[VT_USERDEFINED:0]*/;
  OleProcedure(_dispid, _args);
}

template <class T> void __fastcall
ITaifexTMPConnectionEventsDispT<T>::OnRecoverFinished(long Count/*[in]*/)
{
  _TDispID _dispid(/* OnRecoverFinished */ DISPID(5));
  TAutoArgs<1> _args;
  _args[1] = Count /*[VT_I4:0]*/;
  OleProcedure(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that
// provide static Create() and CreateRemote(LPWSTR machineName) methods
// for creating an instance of an exposed object. These functions can
// be used by client wishing to automate CoClasses exposed by this
// typelibrary.
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : TaifexTMPConnection
// Interface: TCOMITaifexTMPConnection
// *********************************************************************//
typedef TCoClassCreatorT<TCOMITaifexTMPConnection, ITaifexTMPConnection, &CLSID_TaifexTMPConnection, &IID_ITaifexTMPConnection> CoTaifexTMPConnection;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


#if !defined(__TLB_NO_EVENT_WRAPPERS) && defined(USING_ATLVCL)
// *********************************************************************//
// CONNECTIONPOINT/EVENT PROXY
// CoClass         : TaifexTMPConnection
// Event Interface : ITaifexTMPConnectionEvents
// *********************************************************************//
template <class T>
class TEvents_TaifexTMPConnection : public IConnectionPointImpl<T,
                                                 &DIID_ITaifexTMPConnectionEvents,
#if !defined(_TLB_DYNAMIC_CONNECTIONPOINT_ARRAY)
                                                 CComUnkArray<CONNECTIONPOINT_ARRAY_SIZE> >
#else
                                                 CComDynamicArray>
#endif
{
public:
  void            Fire_OnConnected(void);
  void            Fire_OnDisconnected(void);
  void            Fire_OnLogonReply(BSTR ReplyString, Tmporderconnection_tlb::LogonResultEnum Result,
                                    long ConnectionID);
  void            Fire_OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg,
                                         Tmporderconnection_tlb::ExecDupEnum ExecPossDup);
  void            Fire_OnRecoverFinished(long Count);
protected:
  ITaifexTMPConnectionEventsDisp m_EventIntfObj;
};

template <class T> void
TEvents_TaifexTMPConnection<T>::Fire_OnConnected(void)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnConnected();
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_TaifexTMPConnection<T>::Fire_OnDisconnected(void)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnDisconnected();
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_TaifexTMPConnection<T>::Fire_OnLogonReply(BSTR ReplyString,
                                                  Tmporderconnection_tlb::LogonResultEnum Result,
                                                  long ConnectionID)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnLogonReply(ReplyString, Result, ConnectionID);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_TaifexTMPConnection<T>::Fire_OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg,
                                                       Tmporderconnection_tlb::ExecDupEnum ExecPossDup)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnExecutionReport(Msg, ExecPossDup);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_TaifexTMPConnection<T>::Fire_OnRecoverFinished(long Count)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnRecoverFinished(Count);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

#endif  //   __TLB_NO_EVENT_WRAPPERS

};     // namespace Tmporderconnection_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Tmporderconnection_tlb;
#endif

#pragma option pop

#endif // TMPOrderConnection_TLBH

