unit MDComponentStrings;

interface

uses Windows;

{ Strings for CandleStickChart }
resourcestring
  MD_SpeedyUnify_AppName = 'Mega Unify';
  MD_CANDEL_FILL = '成交:%s';
  MD_CANDEL_FILL_EMPTY = '成交:-----';
  MD_CANDEL_HIGH_LOW = '漲跌:%s';
  MD_CANDEL_HIGH_LOW_EMPTY = '漲跌:-----';
  MD_CANDEL_QTY = '成交量:%d';
  MD_CANDEL_QTY_EMPTY = '成交量:-----';
  MD_CANDEL_TIME = '時間:%s';
  MD_CANDEL_TIME_EMPTY = '時間:-----';
  MD_STORE_EXCHANGE_TAIFEX = '台灣期貨交易所';
  MD_STORE_EXCHANGE_TWSE = '台灣證券交易所';
  MD_STORE_EXCHANGE_OTC = '台灣櫃檯買賣中心';

  MD_STORE_EXCHANGE_SGX = '新加坡SGX';

  MD_STORE_EXCHANGE_CME = '芝加哥CME';
  MD_STORE_EXCHANGE_CBOT = '芝加哥CBOT';
  MD_STORE_EXCHANGE_NYMEX = '芝加哥NYMEX';
  MD_STORE_EXCHANGE_NYBOT = '紐約NYBOT';
  MD_STORE_EXCHANGE_LIF = '倫敦期貨交易所LIF';
  MD_STORE_EXCHANGE_LME = '倫敦金屬交易所LME';
  MD_STORE_EXCHANGE_EUX = '歐洲期貨交易所EUX';

  MD_STORE_EXCHANGE_HKEX = '香港HKEx';
  MD_STORE_EXCHANGE_SHFE = '上海期貨交易所';
  MD_STORE_EXCHANGE_CFFEX = '中國金融交易所';
  MD_STORE_EXCHANGE_CZCE = '鄭州商品交易所';
  MD_STORE_EXCHANGE_DCE = '大連商品交易所';
  MD_STORE_EXCHANGE_SSE = '上海證券交易所';

  MD_STORE_EXCHANGE_TOCOM = '東工TOCOM';
  MD_STORE_EXCHANGE_OSE = '大阪OSE';
  MD_STORE_EXCHANGE_TGE = '東穀TGE';

  MD_STORE_EXCHNAGE_KRX = '韓國KRX';
  MD_STORE_EXCHNAGE_TFX = '台灣TAIFEX';
  MD_STORE_EXCHANGE_BMD = '馬來西亞衍生產品交易所';

  MD_CHART_OPEN_PX_EMPTY = '開盤價:-----';
  MD_CHART_HIGH_PX_EMPTY = '最高價:-----';
  MD_CHART_LOW_PX_EMPTY = '最低價:-----';
  MD_CHART_CLOSE_PX_EMPTY = '收盤價:-----';
  MD_CHART_FILL_QTY_EMPTY = '成交量:-----';

  MD_CHART_TIME = '時間:';
  MD_CHART_OPEN_PX = '開盤價:';
  MD_CHART_HIGH_PX = '最高價:';
  MD_CHART_LOW_PX = '最低價:';
  MD_CHART_CLOSE_PX = '收盤價:';
  MD_CHART_FILL_QTY = '成交量:';

  MD_OPTIONS_TBAR_CALL = '買權';
  MD_OPTIONS_TBAR_PUT = '賣權';
  MD_OPTIONS_TBAR_BIDPX = '委買價';
  MD_OPTIONS_TBAR_ASKPX = '委賣價';
  MD_OPTIONS_TBAR_FILLPX = '成交價';
  MD_OPTIONS_TBAR_UPDOWNPX = '漲跌價';
  MD_OPTIONS_TBAR_QTY = '單量';
  MD_OPTIONS_TBAR_TOTALQTY = '總量';
  MD_OPTIONS_TBAR_HIGH = '最高';
  MD_OPTIONS_TBAR_LOW = '最低';
  MD_OPTIONS_TBAR_STRIKEPX = '履約價';
  MD_OPTIONS_TBAR_SETTLEMENT_PX = '結算價';
  MD_OPTIONS_TBAR_OPEN_INTEREST = '未平倉';
  MD_OPTIONS_TBAR_DELTA = 'Delta';
  MD_OPTIONS_TBAR_GAMMA = 'Gamma';
  MD_OPTIONS_TBAR_THETA = 'Theta';
  MD_OPTIONS_TBAR_VEGA = 'Vega';
  MD_OPTIONS_TBAR_RHO = 'Rho';
  MD_OPTIONS_TBAR_DIFF_OI = '持倉量變動';
  MD_OPTIONS_TBAR_BUY_QTY = '買量';
  MD_OPTIONS_TBAR_SELL_QTY = '賣量';
  MD_OPTIONS_TBAR_IMP_VAR = '隱波率';
  MD_OPTIONS_TBAR_THEORY_PX = '理論價';

  MD_MDLIST_SYMBOL = '商品名稱';
  MD_MDLIST_BID_QTY = '委買量';
  MD_MDLIST_ASK_QTY = '委賣量';
  MD_MDLIST_BID_TOTAL_QTY = '總委買量';
  MD_MDLIST_ASK_TOTAL_QTY = '總委賣量';
  MD_MDLIST_OPEN_PX = '開盤價';
  MD_MDLIST_OPEN_INTEREST = '未平倉';
  MD_MDLIST_SETTLEMENT_PX = '結算價';
  MD_MDLIST_PREV_CLOSE_PX = '昨收';
  MD_MDLIST_UP_DOWN = '漲跌';
  MD_MDLIST_UP_DOWN_RATE = '漲跌幅';
  MD_MDLIST_FILL_TIME = '成交時間';

  MD_ORDERBOOK_FILL_BUY = '買成';
  MD_ORDERBOOK_FILL_SELL = '賣成';
  MD_ORDERBOOK_STOPPX = '觸價';
  MD_ORDERBOOK_OCO = 'OCO';
  MD_ORDERBOOK_CANCEL = '刪';
  MD_ORDERBOOK_BUY_IN = '買進';
  MD_ORDERBOOK_BUY_ORDER = '委買';
  MD_ORDERBOOK_SELL_ORDER = '委賣';
  MD_ORDERBOOK_SELL_OFF = '賣出';
  MD_ORDERBOOK_ORDER = '委託';
  MD_ORDERBOOK_MARKET = '市場';
  MD_ORDERBOOK_BUY = '買';
  MD_ORDERBOOK_SELL = '賣';
  MD_ORDERBOOK_NOPOSITION = '您尚未擁有該部位';

  MD_ORDERLIST_CANCELALL = '全刪';
  MD_ORDERLIST_TIME = '時間';
  MD_ORDERLIST_ORDERID = '單號';
  MD_ORDERLIST_NAME = '商品名稱';
  MD_ORDERLIST_SYMBOL = '代碼';
  MD_ORDERLIST_DATE = '年月';
  MD_ORDERLIST_CALL_PUT = 'C/P';
  MD_ORDERLIST_STRIKE_PX = '履約價';
  MD_ORDERLIST_SYM_LEG1 = '代碼1';
  MD_ORDERLIST_DATE_LEG1 = '年月1';
  MD_ORDERLIST_CALL_PUT1 = 'C/P1';
  MD_ORDERLIST_STRIKE_PX1 = '履約價1';
  MD_ORDERLIST_SYM_LEG2 = '代碼2';
  MD_ORDERLIST_DATE_LEG2 = '年月2';
  MD_ORDERLIST_CALL_PUT2 = 'C/P2';
  MD_ORDERLIST_STRIKE_PX2 = '履約價2';
  MD_ORDERLIST_SIDE = 'BS';
  MD_ORDERLIST_SIDE_LEG1 = 'BS1';
  MD_ORDERLIST_SIDE_LEG2 = 'BS2';
  MD_ORDERLIST_PRICE = '價格';
  MD_ORDERLIST_AVG_PX = '均價';
  MD_ORDERLIST_FILL_PX = '成交價';
  MD_ORDERLIST_FILL_PX1 = '成交價1';
  MD_ORDERLIST_FILL_PX2 = '成交價2';
  MD_ORDERLIST_STATUS = '狀態';
  MD_ORDERLIST_ST_NEW = '委託';
  MD_ORDERLIST_ST_FILLED = '成交';
  MD_ORDERLIST_LEAVES_QTY = '剩餘';
  MD_ORDERLIST_OPEN_CLOSE = '倉別';
  MD_ORDERLIST_ORDER_TYPE = '單別';
  MD_ORDERLIST_ORDER_COND = '委託條件';
  MD_ORDERLIST_ERROR_CODE = '錯誤碼';
  MD_ORDERLIST_STRATEGY_NAME = '策略名';
  MD_ORDERLIST_MESSGAE = '訊息';
  MD_ORDERLIST_STOP_PX = '觸價';

  MD_ORDERLIST_CONFIRM_DELETE = '確定要刪除？';
  MD_ORDERLIST_CONFIRM_DELETE_ALL_STOP_ORDER = '刪除全部觸價單';
  MD_ORDERLIST_CONFIRM_DELETE_ALL_ACTIVE_ORDER = '刪除全部 Active Order';
  MD_ORDERLIST_CONFIRM_UP_ARROW = '▲';
  MD_ORDERLIST_CONFIRM_DOWN_ARROW = '▼';

  MD_ORDERSTORE_CONNECTION_NOT_EXIST_EXCEPTION = '『交易所連線物件』不存在 !';
  MD_ORDERSTORE_CONNECTION_NOT_CONNECTED = '『交易所連線物件』尚未建立連線 !';
  MD_ORDERSTORE_CONNECTION_NOT_LOGON = '『交易所連線物件』尚未登入 !';
  MD_ORDERSTORE_NEW_ORDER_ERROR = '『交易所連線物件』新單錯誤 !';
  MD_ORDERSTORE_CANCEL_ERROR = '『交易所連線物件』刪單錯誤 !';
  MD_ORDERSTORE_AMEND_ERROR = '『交易所連線物件』改量錯誤 !';
  MD_ORDERSTORE_REPLACE_PRICE_ERROR = '『交易所線物件』改價錯誤 !';

  MD_ORDERSTORE_QUERY_FEE_NO_DATA = '手續費查詢失敗,無資料';
  MD_ORDERSTORE_QUERY_FEE_NO_FEE_DATA = '手續費查詢失敗,無手續費資料';
  MD_ORDERSTORE_QUERY_FEE_FAILED_PREFIX = '手續費查詢失敗,原因:';
  MD_ORDERSTORE_QUERY_FEE_FAILED = '手續費查詢失敗';
  MD_ORDERSTORE_QUERY_TAX_NO_DATA = '稅率查詢失敗,無資料';
  MD_ORDERSTORE_QUERY_TAX_NO_TAX_DATA = '稅率查詢失敗,無稅率資料';
  MD_ORDERSTORE_QUERY_TAX_FAILED_PREFIX = '稅率查詢失敗,原因:';
  MD_ORDERSTORE_QUERY_TAX_FAILED = '稅率查詢失敗';
  MD_ORDERSTORE_QUERY_OVERSEAS_FEE_NO_DATA = '海外手續費查詢失敗,無資料';
  MD_ORDERSTORE_QUERY_OVERSEAS_FEE_NO_FEE_DATA = '海外手續費查詢失敗,無手續費資料';
  MD_ORDERSTORE_QUERY_OVERSEAS_FEE_FAILED_PREFIX = '海外手續費查詢失敗,原因:';
  MD_ORDERSTORE_QUERY_OVERSEAS_FEE_FAILED = '海外手續費查詢失敗';
  MD_ORDERSTORE_STOP_ORDER_BUY_STOP_PRICE1 = '買進時，觸價價格(';
  MD_ORDERSTORE_STOP_ORDER_BUY_STOP_PRICE2 = ')必須大於市價(';
  MD_ORDERSTORE_STOP_ORDER_BUY_ORDER_PRICE1 = '買進時，委託價(';
  MD_ORDERSTORE_STOP_ORDER_BUY_ORDER_PRICE2 = ')必須大於或等於觸價價格(';
  MD_ORDERSTORE_STOP_ORDER_SELL_STOP_PRICE1 = '賣出時，觸價價格(';
  MD_ORDERSTORE_STOP_ORDER_SELL_STOP_PRICE2 = ')必須低於市價(';
  MD_ORDERSTORE_STOP_ORDER_SELL_ORDER_PRICE1 = '賣出時，委託價(';
  MD_ORDERSTORE_STOP_ORDER_SELL_ORDER_PRICE2 = ')必須小於或等於觸價價格(';
  MD_ORDERSTORE_STOP_ORDER_SUFFIX = ')';
  MD_ORDERSTORE_STOP_ORDER_NEW_TEXT1 = '觸發條件 商品[';
  MD_ORDERSTORE_STOP_ORDER_NEW_TEXT2 = ']  價格[';
  MD_ORDERSTORE_STOP_ORDER_NEW_TEXT3 = ']';
  MD_ORDERSTORE_STOP_ORDER_NEW_ERROR = '尚未有成交資料';

  MD_ORDERSTORE_QUERY_TAIFEX_OI_NO_DATA = '昨日留倉查詢失敗,無資料';
  MD_ORDERSTORE_QUERY_TAIFEX_OI_NO_ORDER_DATA = '昨日留倉查詢失敗,無委託資料';
  MD_ORDERSTORE_QUERY_TAIFEX_OI_FAILED_PREFIX = '昨日留倉查詢失敗,原因:';
  MD_ORDERSTORE_QUERY_TAIFEX_OI_FAILED = '昨日留倉查詢失敗';
  MD_ORDERSTORE_QUERY_OVERSEAS_OI_NO_DATA = '海外昨日留倉查詢失敗,無資料';
  MD_ORDERSTORE_QUERY_OVERSEAS_OI_NO_ORDER_DATA = '海外昨日留倉查詢失敗,無委託資料';
  MD_ORDERSTORE_QUERY_OVERSEAS_OI_FAILED_PREFIX = '海外昨日留倉查詢失敗,原因:';
  MD_ORDERSTORE_QUERY_OVERSEAS_OI_FAILED = '海外昨日留倉查詢失敗';

  MD_EXECUTION_PENDING = '傳送中';
  MD_EXECUTION_NEW = '新增';
  MD_EXECUTION_REPLACE_QTY = '改量';
  MD_EXECUTION_REPLACE_PX = '改價';
  MD_EXECUTION_CANCEL = '刪除';
  MD_EXECUTION_FILL = '成交';
  MD_EXECUTION_REJECT = '失敗';
  MD_EXECUTION_STATUS = '狀態';
  MD_EXECUTION_FUTURES = '期貨';
  MD_EXECUTION_OPTIONS = '選擇權';
  MD_EXECUTION_POSITION_EFFECT_OPEN = '新倉';
  MD_EXECUTION_POSITION_EFFECT_CLOSE = '平倉';
  MD_EXECUTION_POSITION_EFFECT_ROLLED = '當沖';
  MD_EXECUTION_POSITION_EFFECT_DAY_TRADE = '當沖';
  MD_EXECUTION_POSITION_EFFECT_MARKET_MAKER = '造市';
  MD_EXECUTION_ORDER_TYPE_MARKET = '市價';
  MD_EXECUTION_ORDER_TYPE_LIMIT = '限價';
  MD_EXECUTION_ORDER_TYPE_STOP = '停損市價';
  MD_EXECUTION_ORDER_TYPE_STOP_LIMIT = '停損限價';
  MD_EXECUTION_BUY = '買';
  MD_EXECUTION_SELL = '賣';

  MD_SG_BUY = '買入';
  MD_SG_SELL = '賣出';
  MD_SG_OPEN = '開倉';
  MD_SG_CLOSE = '平倉';
  MD_SG_CLOSE_TODAY = '平今';
  MD_SG_SPECULATE = '投機';
  MD_SG_HEDGE = '保值';
  MD_SG_WAITING = '等待發出';
  MD_SG_BAODANING = '正在申報';
  MD_SG_ALREADY_BAODANED = '已經報入';
  MD_SG_PARTIAL_COMPLETED = '部分成交';
  MD_SG_COMPLETED = '全部成交';
  MD_SG_DELETEING = '等待撤除';
  MD_SG_ERROR_ORDER = '錯誤委託';
  MD_SG_SYSTEM_DISABLE = '場內拒絕';
  MD_SG_TOTAL_DELETED = '已經撤銷';
  MD_SG_PARTIAL_COMPLETED_AND_DELETED = '部成部撤';
  MD_SG_LIMIT = '限價';
  MD_SG_MARKET = '市價';
  MD_SG_AT_BEST = '最優價';
  MD_SG_STOP_LOSS = '市價止損';
  MD_SG_TAKE_PROFIT = '市價止盈';
  MD_SG_STOP_LIMIT_LOSS = '限價止損';
  MD_SG_TAKE_LIMIT_PROFIT = '限價止盈';
  MD_SG_GFD = '當日有效(GFD)';
  MD_SG_FOK = '全成或全撤(FOK)';
  MD_SG_FAK = '剩餘即撤單(FAK)';

implementation

end.
