// ************************************************************************ //
// WARNING
// -------
// The types declared in this file were generated from data read from a
// Type Library. If this type library is explicitly or indirectly (via
// another type library referring to this type library) re-imported, or the
// 'Refresh' command of the Type Library Editor activated while editing the
// Type Library, the contents of this file will be regenerated and all
// manual modifications will be lost.
// ************************************************************************ //

// $Rev: 18756 $
// File generated on 2015/9/22 ¤U¤È 11:48:40 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\src\COM\OrderConnection\OrderConnection (1)
// LIBID: {46091260-130A-4199-B111-117EB8DFEEFC}
// LCID: 0
// Helpfile:
// HelpString: Speedy Order Connection Library
// DepndLst:
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
//   (2) v1.0 OrderMessage, (C:\MBus\lib\OrderMessage.dll)
// ************************************************************************ //
#ifndef   OrderConnection_TLBH
#define   OrderConnection_TLBH

#pragma option push -b -a4 -w-inl

#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif
#include "OrderMessage_TLB.h"


// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Orderconnection_tlb
{

// *********************************************************************//
// HelpString: Speedy Order Connection Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:
//   Type Libraries     : LIBID_xxxx
//   CoClasses          : CLSID_xxxx
//   DISPInterfaces     : DIID_xxxx
//   Non-DISP interfaces: IID_xxxx
// *********************************************************************//
extern __declspec (package) const GUID LIBID_OrderConnection;
extern __declspec (package) const GUID IID_ITaifexConnection;
extern __declspec (package) const GUID DIID_ITaifexConnectionEvents;
extern __declspec (package) const GUID CLSID_TaifexConnection;
extern __declspec (package) const GUID GUID_RecoverTypeEnum;
extern __declspec (package) const GUID GUID_RecoverMarketEnum;
extern __declspec (package) const GUID GUID_MessageLanguageEnum;
extern __declspec (package) const GUID GUID_ConnectionTypeEnum;
extern __declspec (package) const GUID GUID_SellSideTypeEnum;
extern __declspec (package) const GUID GUID_LogonResultEnum;
extern __declspec (package) const GUID GUID_ExecDupEnum;
extern __declspec (package) const GUID GUID_APIEnum;

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary
// *********************************************************************//
enum class    RecoverTypeEnum;
enum class    RecoverMarketEnum;
enum class    MessageLanguageEnum;
enum class    ConnectionTypeEnum;
enum class    SellSideTypeEnum;
enum class    LogonResultEnum;
enum class    ExecDupEnum;
enum class    APIEnum;
interface DECLSPEC_UUID("{E491C857-AF5A-492B-BE8B-58A6BB54F7B4}") ITaifexConnection;
typedef TComInterface<ITaifexConnection, &IID_ITaifexConnection> ITaifexConnectionPtr;

interface DECLSPEC_UUID("{9C278915-C60C-43F3-81C9-586D1AB00F03}") ITaifexConnectionEvents;
typedef TComInterface<ITaifexConnectionEvents, &DIID_ITaifexConnectionEvents> ITaifexConnectionEventsPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library
// (NOTE: Here we map each CoClass to its Default Interface)
//
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this
// TypeLibrary. It simplifies the updating of macros when CoClass name
// change.
// *********************************************************************//
typedef ITaifexConnection TaifexConnection;
typedef ITaifexConnectionPtr TaifexConnectionPtr;

#define LIBID_OF_TaifexConnection (&LIBID_OrderConnection)

// *********************************************************************//
// Declaration of Enumerations defined in Type Library
// *********************************************************************//
enum class RecoverTypeEnum
{
  rtConfirm = 0,
  rtFilled = 1,
  rtAll = 2
};

enum class RecoverMarketEnum
{
  rmFutures = 0,
  rmOption = 1,
  rmTSE = 2,
  rmOTC = 3,
  rmAll = 4,
  rmPATSFutures = 5,
  rmCNFutures = 6
};

enum class MessageLanguageEnum
{
  mlEnglish = 0,
  mlChinese = 1
};

enum class ConnectionTypeEnum
{
  ctSendOrder = 0,
  ctRecvExecution = 1,
  ctBoth = 2,
  ctRecvFillOnly = 3,
  ctRecvConfirmOnly = 4
};

enum class SellSideTypeEnum
{
  ssTAIFEX = 0,
  ssTSEOTC = 1,
  ssPATS = 2,
  ssSGCN = 3
};

enum class LogonResultEnum
{
  lrOK = 1,
  lrFailed = 0,
  ltAlreadyLogon = 0xFFFFFFFF
};

enum class ExecDupEnum
{
  edNewExecution = 0,
  edPossibleDuplicate = 1,
  edSpeedyGenerate = 2
};

enum class APIEnum
{
  aeSpeedy = 0,
  aeCTP = 1,
  aeFemas = 2,
  aeKSFt = 3,
  aeKSOpt = 4,
  aeHSctp = 5,
  aeHSufx = 6,
  aeKNctp = 7
};

// *********************************************************************//
// Interface: ITaifexConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {E491C857-AF5A-492B-BE8B-58A6BB54F7B4}
// *********************************************************************//
interface ITaifexConnection  : public IDispatch
{
public:
  // [1] Create a connection object with a unique name.
  virtual HRESULT STDMETHODCALLTYPE Create(BSTR AppName/*[in]*/) = 0;
  // [2] Destroy a connection object.
  virtual HRESULT STDMETHODCALLTYPE Destroy(void) = 0;
  // [3] Connect to the Speedy Order Gateway
  virtual HRESULT STDMETHODCALLTYPE Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/) = 0;
  // [4] Disconnect.
  virtual HRESULT STDMETHODCALLTYPE Disconnect(void) = 0;
  // [5] Logon to the Speedy Order Gateway
  virtual HRESULT STDMETHODCALLTYPE Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                          Orderconnection_tlb::ConnectionTypeEnum Type/*[in]*/) = 0;
  // [6] Place a new order
  virtual HRESULT STDMETHODCALLTYPE NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/) = 0;
  // [7] Send an order replace message.
  virtual HRESULT STDMETHODCALLTYPE ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/) = 0;
  // [8] Send an order cancel message.
  virtual HRESULT STDMETHODCALLTYPE CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/) = 0;
  // [9] Send a quote message.
  virtual HRESULT STDMETHODCALLTYPE Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/) = 0;
  // [10] Send a quote cancel message.
  virtual HRESULT STDMETHODCALLTYPE QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/) = 0;
  // [11] Send a quote request message.
  virtual HRESULT STDMETHODCALLTYPE QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/) = 0;
  // [12] Recover executions from Order Gateway.
  virtual HRESULT STDMETHODCALLTYPE Recover(BSTR BeginTime/*[in]*/,
                                            Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                            Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_ClearMemberID(BSTR* Value/*[out,retval]*/) = 0; // [14]
  virtual HRESULT STDMETHODCALLTYPE set_ClearMemberID(BSTR Value/*[in]*/) = 0; // [14]
  virtual HRESULT STDMETHODCALLTYPE get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [15]
  virtual HRESULT STDMETHODCALLTYPE SetLanguage(Orderconnection_tlb::MessageLanguageEnum Lang/*[in]*/) = 0; // [16]
  virtual HRESULT STDMETHODCALLTYPE GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                                     Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                                     __int64* NID/*[out,retval]*/) = 0; // [201]
  virtual HRESULT STDMETHODCALLTYPE GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                                BSTR* BrokerID/*[out,retval]*/) = 0; // [202]
  virtual HRESULT STDMETHODCALLTYPE SetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                                BSTR Value/*[in]*/) = 0; // [203]
  virtual HRESULT STDMETHODCALLTYPE Create2(BSTR AppName/*[in]*/) = 0; // [204]
  virtual HRESULT STDMETHODCALLTYPE get_BrokerID(BSTR* Value/*[out,retval]*/) = 0; // [205]
  virtual HRESULT STDMETHODCALLTYPE set_BrokerID(BSTR Value/*[in]*/) = 0; // [205]
  virtual HRESULT STDMETHODCALLTYPE get_UseNewFuturesSymbol(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [206]
  virtual HRESULT STDMETHODCALLTYPE set_UseNewFuturesSymbol(VARIANT_BOOL Value/*[in]*/) = 0; // [206]
  virtual HRESULT STDMETHODCALLTYPE SetDebugLog(BSTR FileName/*[in]*/) = 0; // [207]
  virtual HRESULT STDMETHODCALLTYPE OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/) = 0; // [208]
  virtual HRESULT STDMETHODCALLTYPE Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                             Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                             Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/) = 0; // [209]
  virtual HRESULT STDMETHODCALLTYPE set_SendFillZeroQty(VARIANT_BOOL Param1/*[in]*/) = 0; // [210]
  virtual HRESULT STDMETHODCALLTYPE NewsRequest(Ordermessage_tlb::INewsMessage* NewsReq/*[in]*/) = 0; // [211]
  virtual HRESULT STDMETHODCALLTYPE LockThisAE(VARIANT_BOOL Locked/*[in]*/) = 0; // [212]
  virtual HRESULT STDMETHODCALLTYPE set_EnableFilledStatus(VARIANT_BOOL Value/*[in]*/) = 0; // [213]
  virtual HRESULT STDMETHODCALLTYPE get_EnablePandingNewAck(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [214]
  virtual HRESULT STDMETHODCALLTYPE set_EnablePandingNewAck(VARIANT_BOOL Value/*[in]*/) = 0; // [214]
  virtual HRESULT STDMETHODCALLTYPE AddSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/) = 0; // [215]
  virtual HRESULT STDMETHODCALLTYPE RemoveSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/) = 0; // [216]
  virtual HRESULT STDMETHODCALLTYPE get_X25StylePxQty(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [217]
  virtual HRESULT STDMETHODCALLTYPE set_X25StylePxQty(VARIANT_BOOL Value/*[in]*/) = 0; // [217]
  virtual HRESULT STDMETHODCALLTYPE set_Stdout(VARIANT_BOOL Value/*[in]*/) = 0; // [218]
  virtual HRESULT STDMETHODCALLTYPE LogonProxy(BSTR ID/*[in]*/, BSTR Password/*[in]*/,
                                               BSTR Account/*[in]*/, BSTR Token1/*[in]*/,
                                               BSTR Token2/*[in]*/) = 0; // [219]
  virtual HRESULT STDMETHODCALLTYPE LockAE(BSTR AE/*[in]*/, VARIANT_BOOL IsLock/*[in]*/) = 0; // [220]
  virtual HRESULT STDMETHODCALLTYPE Connect2(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/,
                                             long TimeoutSec/*[in]*/) = 0; // [221]
  virtual HRESULT STDMETHODCALLTYPE URLEncode(BSTR URL/*[in]*/, BSTR* EncodeURL/*[out,retval]*/) = 0; // [222]
  virtual HRESULT STDMETHODCALLTYPE get_Version(BSTR* Value/*[out,retval]*/) = 0; // [223]
  virtual HRESULT STDMETHODCALLTYPE get_WhichAPI(Orderconnection_tlb::APIEnum* Value/*[out,retval]*/) = 0; // [224]
  virtual HRESULT STDMETHODCALLTYPE set_DetectAPI(VARIANT_BOOL Value/*[in]*/) = 0; // [225]
  virtual HRESULT STDMETHODCALLTYPE Create3(BSTR AppName/*[in]*/,
                                            Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                            BSTR* Message/*[out]*/,
                                            VARIANT_BOOL* Result/*[out,retval]*/) = 0; // [226]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  BSTR __fastcall get_ClearMemberID(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_ClearMemberID((BSTR*)&Value));
    return Value;
  }

  VARIANT_BOOL __fastcall get_IsAdministrator(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->get_IsAdministrator((VARIANT_BOOL*)&Value));
    return Value;
  }

  __int64 __fastcall GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                      Ordermessage_tlb::MessageTypeEnum Type/*[in]*/)
  {
    __int64 NID;
    OLECHECK(this->GenerateUniqueID(Market, Type, (__int64*)&NID));
    return NID;
  }

  BSTR __fastcall GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/)
  {
    BSTR BrokerID = 0;
    OLECHECK(this->GetBrokerID(Market, (BSTR*)&BrokerID));
    return BrokerID;
  }

  BSTR __fastcall get_BrokerID(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_BrokerID((BSTR*)&Value));
    return Value;
  }

  VARIANT_BOOL __fastcall get_UseNewFuturesSymbol(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->get_UseNewFuturesSymbol((VARIANT_BOOL*)&Value));
    return Value;
  }

  VARIANT_BOOL __fastcall get_EnablePandingNewAck(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->get_EnablePandingNewAck((VARIANT_BOOL*)&Value));
    return Value;
  }

  VARIANT_BOOL __fastcall get_X25StylePxQty(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->get_X25StylePxQty((VARIANT_BOOL*)&Value));
    return Value;
  }

  BSTR __fastcall URLEncode(BSTR URL/*[in]*/)
  {
    BSTR EncodeURL = 0;
    OLECHECK(this->URLEncode(URL, (BSTR*)&EncodeURL));
    return EncodeURL;
  }

  BSTR __fastcall get_Version(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_Version((BSTR*)&Value));
    return Value;
  }

  Orderconnection_tlb::APIEnum __fastcall get_WhichAPI(void)
  {
    Orderconnection_tlb::APIEnum Value;
    OLECHECK(this->get_WhichAPI((Orderconnection_tlb::APIEnum*)&Value));
    return Value;
  }

  VARIANT_BOOL __fastcall Create3(BSTR AppName/*[in]*/, Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                  BSTR* Message/*[out]*/)
  {
    VARIANT_BOOL Result;
    OLECHECK(this->Create3(AppName, UseAPI, Message, (VARIANT_BOOL*)&Result));
    return Result;
  }


  __property   BSTR            ClearMemberID = {read = get_ClearMemberID, write = set_ClearMemberID};
  __property   VARIANT_BOOL    IsAdministrator = {read = get_IsAdministrator};
  __property   BSTR            BrokerID = {read = get_BrokerID, write = set_BrokerID};
  __property   VARIANT_BOOL    UseNewFuturesSymbol = {read = get_UseNewFuturesSymbol, write = set_UseNewFuturesSymbol};
  __property   VARIANT_BOOL    SendFillZeroQty = {write = set_SendFillZeroQty};
  __property   VARIANT_BOOL    EnableFilledStatus = {write = set_EnableFilledStatus};
  __property   VARIANT_BOOL    EnablePandingNewAck = {read = get_EnablePandingNewAck, write = set_EnablePandingNewAck};
  __property   VARIANT_BOOL    X25StylePxQty = {read = get_X25StylePxQty, write = set_X25StylePxQty};
  __property   VARIANT_BOOL    Stdout = {write = set_Stdout};
  __property   BSTR            Version = {read = get_Version};
  __property   Orderconnection_tlb::APIEnum WhichAPI = {read = get_WhichAPI};
  __property   VARIANT_BOOL    DetectAPI = {write = set_DetectAPI};

#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

// *********************************************************************//
// Interface: ITaifexConnectionEvents
// Flags:     (0)
// GUID:      {9C278915-C60C-43F3-81C9-586D1AB00F03}
// *********************************************************************//
interface ITaifexConnectionEvents : public TDispWrapper<IDispatch>
{
  void __fastcall OnConnected()
  {
    _TDispID _dispid(/* OnConnected */ DISPID(0));
    OleProcedure(_dispid);
  }

  void __fastcall OnDisconnected()
  {
    _TDispID _dispid(/* OnDisconnected */ DISPID(1));
    OleProcedure(_dispid);
  }

  void __fastcall OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg/*[in]*/,
                                    Orderconnection_tlb::ExecDupEnum ExecPossDup/*[in]*/)
  {
    _TDispID _dispid(/* OnExecutionReport */ DISPID(3));
    TAutoArgs<2> _args;
    _args[1] = (LPDISPATCH)(Ordermessage_tlb::IExecutionReportMessage*)Msg /*[VT_USERDEFINED:1]*/;
    _args[2] = (int)ExecPossDup /*[VT_USERDEFINED:0]*/;
    OleProcedure(_dispid, _args);
  }

  void __fastcall OnRecoverFinished(long Count/*[in]*/)
  {
    _TDispID _dispid(/* OnRecoverFinished */ DISPID(4));
    TAutoArgs<1> _args;
    _args[1] = Count /*[VT_I4:0]*/;
    OleProcedure(_dispid, _args);
  }

  HRESULT __fastcall OnNews(Ordermessage_tlb::INewsMessage* News/*[in]*/)
  {
    _TDispID _dispid(/* OnNews */ DISPID(5));
    TAutoArgs<1> _args;
    _args[1] = (LPDISPATCH)(Ordermessage_tlb::INewsMessage*)News /*[VT_USERDEFINED:1]*/;
    return OleFunction(_dispid, _args);
  }

  HRESULT __fastcall OnLogonReply(BSTR Message/*[in]*/,
                                  Orderconnection_tlb::LogonResultEnum Result/*[in]*/,
                                  long ConnectionID/*[in]*/)
  {
    _TDispID _dispid(/* OnLogonReply */ DISPID(201));
    TAutoArgs<3> _args;
    _args[1] = Message /*[VT_BSTR:0]*/;
    _args[2] = (int)Result /*[VT_USERDEFINED:0]*/;
    _args[3] = ConnectionID /*[VT_I4:0]*/;
    return OleFunction(_dispid, _args);
  }


};
#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMITaifexConnection
// Interface: ITaifexConnection
// *********************************************************************//
template <class T /* ITaifexConnection */ >
class TCOMITaifexConnectionT : public TComInterface<ITaifexConnection>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMITaifexConnectionT() {}
  TCOMITaifexConnectionT(ITaifexConnection *intf, bool addRef = false) : TComInterface<ITaifexConnection>(intf, addRef) {}
  TCOMITaifexConnectionT(const TCOMITaifexConnectionT& src) : TComInterface<ITaifexConnection>(src) {}
  TCOMITaifexConnectionT& operator=(const TCOMITaifexConnectionT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall Create(BSTR AppName/*[in]*/);
  HRESULT         __fastcall Destroy(void);
  HRESULT         __fastcall Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/);
  HRESULT         __fastcall Disconnect(void);
  HRESULT         __fastcall Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                   Orderconnection_tlb::ConnectionTypeEnum Type/*[in]*/);
  HRESULT         __fastcall NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/);
  HRESULT         __fastcall QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/);
  HRESULT         __fastcall QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/);
  HRESULT         __fastcall Recover(BSTR BeginTime/*[in]*/,
                                     Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                     Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/);
  HRESULT         __fastcall get_ClearMemberID(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_ClearMemberID(void);
  HRESULT         __fastcall set_ClearMemberID(BSTR Value/*[in]*/);
  HRESULT         __fastcall get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_IsAdministrator(void);
  HRESULT         __fastcall SetLanguage(Orderconnection_tlb::MessageLanguageEnum Lang/*[in]*/);
  HRESULT         __fastcall GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                              Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                              __int64* NID/*[out,retval]*/);
  __int64         __fastcall GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                              Ordermessage_tlb::MessageTypeEnum Type/*[in]*/);
  HRESULT         __fastcall GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                         BSTR* BrokerID/*[out,retval]*/);
  BSTR            __fastcall GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/);
  HRESULT         __fastcall SetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                         BSTR Value/*[in]*/);
  HRESULT         __fastcall Create2(BSTR AppName/*[in]*/);
  HRESULT         __fastcall get_BrokerID(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_BrokerID(void);
  HRESULT         __fastcall set_BrokerID(BSTR Value/*[in]*/);
  HRESULT         __fastcall get_UseNewFuturesSymbol(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_UseNewFuturesSymbol(void);
  HRESULT         __fastcall set_UseNewFuturesSymbol(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall SetDebugLog(BSTR FileName/*[in]*/);
  HRESULT         __fastcall OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/);
  HRESULT         __fastcall Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                      Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                      Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/);
  HRESULT         __fastcall set_SendFillZeroQty(VARIANT_BOOL Param1/*[in]*/);
  HRESULT         __fastcall NewsRequest(Ordermessage_tlb::INewsMessage* NewsReq/*[in]*/);
  HRESULT         __fastcall LockThisAE(VARIANT_BOOL Locked/*[in]*/);
  HRESULT         __fastcall set_EnableFilledStatus(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall get_EnablePandingNewAck(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_EnablePandingNewAck(void);
  HRESULT         __fastcall set_EnablePandingNewAck(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall AddSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/);
  HRESULT         __fastcall RemoveSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/);
  HRESULT         __fastcall get_X25StylePxQty(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_X25StylePxQty(void);
  HRESULT         __fastcall set_X25StylePxQty(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall set_Stdout(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall LogonProxy(BSTR ID/*[in]*/, BSTR Password/*[in]*/, BSTR Account/*[in]*/,
                                        BSTR Token1/*[in]*/, BSTR Token2/*[in]*/);
  HRESULT         __fastcall LockAE(BSTR AE/*[in]*/, VARIANT_BOOL IsLock/*[in]*/);
  HRESULT         __fastcall Connect2(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/,
                                      long TimeoutSec/*[in]*/);
  HRESULT         __fastcall URLEncode(BSTR URL/*[in]*/, BSTR* EncodeURL/*[out,retval]*/);
  BSTR            __fastcall URLEncode(BSTR URL/*[in]*/);
  HRESULT         __fastcall get_Version(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_Version(void);
  HRESULT         __fastcall get_WhichAPI(Orderconnection_tlb::APIEnum* Value/*[out,retval]*/);
  Orderconnection_tlb::APIEnum __fastcall get_WhichAPI(void);
  HRESULT         __fastcall set_DetectAPI(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall Create3(BSTR AppName/*[in]*/,
                                     Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                     BSTR* Message/*[out]*/, VARIANT_BOOL* Result/*[out,retval]*/);
  VARIANT_BOOL    __fastcall Create3(BSTR AppName/*[in]*/,
                                     Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                     BSTR* Message/*[out]*/);

  __property   BSTR            ClearMemberID = {read = get_ClearMemberID, write = set_ClearMemberID};
  __property   VARIANT_BOOL    IsAdministrator = {read = get_IsAdministrator};
  __property   BSTR            BrokerID = {read = get_BrokerID, write = set_BrokerID};
  __property   VARIANT_BOOL    UseNewFuturesSymbol = {read = get_UseNewFuturesSymbol, write = set_UseNewFuturesSymbol};
  __property   VARIANT_BOOL    SendFillZeroQty = {write = set_SendFillZeroQty};
  __property   VARIANT_BOOL    EnableFilledStatus = {write = set_EnableFilledStatus};
  __property   VARIANT_BOOL    EnablePandingNewAck = {read = get_EnablePandingNewAck, write = set_EnablePandingNewAck};
  __property   VARIANT_BOOL    X25StylePxQty = {read = get_X25StylePxQty, write = set_X25StylePxQty};
  __property   VARIANT_BOOL    Stdout = {write = set_Stdout};
  __property   BSTR            Version = {read = get_Version};
  __property   Orderconnection_tlb::APIEnum WhichAPI = {read = get_WhichAPI};
  __property   VARIANT_BOOL    DetectAPI = {write = set_DetectAPI};
};
typedef TCOMITaifexConnectionT<ITaifexConnection> TCOMITaifexConnection;

// *********************************************************************//
// DispIntf:  ITaifexConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {E491C857-AF5A-492B-BE8B-58A6BB54F7B4}
// *********************************************************************//
template<class T>
class ITaifexConnectionDispT : public TAutoDriver<ITaifexConnection>
{
public:
  ITaifexConnectionDispT(){}

  ITaifexConnectionDispT(ITaifexConnection *pintf)
  {
    TAutoDriver<ITaifexConnection>::Bind(pintf, false);
  }

  ITaifexConnectionDispT(ITaifexConnectionPtr pintf)
  {
    TAutoDriver<ITaifexConnection>::Bind(pintf, true);
  }

  ITaifexConnectionDispT& operator=(ITaifexConnection *pintf)
  {
    TAutoDriver<ITaifexConnection>::Bind(pintf, false);
    return *this;
  }

  ITaifexConnectionDispT& operator=(ITaifexConnectionPtr pintf)
  {
    TAutoDriver<ITaifexConnection>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_TaifexConnection));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_TaifexConnection);
  }

  HRESULT         __fastcall Create(BSTR AppName/*[in]*/);
  HRESULT         __fastcall Destroy();
  HRESULT         __fastcall Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/);
  HRESULT         __fastcall Disconnect();
  HRESULT         __fastcall Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                   Orderconnection_tlb::ConnectionTypeEnum Type/*[in]*/);
  HRESULT         __fastcall NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/);
  HRESULT         __fastcall Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/);
  HRESULT         __fastcall QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/);
  HRESULT         __fastcall QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/);
  HRESULT         __fastcall Recover(BSTR BeginTime/*[in]*/,
                                     Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                     Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/);
  HRESULT         __fastcall get_ClearMemberID(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_ClearMemberID(void);
  HRESULT         __fastcall set_ClearMemberID(BSTR Value/*[in]*/);
  HRESULT         __fastcall get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_IsAdministrator(void);
  HRESULT         __fastcall SetLanguage(Orderconnection_tlb::MessageLanguageEnum Lang/*[in]*/);
  HRESULT         __fastcall GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                              Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                              __int64* NID/*[out,retval]*/);
  __int64         __fastcall GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                              Ordermessage_tlb::MessageTypeEnum Type/*[in]*/);
  HRESULT         __fastcall GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                         BSTR* BrokerID/*[out,retval]*/);
  BSTR            __fastcall GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/);
  HRESULT         __fastcall SetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                         BSTR Value/*[in]*/);
  HRESULT         __fastcall Create2(BSTR AppName/*[in]*/);
  HRESULT         __fastcall get_BrokerID(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_BrokerID(void);
  HRESULT         __fastcall set_BrokerID(BSTR Value/*[in]*/);
  HRESULT         __fastcall get_UseNewFuturesSymbol(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_UseNewFuturesSymbol(void);
  HRESULT         __fastcall set_UseNewFuturesSymbol(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall SetDebugLog(BSTR FileName/*[in]*/);
  HRESULT         __fastcall OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/);
  HRESULT         __fastcall Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                      Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                      Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/);
  HRESULT         __fastcall set_SendFillZeroQty(VARIANT_BOOL Param1/*[in]*/);
  HRESULT         __fastcall NewsRequest(Ordermessage_tlb::INewsMessage* NewsReq/*[in]*/);
  HRESULT         __fastcall LockThisAE(VARIANT_BOOL Locked/*[in]*/);
  HRESULT         __fastcall set_EnableFilledStatus(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall get_EnablePandingNewAck(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_EnablePandingNewAck(void);
  HRESULT         __fastcall set_EnablePandingNewAck(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall AddSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/);
  HRESULT         __fastcall RemoveSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/);
  HRESULT         __fastcall get_X25StylePxQty(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_X25StylePxQty(void);
  HRESULT         __fastcall set_X25StylePxQty(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall set_Stdout(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall LogonProxy(BSTR ID/*[in]*/, BSTR Password/*[in]*/, BSTR Account/*[in]*/
                                        , BSTR Token1/*[in]*/, BSTR Token2/*[in]*/);
  HRESULT         __fastcall LockAE(BSTR AE/*[in]*/, VARIANT_BOOL IsLock/*[in]*/);
  HRESULT         __fastcall Connect2(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/,
                                      long TimeoutSec/*[in]*/);
  HRESULT         __fastcall URLEncode(BSTR URL/*[in]*/, BSTR* EncodeURL/*[out,retval]*/);
  BSTR            __fastcall URLEncode(BSTR URL/*[in]*/);
  HRESULT         __fastcall get_Version(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_Version(void);
  HRESULT         __fastcall get_WhichAPI(Orderconnection_tlb::APIEnum* Value/*[out,retval]*/);
  Orderconnection_tlb::APIEnum __fastcall get_WhichAPI(void);
  HRESULT         __fastcall set_DetectAPI(VARIANT_BOOL Value/*[in]*/);
  HRESULT         __fastcall Create3(BSTR AppName/*[in]*/,
                                     Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                     BSTR* Message/*[out]*/, VARIANT_BOOL* Result/*[out,retval]*/);
  VARIANT_BOOL    __fastcall Create3(BSTR AppName/*[in]*/,
                                     Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                     BSTR* Message/*[out]*/);

  __property   BSTR            ClearMemberID = {read = get_ClearMemberID, write = set_ClearMemberID};
  __property   VARIANT_BOOL    IsAdministrator = {read = get_IsAdministrator};
  __property   BSTR            BrokerID = {read = get_BrokerID, write = set_BrokerID};
  __property   VARIANT_BOOL    UseNewFuturesSymbol = {read = get_UseNewFuturesSymbol, write = set_UseNewFuturesSymbol};
  __property   VARIANT_BOOL    SendFillZeroQty = {write = set_SendFillZeroQty};
  __property   VARIANT_BOOL    EnableFilledStatus = {write = set_EnableFilledStatus};
  __property   VARIANT_BOOL    EnablePandingNewAck = {read = get_EnablePandingNewAck, write = set_EnablePandingNewAck};
  __property   VARIANT_BOOL    X25StylePxQty = {read = get_X25StylePxQty, write = set_X25StylePxQty};
  __property   VARIANT_BOOL    Stdout = {write = set_Stdout};
  __property   BSTR            Version = {read = get_Version};
  __property   Orderconnection_tlb::APIEnum WhichAPI = {read = get_WhichAPI};
  __property   VARIANT_BOOL    DetectAPI = {write = set_DetectAPI};
};
typedef ITaifexConnectionDispT<ITaifexConnection> ITaifexConnectionDisp;

// *********************************************************************//
// DispIntf:  ITaifexConnectionEvents
// Flags:     (0)
// GUID:      {9C278915-C60C-43F3-81C9-586D1AB00F03}
// *********************************************************************//
template <class T>
class ITaifexConnectionEventsDispT : public TAutoDriver<ITaifexConnectionEvents>
{
public:
  ITaifexConnectionEventsDispT(){}

  void Attach(LPUNKNOWN punk)
  { m_Dispatch = static_cast<T*>(punk); }

  void            __fastcall OnConnected();
  void            __fastcall OnDisconnected();
  void            __fastcall OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg/*[in]*/
                                               ,
                                               Orderconnection_tlb::ExecDupEnum ExecPossDup/*[in]*/);
  void            __fastcall OnRecoverFinished(long Count/*[in]*/);
  HRESULT         __fastcall OnNews(Ordermessage_tlb::INewsMessage* News/*[in]*/);
  HRESULT         __fastcall OnLogonReply(BSTR Message/*[in]*/,
                                          Orderconnection_tlb::LogonResultEnum Result/*[in]*/,
                                          long ConnectionID/*[in]*/);

};
typedef ITaifexConnectionEventsDispT<ITaifexConnectionEvents> ITaifexConnectionEventsDisp;

// *********************************************************************//
// SmartIntf: TCOMITaifexConnection
// Interface: ITaifexConnection
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Create(BSTR AppName/*[in]*/)
{
  return (*this)->Create(AppName);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Destroy(void)
{
  return (*this)->Destroy();
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/)
{
  return (*this)->Connect(RemoteIP, RemotePort);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Disconnect(void)
{
  return (*this)->Disconnect();
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                 Orderconnection_tlb::ConnectionTypeEnum Type/*[in]*/)
{
  return (*this)->Logon(ID, PASSWD, ACCOUNT, Type);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/)
{
  return (*this)->NewOrder(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/)
{
  return (*this)->ReplaceOrder(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/)
{
  return (*this)->CancelOrder(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/)
{
  return (*this)->Quote(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/)
{
  return (*this)->QuoteCancel(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/)
{
  return (*this)->QuoteRequest(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Recover(BSTR BeginTime/*[in]*/,
                                   Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                   Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/)
{
  return (*this)->Recover(BeginTime, Type, Market);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::get_ClearMemberID(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_ClearMemberID(Value);
}

template <class T> BSTR __fastcall
TCOMITaifexConnectionT<T>::get_ClearMemberID(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_ClearMemberID((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_ClearMemberID(BSTR Value/*[in]*/)
{
  return (*this)->set_ClearMemberID(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->get_IsAdministrator(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMITaifexConnectionT<T>::get_IsAdministrator(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->get_IsAdministrator((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::SetLanguage(Orderconnection_tlb::MessageLanguageEnum Lang/*[in]*/)
{
  return (*this)->SetLanguage(Lang);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                            Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                            __int64* NID/*[out,retval]*/)
{
  return (*this)->GenerateUniqueID(Market, Type, NID);
}

template <class T> __int64 __fastcall
TCOMITaifexConnectionT<T>::GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                            Ordermessage_tlb::MessageTypeEnum Type/*[in]*/)
{
  __int64 NID;
  OLECHECK(this->GenerateUniqueID(Market/*[in]*/, Type/*[in]*/, (__int64*)&NID));
  return NID;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                       BSTR* BrokerID/*[out,retval]*/)
{
  return (*this)->GetBrokerID(Market, BrokerID);
}

template <class T> BSTR __fastcall
TCOMITaifexConnectionT<T>::GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/)
{
  BSTR BrokerID = 0;
  OLECHECK(this->GetBrokerID(Market/*[in]*/, (BSTR*)&BrokerID));
  return BrokerID;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::SetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                       BSTR Value/*[in]*/)
{
  return (*this)->SetBrokerID(Market, Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Create2(BSTR AppName/*[in]*/)
{
  return (*this)->Create2(AppName);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::get_BrokerID(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_BrokerID(Value);
}

template <class T> BSTR __fastcall
TCOMITaifexConnectionT<T>::get_BrokerID(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_BrokerID((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_BrokerID(BSTR Value/*[in]*/)
{
  return (*this)->set_BrokerID(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::get_UseNewFuturesSymbol(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->get_UseNewFuturesSymbol(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMITaifexConnectionT<T>::get_UseNewFuturesSymbol(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->get_UseNewFuturesSymbol((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_UseNewFuturesSymbol(VARIANT_BOOL Value/*[in]*/)
{
  return (*this)->set_UseNewFuturesSymbol(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::SetDebugLog(BSTR FileName/*[in]*/)
{
  return (*this)->SetDebugLog(FileName);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/)
{
  return (*this)->OrderStatusRequest(Msg);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                    Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                    Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/)
{
  return (*this)->Recover2(BeginTime, EndTime, Type, Market);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_SendFillZeroQty(VARIANT_BOOL Param1/*[in]*/)
{
  return (*this)->set_SendFillZeroQty(Param1);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::NewsRequest(Ordermessage_tlb::INewsMessage* NewsReq/*[in]*/)
{
  return (*this)->NewsRequest(NewsReq);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::LockThisAE(VARIANT_BOOL Locked/*[in]*/)
{
  return (*this)->LockThisAE(Locked);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_EnableFilledStatus(VARIANT_BOOL Value/*[in]*/)
{
  return (*this)->set_EnableFilledStatus(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::get_EnablePandingNewAck(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->get_EnablePandingNewAck(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMITaifexConnectionT<T>::get_EnablePandingNewAck(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->get_EnablePandingNewAck((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_EnablePandingNewAck(VARIANT_BOOL Value/*[in]*/)
{
  return (*this)->set_EnablePandingNewAck(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::AddSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/)
{
  return (*this)->AddSellSide(SellSide);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::RemoveSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/)
{
  return (*this)->RemoveSellSide(SellSide);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::get_X25StylePxQty(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->get_X25StylePxQty(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMITaifexConnectionT<T>::get_X25StylePxQty(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->get_X25StylePxQty((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_X25StylePxQty(VARIANT_BOOL Value/*[in]*/)
{
  return (*this)->set_X25StylePxQty(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_Stdout(VARIANT_BOOL Value/*[in]*/)
{
  return (*this)->set_Stdout(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::LogonProxy(BSTR ID/*[in]*/, BSTR Password/*[in]*/, BSTR Account/*[in]*/,
                                      BSTR Token1/*[in]*/, BSTR Token2/*[in]*/)
{
  return (*this)->LogonProxy(ID, Password, Account, Token1, Token2);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::LockAE(BSTR AE/*[in]*/, VARIANT_BOOL IsLock/*[in]*/)
{
  return (*this)->LockAE(AE, IsLock);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Connect2(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/,
                                    long TimeoutSec/*[in]*/)
{
  return (*this)->Connect2(RemoteIP, RemotePort, TimeoutSec);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::URLEncode(BSTR URL/*[in]*/, BSTR* EncodeURL/*[out,retval]*/)
{
  return (*this)->URLEncode(URL, EncodeURL);
}

template <class T> BSTR __fastcall
TCOMITaifexConnectionT<T>::URLEncode(BSTR URL/*[in]*/)
{
  BSTR EncodeURL = 0;
  OLECHECK(this->URLEncode(URL/*[in]*/, (BSTR*)&EncodeURL));
  return EncodeURL;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::get_Version(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_Version(Value);
}

template <class T> BSTR __fastcall
TCOMITaifexConnectionT<T>::get_Version(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_Version((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::get_WhichAPI(Orderconnection_tlb::APIEnum* Value/*[out,retval]*/)
{
  return (*this)->get_WhichAPI(Value);
}

template <class T> Orderconnection_tlb::APIEnum __fastcall
TCOMITaifexConnectionT<T>::get_WhichAPI(void)
{
  Orderconnection_tlb::APIEnum Value;
  OLECHECK(this->get_WhichAPI((Orderconnection_tlb::APIEnum*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::set_DetectAPI(VARIANT_BOOL Value/*[in]*/)
{
  return (*this)->set_DetectAPI(Value);
}

template <class T> HRESULT __fastcall
TCOMITaifexConnectionT<T>::Create3(BSTR AppName/*[in]*/, Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                   BSTR* Message/*[out]*/, VARIANT_BOOL* Result/*[out,retval]*/)
{
  return (*this)->Create3(AppName, UseAPI, Message, Result);
}

template <class T> VARIANT_BOOL __fastcall
TCOMITaifexConnectionT<T>::Create3(BSTR AppName/*[in]*/, Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                   BSTR* Message/*[out]*/)
{
  VARIANT_BOOL Result;
  OLECHECK(this->Create3(AppName/*[in]*/, UseAPI/*[in]*/, Message/*[out]*/, (VARIANT_BOOL*)&Result));
  return Result;
}

// *********************************************************************//
// DispIntf:  ITaifexConnection
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {E491C857-AF5A-492B-BE8B-58A6BB54F7B4}
// *********************************************************************//
template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Create(BSTR AppName/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Create"), DISPID(1));
  TAutoArgs<1> _args;
  _args[1] = AppName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Destroy()
{
  _TDispID _dispid(*this, OLETEXT("Destroy"), DISPID(2));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Connect(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Connect"), DISPID(3));
  TAutoArgs<2> _args;
  _args[1] = RemoteIP /*[VT_BSTR:0]*/;
  _args[2] = RemotePort /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Disconnect()
{
  _TDispID _dispid(*this, OLETEXT("Disconnect"), DISPID(4));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Logon(BSTR ID/*[in]*/, BSTR PASSWD/*[in]*/, BSTR ACCOUNT/*[in]*/,
                                 Orderconnection_tlb::ConnectionTypeEnum Type/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Logon"), DISPID(5));
  TAutoArgs<4> _args;
  _args[1] = ID /*[VT_BSTR:0]*/;
  _args[2] = PASSWD /*[VT_BSTR:0]*/;
  _args[3] = ACCOUNT /*[VT_BSTR:0]*/;
  _args[4] = (int)Type /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::NewOrder(Ordermessage_tlb::INewOrderMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("NewOrder"), DISPID(6));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::INewOrderMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::ReplaceOrder(Ordermessage_tlb::IReplaceOrderMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("ReplaceOrder"), DISPID(7));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IReplaceOrderMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::CancelOrder(Ordermessage_tlb::ICancelOrderMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("CancelOrder"), DISPID(8));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::ICancelOrderMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Quote(Ordermessage_tlb::IQuoteMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Quote"), DISPID(9));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IQuoteMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::QuoteCancel(Ordermessage_tlb::IQuoteCancelMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("QuoteCancel"), DISPID(10));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IQuoteCancelMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::QuoteRequest(Ordermessage_tlb::IQuoteRequestMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("QuoteRequest"), DISPID(11));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IQuoteRequestMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Recover(BSTR BeginTime/*[in]*/,
                                   Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                   Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Recover"), DISPID(12));
  TAutoArgs<3> _args;
  _args[1] = BeginTime /*[VT_BSTR:0]*/;
  _args[2] = (int)Type /*[VT_USERDEFINED:0]*/;
  _args[3] = (int)Market /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::get_ClearMemberID(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("ClearMemberID"), DISPID(14));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
ITaifexConnectionDispT<T>::get_ClearMemberID(void)
{
  BSTR Value;
  this->get_ClearMemberID((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_ClearMemberID(BSTR Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("ClearMemberID"), DISPID(14));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BSTR:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::get_IsAdministrator(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("IsAdministrator"), DISPID(15));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
ITaifexConnectionDispT<T>::get_IsAdministrator(void)
{
  VARIANT_BOOL Value;
  this->get_IsAdministrator((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::SetLanguage(Orderconnection_tlb::MessageLanguageEnum Lang/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetLanguage"), DISPID(16));
  TAutoArgs<1> _args;
  _args[1] = (int)Lang /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                            Ordermessage_tlb::MessageTypeEnum Type/*[in]*/,
                                            __int64* NID/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GenerateUniqueID"), DISPID(201));
  TAutoArgs<2> _args;
  _args[1] = (int)Market /*[VT_USERDEFINED:0]*/;
  _args[2] = (int)Type /*[VT_USERDEFINED:0]*/;
  return OutRetValSetterPtr(NID /*[VT_I8:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> __int64 __fastcall
ITaifexConnectionDispT<T>::GenerateUniqueID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                            Ordermessage_tlb::MessageTypeEnum Type/*[in]*/)
{
  __int64 NID;
  this->GenerateUniqueID(Market, Type, (__int64*)&NID);
  return NID;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                       BSTR* BrokerID/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetBrokerID"), DISPID(202));
  TAutoArgs<1> _args;
  _args[1] = (int)Market /*[VT_USERDEFINED:0]*/;
  return OutRetValSetterPtr(BrokerID /*[VT_BSTR:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> BSTR __fastcall
ITaifexConnectionDispT<T>::GetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/)
{
  BSTR BrokerID;
  this->GetBrokerID(Market, (BSTR*)&BrokerID);
  return BrokerID;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::SetBrokerID(Ordermessage_tlb::MarketEnum Market/*[in]*/,
                                       BSTR Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetBrokerID"), DISPID(203));
  TAutoArgs<2> _args;
  _args[1] = (int)Market /*[VT_USERDEFINED:0]*/;
  _args[2] = Value /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Create2(BSTR AppName/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Create2"), DISPID(204));
  TAutoArgs<1> _args;
  _args[1] = AppName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::get_BrokerID(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("BrokerID"), DISPID(205));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
ITaifexConnectionDispT<T>::get_BrokerID(void)
{
  BSTR Value;
  this->get_BrokerID((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_BrokerID(BSTR Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("BrokerID"), DISPID(205));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BSTR:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::get_UseNewFuturesSymbol(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("UseNewFuturesSymbol"), DISPID(206));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
ITaifexConnectionDispT<T>::get_UseNewFuturesSymbol(void)
{
  VARIANT_BOOL Value;
  this->get_UseNewFuturesSymbol((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_UseNewFuturesSymbol(VARIANT_BOOL Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("UseNewFuturesSymbol"), DISPID(206));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BOOL:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::SetDebugLog(BSTR FileName/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetDebugLog"), DISPID(207));
  TAutoArgs<1> _args;
  _args[1] = FileName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::OrderStatusRequest(Ordermessage_tlb::IOrderStatusRequestMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("OrderStatusRequest"), DISPID(208));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IOrderStatusRequestMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Recover2(BSTR BeginTime/*[in]*/, BSTR EndTime/*[in]*/,
                                    Orderconnection_tlb::RecoverTypeEnum Type/*[in]*/,
                                    Orderconnection_tlb::RecoverMarketEnum Market/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Recover2"), DISPID(209));
  TAutoArgs<4> _args;
  _args[1] = BeginTime /*[VT_BSTR:0]*/;
  _args[2] = EndTime /*[VT_BSTR:0]*/;
  _args[3] = (int)Type /*[VT_USERDEFINED:0]*/;
  _args[4] = (int)Market /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_SendFillZeroQty(VARIANT_BOOL Param1/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SendFillZeroQty"), DISPID(210));
  TAutoArgs<1> _args;
  _args[1] = Param1 /*[VT_BOOL:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::NewsRequest(Ordermessage_tlb::INewsMessage* NewsReq/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("NewsRequest"), DISPID(211));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::INewsMessage*)NewsReq /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::LockThisAE(VARIANT_BOOL Locked/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("LockThisAE"), DISPID(212));
  TAutoArgs<1> _args;
  _args[1] = Locked /*[VT_BOOL:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_EnableFilledStatus(VARIANT_BOOL Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("EnableFilledStatus"), DISPID(213));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BOOL:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::get_EnablePandingNewAck(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("EnablePandingNewAck"), DISPID(214));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
ITaifexConnectionDispT<T>::get_EnablePandingNewAck(void)
{
  VARIANT_BOOL Value;
  this->get_EnablePandingNewAck((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_EnablePandingNewAck(VARIANT_BOOL Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("EnablePandingNewAck"), DISPID(214));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BOOL:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::AddSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("AddSellSide"), DISPID(215));
  TAutoArgs<1> _args;
  _args[1] = (int)SellSide /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::RemoveSellSide(Orderconnection_tlb::SellSideTypeEnum SellSide/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("RemoveSellSide"), DISPID(216));
  TAutoArgs<1> _args;
  _args[1] = (int)SellSide /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::get_X25StylePxQty(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("X25StylePxQty"), DISPID(217));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
ITaifexConnectionDispT<T>::get_X25StylePxQty(void)
{
  VARIANT_BOOL Value;
  this->get_X25StylePxQty((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_X25StylePxQty(VARIANT_BOOL Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("X25StylePxQty"), DISPID(217));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BOOL:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_Stdout(VARIANT_BOOL Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Stdout"), DISPID(218));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BOOL:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::LogonProxy(BSTR ID/*[in]*/, BSTR Password/*[in]*/, BSTR Account/*[in]*/,
                                      BSTR Token1/*[in]*/, BSTR Token2/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("LogonProxy"), DISPID(219));
  TAutoArgs<5> _args;
  _args[1] = ID /*[VT_BSTR:0]*/;
  _args[2] = Password /*[VT_BSTR:0]*/;
  _args[3] = Account /*[VT_BSTR:0]*/;
  _args[4] = Token1 /*[VT_BSTR:0]*/;
  _args[5] = Token2 /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::LockAE(BSTR AE/*[in]*/, VARIANT_BOOL IsLock/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("LockAE"), DISPID(220));
  TAutoArgs<2> _args;
  _args[1] = AE /*[VT_BSTR:0]*/;
  _args[2] = IsLock /*[VT_BOOL:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Connect2(BSTR RemoteIP/*[in]*/, long RemotePort/*[in]*/,
                                    long TimeoutSec/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Connect2"), DISPID(221));
  TAutoArgs<3> _args;
  _args[1] = RemoteIP /*[VT_BSTR:0]*/;
  _args[2] = RemotePort /*[VT_I4:0]*/;
  _args[3] = TimeoutSec /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::URLEncode(BSTR URL/*[in]*/, BSTR* EncodeURL/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("URLEncode"), DISPID(222));
  TAutoArgs<1> _args;
  _args[1] = URL /*[VT_BSTR:0]*/;
  return OutRetValSetterPtr(EncodeURL /*[VT_BSTR:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> BSTR __fastcall
ITaifexConnectionDispT<T>::URLEncode(BSTR URL/*[in]*/)
{
  BSTR EncodeURL;
  this->URLEncode(URL, (BSTR*)&EncodeURL);
  return EncodeURL;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::get_Version(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Version"), DISPID(223));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
ITaifexConnectionDispT<T>::get_Version(void)
{
  BSTR Value;
  this->get_Version((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::get_WhichAPI(Orderconnection_tlb::APIEnum* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("WhichAPI"), DISPID(224));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr((int*)Value /*[VT_USERDEFINED:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> Orderconnection_tlb::APIEnum __fastcall
ITaifexConnectionDispT<T>::get_WhichAPI(void)
{
  Orderconnection_tlb::APIEnum Value;
  this->get_WhichAPI((Orderconnection_tlb::APIEnum*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::set_DetectAPI(VARIANT_BOOL Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("DetectAPI"), DISPID(225));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BOOL:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionDispT<T>::Create3(BSTR AppName/*[in]*/, Orderconnection_tlb::APIEnum UseAPI/*[in]*/
                                   , BSTR* Message/*[out]*/, VARIANT_BOOL* Result/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Create3"), DISPID(226));
  TAutoArgs<3> _args;
  _args[1] = AppName /*[VT_BSTR:0]*/;
  _args[2] = (int)UseAPI /*[VT_USERDEFINED:0]*/;
  _args[3] = Message /*[VT_BSTR:1]*/;
  return OutRetValSetterPtr(Result /*[VT_BOOL:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
ITaifexConnectionDispT<T>::Create3(BSTR AppName/*[in]*/, Orderconnection_tlb::APIEnum UseAPI/*[in]*/,
                                   BSTR* Message/*[out]*/)
{
  VARIANT_BOOL Result;
  this->Create3(AppName, UseAPI, Message, (VARIANT_BOOL*)&Result);
  return Result;
}

// *********************************************************************//
// DispIntf:  ITaifexConnectionEvents
// Flags:     (0)
// GUID:      {9C278915-C60C-43F3-81C9-586D1AB00F03}
// *********************************************************************//
template <class T> void __fastcall
ITaifexConnectionEventsDispT<T>::OnConnected()
{
  _TDispID _dispid(/* OnConnected */ DISPID(0));
  OleProcedure(_dispid);
}

template <class T> void __fastcall
ITaifexConnectionEventsDispT<T>::OnDisconnected()
{
  _TDispID _dispid(/* OnDisconnected */ DISPID(1));
  OleProcedure(_dispid);
}

template <class T> void __fastcall
ITaifexConnectionEventsDispT<T>::OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg/*[in]*/
                                                   ,
                                                   Orderconnection_tlb::ExecDupEnum ExecPossDup/*[in]*/)
{
  _TDispID _dispid(/* OnExecutionReport */ DISPID(3));
  TAutoArgs<2> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::IExecutionReportMessage*)Msg /*[VT_USERDEFINED:1]*/;
  _args[2] = (int)ExecPossDup /*[VT_USERDEFINED:0]*/;
  OleProcedure(_dispid, _args);
}

template <class T> void __fastcall
ITaifexConnectionEventsDispT<T>::OnRecoverFinished(long Count/*[in]*/)
{
  _TDispID _dispid(/* OnRecoverFinished */ DISPID(4));
  TAutoArgs<1> _args;
  _args[1] = Count /*[VT_I4:0]*/;
  OleProcedure(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionEventsDispT<T>::OnNews(Ordermessage_tlb::INewsMessage* News/*[in]*/)
{
  _TDispID _dispid(/* OnNews */ DISPID(5));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Ordermessage_tlb::INewsMessage*)News /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITaifexConnectionEventsDispT<T>::OnLogonReply(BSTR Message/*[in]*/,
                                              Orderconnection_tlb::LogonResultEnum Result/*[in]*/,
                                              long ConnectionID/*[in]*/)
{
  _TDispID _dispid(/* OnLogonReply */ DISPID(201));
  TAutoArgs<3> _args;
  _args[1] = Message /*[VT_BSTR:0]*/;
  _args[2] = (int)Result /*[VT_USERDEFINED:0]*/;
  _args[3] = ConnectionID /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that
// provide static Create() and CreateRemote(LPWSTR machineName) methods
// for creating an instance of an exposed object. These functions can
// be used by client wishing to automate CoClasses exposed by this
// typelibrary.
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : TaifexConnection
// Interface: TCOMITaifexConnection
// *********************************************************************//
typedef TCoClassCreatorT<TCOMITaifexConnection, ITaifexConnection, &CLSID_TaifexConnection, &IID_ITaifexConnection> CoTaifexConnection;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


#if !defined(__TLB_NO_EVENT_WRAPPERS) && defined(USING_ATLVCL)
// *********************************************************************//
// CONNECTIONPOINT/EVENT PROXY
// CoClass         : TaifexConnection
// Event Interface : ITaifexConnectionEvents
// *********************************************************************//
template <class T>
class TEvents_TaifexConnection : public IConnectionPointImpl<T,
                                                 &DIID_ITaifexConnectionEvents,
#if !defined(_TLB_DYNAMIC_CONNECTIONPOINT_ARRAY)
                                                 CComUnkArray<CONNECTIONPOINT_ARRAY_SIZE> >
#else
                                                 CComDynamicArray>
#endif
{
public:
  void            Fire_OnConnected(void);
  void            Fire_OnDisconnected(void);
  void            Fire_OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg,
                                         Orderconnection_tlb::ExecDupEnum ExecPossDup);
  void            Fire_OnRecoverFinished(long Count);
  HRESULT         Fire_OnNews(Ordermessage_tlb::INewsMessage* News);
  HRESULT         Fire_OnLogonReply(BSTR Message, Orderconnection_tlb::LogonResultEnum Result,
                                    long ConnectionID);
protected:
  ITaifexConnectionEventsDisp m_EventIntfObj;
};

template <class T> void
TEvents_TaifexConnection<T>::Fire_OnConnected(void)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnConnected();
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_TaifexConnection<T>::Fire_OnDisconnected(void)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnDisconnected();
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_TaifexConnection<T>::Fire_OnExecutionReport(Ordermessage_tlb::IExecutionReportMessage* Msg,
                                                    Orderconnection_tlb::ExecDupEnum ExecPossDup)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnExecutionReport(Msg, ExecPossDup);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> void
TEvents_TaifexConnection<T>::Fire_OnRecoverFinished(long Count)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnRecoverFinished(Count);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
}

template <class T> HRESULT
TEvents_TaifexConnection<T>::Fire_OnNews(Ordermessage_tlb::INewsMessage* News)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnNews(News);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

template <class T> HRESULT
TEvents_TaifexConnection<T>::Fire_OnLogonReply(BSTR Message,
                                               Orderconnection_tlb::LogonResultEnum Result,
                                               long ConnectionID)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnLogonReply(Message, Result, ConnectionID);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

#endif  //   __TLB_NO_EVENT_WRAPPERS

};     // namespace Orderconnection_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Orderconnection_tlb;
#endif

#pragma option pop

#endif // OrderConnection_TLBH

