#include "MultilegSymbol.h"

//------------------------------------------------------------------------------------------------------------------------
// class BO_SymbolDeCompose
//------------------------------------------------------------------------------------------------------------------------
//
//  File: ../cfg/StrikePxDigi.ini 
//  Generated by SpeedyTMP ,each time download P08  from TAIFEX
//
//------------------------------------------------------------------------------------------------------------------------
UFC::UiniFile BO_SymbolDeCompose::StrikePxTable( "../cfg/StrikePxDigit.ini", TRUE );
//------------------------------------------------------------------------------------------------------------------------
BO_SymbolDeCompose::BO_SymbolDeCompose()
:FIsFLEX( FALSE )
{
    Initialize();
}
//------------------------------------------------------------------------------------------------------------------------
BO_SymbolDeCompose::BO_SymbolDeCompose( UFC::AnsiString Symbol, char BS_Code )
:FIsFLEX( FALSE )
{
    Initialize();
    SetSymbol( Symbol, BS_Code );
}
//------------------------------------------------------------------------------------------------------------------------
BO_SymbolDeCompose::~BO_SymbolDeCompose()
{
}
//------------------------------------------------------------------------------------------------------------------------
void BO_SymbolDeCompose::Initialize( void )
{    
    // Initial variant
    UFC::UDateTime Today;
    
    FStrategicType = stUnKnown;    
    ///< Case 2023
    FCYear1Base = Today.getYear() % 10;  ///< 3
    FCYear2Base = Today.getYear() / 100; ///< 20
    FCYear3Base = Today.getYear() / 10;  ///< 202
    FNYear3Base = FCYear3Base + 1;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::GetFLEXExcercisePrice( const char* SymbolPos, char* ePrice )
{
    // Options FLEX Single TXOOX231214P1603000 length 19
    UFC::AnsiString StrikePx;
    UFC::AnsiString PxPart( SymbolPos + 12, 7 ); 
    
    StrikePx.Printf( "0%s0", PxPart.c_str() );
    strcpy( ePrice, StrikePx.c_str() );
    return TRUE;
}    
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::GetExcercisePrice( const char* SymbolPos, const char* SymbolPricePos, char* ePrice )
{
    for( register int i=0; i<5; i++ ) ///< Check Excercise Price  9(5)
    {
        if ( SymbolPricePos[i] < '0' || SymbolPricePos[i] > '9' )	// not equal '0' ~ '9'
             return FALSE;
    }
    UFC::AnsiString Value,StrikePx;
    UFC::AnsiString PxPart( SymbolPricePos, 5 );    
    UFC::AnsiString Sym( SymbolPos, 3 );
    UFC::AnsiString SymbolKey = Sym + PxPart;    
    
    ///< ePrice Format : 123456.789    
    if( StrikePxTable.GetValue("Options", SymbolKey, Value ) == TRUE ) ///< Found in ../cfg/StrikePxDigi.ini
    {        
        switch( Value.ToInt() )
        {
            case 0 : StrikePx.Printf( "0%s000", PxPart.c_str() ); break;
            case 1 : StrikePx.Printf( "00%s00", PxPart.c_str() ); break;
            case 2 : StrikePx.Printf( "000%s0", PxPart.c_str() ); break;            
            case 3 : StrikePx.Printf( "0000%s", PxPart.c_str() ); break;            
            default: StrikePx.Printf( "00%s00", PxPart.c_str() );
                     break;///< Default 2 digit                                                   
        }
    }
    else
    {
        if ( Sym.AnsiCompare( "TXO" )  == 0 || 
             Sym.AnsiCompare( "TX1" )  == 0 || ///<  Week 1, New Version 2012/08/28 for weekly TX Options.
             Sym.AnsiCompare( "TX2" )  == 0 || ///<  Week 2
             Sym.AnsiCompare( "TX4" )  == 0 || ///<  Week 4
             Sym.AnsiCompare( "TX5" )  == 0 || ///<  Week 5
             Sym.AnsiCompare( "TXU" )  == 0 || ///<  Week friday 1, New Version 2025/06/27 for weekly friday TX Options.
             Sym.AnsiCompare( "TXV" )  == 0 || ///<  Week friday 2
             Sym.AnsiCompare( "TXX" )  == 0 || ///<  Week friday 3
             Sym.AnsiCompare( "TXY" )  == 0 || ///<  Week friday 4
             Sym.AnsiCompare( "TXZ" )  == 0 || ///<  Week friday 5
             Sym.AnsiCompare( "TFO" )  == 0 || 
             Sym.AnsiCompare( "TGO" )  == 0 || 
             Sym.AnsiCompare( "XIO" )  == 0  )
            StrikePx.Printf( "0%s000", PxPart.c_str() ); ///< TXN, 0 digit
        else
            StrikePx.Printf( "00%s00", PxPart.c_str() ); ///< Default 2 digit       
    }
    strcpy( ePrice, StrikePx.c_str() );
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::GetMonthAndCP( const char* SymbolMonthPos, char* SettleMonth, char* CP_Code )
{
    // SettleMonth & CP_Code
    if (SymbolMonthPos[1] == '0' && FCYear1Base == 9)
        sprintf(SettleMonth, "%d%c", FNYear3Base, SymbolMonthPos[1]);
    else
        sprintf(SettleMonth, "%d%c", FCYear3Base, SymbolMonthPos[1]);
    switch ( SymbolMonthPos[0] )
    {
        case 'A': strcat( SettleMonth, "01" ); *CP_Code = 'C'; break;
        case 'M': strcat( SettleMonth, "01" ); *CP_Code = 'P'; break;
        case 'B': strcat( SettleMonth, "02" ); *CP_Code = 'C'; break;
        case 'N': strcat( SettleMonth, "02" ); *CP_Code = 'P'; break;
        case 'C': strcat( SettleMonth, "03" ); *CP_Code = 'C'; break;
        case 'O': strcat( SettleMonth, "03" ); *CP_Code = 'P'; break;
        case 'D': strcat( SettleMonth, "04" ); *CP_Code = 'C'; break;
        case 'P': strcat( SettleMonth, "04" ); *CP_Code = 'P'; break;
        case 'E': strcat( SettleMonth, "05" ); *CP_Code = 'C'; break;
        case 'Q': strcat( SettleMonth, "05" ); *CP_Code = 'P'; break;
        case 'F': strcat( SettleMonth, "06" ); *CP_Code = 'C'; break;
        case 'R': strcat( SettleMonth, "06" ); *CP_Code = 'P'; break;
        case 'G': strcat( SettleMonth, "07" ); *CP_Code = 'C'; break;
        case 'S': strcat( SettleMonth, "07" ); *CP_Code = 'P'; break;
        case 'H': strcat( SettleMonth, "08" ); *CP_Code = 'C'; break;
        case 'T': strcat( SettleMonth, "08" ); *CP_Code = 'P'; break;
        case 'I': strcat( SettleMonth, "09" ); *CP_Code = 'C'; break;
        case 'U': strcat( SettleMonth, "09" ); *CP_Code = 'P'; break;
        case 'J': strcat( SettleMonth, "10" ); *CP_Code = 'C'; break;
        case 'V': strcat( SettleMonth, "10" ); *CP_Code = 'P'; break;
        case 'K': strcat( SettleMonth, "11" ); *CP_Code = 'C'; break;
        case 'W': strcat( SettleMonth, "11" ); *CP_Code = 'P'; break;
        case 'L': strcat( SettleMonth, "12" ); *CP_Code = 'C'; break;
        case 'X': strcat( SettleMonth, "12" ); *CP_Code = 'P'; break;
        default:  strcat( SettleMonth, "00" ); *CP_Code = ' '; return FALSE;
    }
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetSingle( void )
{
    FStrategicType = stSingle;
    // 1st foot
    strncpy_zero( FComm1, FSymbol.c_str(), 10 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+3, FExcercisePrice1 ) == FALSE )       
    {
        printf("ExcercisePrice:%s\n", FExcercisePrice1 );                
        return FALSE;
    }
    if ( GetMonthAndCP( FSymbol.c_str()+8, FSettleMonth1, &FCP_Code1 ) == FALSE )
    {
        printf("SettleMonth:%s Call,Put:%c \n", FSettleMonth1, FCP_Code1 );                        
        return FALSE;
    }
    FBS_Code1 = FBS_Code;
    // 2nd foot
    memset( FComm2, ' ', 10 ); FComm2[10] = 0;
    strcpy( FExcercisePrice2, "000000000" );
    strcpy( FSettleMonth2, "      " );
    FBS_Code2 = ' ';
    FCP_Code2 = ' ';
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetFLEXSingle( void )
{
    // Options FLEX Single TXOOX231214P1603000 length 19    
    FIsFLEX = TRUE;
    FStrategicType = stFLEXSingle;
    UFC::AnsiString SettleDate( FSymbol.c_str() + 5, 6 );    
    
    // 1st foot
    strncpy_zero( FComm1, FSymbol.c_str(), 19 );
    if ( GetFLEXExcercisePrice( FSymbol.c_str(), FExcercisePrice1 ) == FALSE )       
    {
        printf("ExcercisePrice:%s\n", FExcercisePrice1 );                
        return FALSE;
    }
    strcpy( FSettleMonth1, SettleDate.c_str() );   
    FBS_Code1 = FBS_Code;
    FCP_Code1 = FSymbol[11];
    
    // 2nd foot
    memset( FComm2, ' ', 19 ); FComm2[19] = 0;
    strcpy( FExcercisePrice2, "000000000" );
    strcpy( FSettleMonth2, "      " );
    FBS_Code2 = ' ';
    FCP_Code2 = ' ';
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetPriceSpread( void )
{
    // 1st foot
    memcpy( FComm1, FSymbol.c_str(), 8 );
    strncpy_zero( FComm1+8, FSymbol.c_str()+14, 2 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+3, FExcercisePrice1 ) == FALSE )
        return FALSE;
    if ( GetMonthAndCP( FSymbol.c_str()+14, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;
    FBS_Code1 = (FBS_Code == 'B') ? 'S' : 'B';
    // 2nd foot
    memcpy( FComm2, FSymbol.c_str(), 3 );
    strncpy_zero( FComm2+3, FSymbol.c_str()+9, 7 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+9, FExcercisePrice2 ) == FALSE )
        return FALSE;
    strcpy( FSettleMonth2, FSettleMonth1 );
    FCP_Code2 = FCP_Code1;
    FBS_Code2 = FBS_Code;
    // check 1.ExcercisePrice
    if ( FCP_Code1 == 'C' )
    {
        if ( atoi(FExcercisePrice1) <= atoi(FExcercisePrice2) )
            return FALSE;
        FStrategicType = stCallPriceSpread;
    }
    else
    {
        if ( atoi(FExcercisePrice2) <= atoi(FExcercisePrice1) )
            return FALSE;
        FStrategicType = stPutPriceSpread;
    }
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetTimeSpread( void )
{
    // 1st foot
    strncpy_zero( FComm1, FSymbol.c_str(), 10 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+3, FExcercisePrice1 ) == FALSE )
        return FALSE;
    if ( GetMonthAndCP( FSymbol.c_str()+8, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;
    FBS_Code1 = (FBS_Code == 'B') ? 'S' : 'B';
    // 2nd foot
    memcpy( FComm2, FSymbol.c_str(), 8 );
    strncpy_zero( FComm2+8, FSymbol.c_str()+11, 2 );
    strcpy( FExcercisePrice2, FExcercisePrice1 );
    if ( GetMonthAndCP( FSymbol.c_str()+11, FSettleMonth2, &FCP_Code2 ) == FALSE )
        return FALSE;
    FBS_Code2 = FBS_Code;
    // check 1.CP_Code 2.SettleMonth
    if ( FCP_Code1 != FCP_Code2 )
        return FALSE;
    if ( atoi(FSettleMonth2) <= atoi(FSettleMonth1) )
        return FALSE;
    if ( FCP_Code1 == 'C' )
        FStrategicType = stCallTimeSpread;
    else
        FStrategicType = stPutTimeSpread;
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetWeeklyOPTimeSpread( void )
{
    // 1st foot
    strncpy_zero( FComm1, FSymbol.c_str(), 10 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+3, FExcercisePrice1 ) == FALSE )
        return FALSE;
    if ( GetMonthAndCP( FSymbol.c_str()+8, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;
    FBS_Code1 = (FBS_Code == 'B') ? 'S' : 'B';
    // 2nd foot
    memcpy( FComm2, FSymbol.c_str()+11, 3 );          ///< Copy TXN
    memcpy( FComm2+3, FSymbol.c_str()+3, 5 );         ///< Copy Strike Price
    strncpy_zero( FComm2+8, FSymbol.c_str() + 14, 2 );///< Copy Month Year
    strcpy( FExcercisePrice2, FExcercisePrice1 );
    if ( GetMonthAndCP( FSymbol.c_str() + 14, FSettleMonth2, &FCP_Code2 ) == FALSE )
        return FALSE;
    FBS_Code2 = FBS_Code;
    // check 1.CP_Code 2.SettleMonth
    if ( FCP_Code1 != FCP_Code2 )
        return FALSE;
    if ( atoi(FSettleMonth2) < atoi(FSettleMonth1) )
        return FALSE;
    if ( FCP_Code1 == 'C' )
        FStrategicType = stCallTimeSpread;
    else
        FStrategicType = stPutTimeSpread;
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetStraddle( void )
{
    FStrategicType = stStraddle;
    // 1st foot
    strncpy_zero( FComm1, FSymbol.c_str(), 10 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+3, FExcercisePrice1 ) == FALSE )
        return FALSE;
    if ( GetMonthAndCP( FSymbol.c_str()+8, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;
    FBS_Code1 = FBS_Code;
    // 2nd foot
    memcpy( FComm2, FSymbol.c_str(), 8 );
    strncpy_zero( FComm2+8, FSymbol.c_str()+11, 2 );
    strcpy( FExcercisePrice2, FExcercisePrice1 );
    if ( GetMonthAndCP( FSymbol.c_str()+11, FSettleMonth2, &FCP_Code2 ) == FALSE )
        return FALSE;
    FBS_Code2 = FBS_Code;
    // check 1.CP_Code 2.SettleMonth
    if ( FCP_Code1 != 'C' || FCP_Code2 != 'P' )
        return FALSE;
    if ( atoi(FSettleMonth1) != atoi(FSettleMonth2) )
        return FALSE;
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetStrangle( void )
{
    FStrategicType = stStrangle;
    // 1st foot
    strncpy_zero( FComm1, FSymbol.c_str(), 10 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+3, FExcercisePrice1 ) == FALSE )
        return FALSE;
    if ( GetMonthAndCP( FSymbol.c_str()+8, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;
    FBS_Code1 = FBS_Code;
    // 2nd foot
    memcpy( FComm2, FSymbol.c_str(), 3 );
    strncpy_zero( FComm2+3, FSymbol.c_str()+11, 7 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+11, FExcercisePrice2 ) == FALSE )
        return FALSE;
    if ( GetMonthAndCP( FSymbol.c_str()+16, FSettleMonth2, &FCP_Code2 ) == FALSE )
        return FALSE;
    FBS_Code2 = FBS_Code;
    // check 1.CP_Code 2.SettleMonth 3.ExcercisePrice
    if ( FCP_Code1 != 'C' || FCP_Code2 != 'P' )
        return FALSE;
    if ( atoi(FSettleMonth1) != atoi(FSettleMonth2) )
        return FALSE;
    if ( atoi(FExcercisePrice1) == atoi(FExcercisePrice2) )
        return FALSE;
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetConRev( void )
{
    FStrategicType = stConRev;
    // 1st foot
    strncpy_zero( FComm1, FSymbol.c_str(), 10 );
    if ( GetExcercisePrice( FSymbol.c_str(), FSymbol.c_str()+3, FExcercisePrice1 ) == FALSE )
        return FALSE;
    if ( GetMonthAndCP( FSymbol.c_str()+8, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;
    FBS_Code1 = (FBS_Code == 'B') ? 'S' : 'B';
    // 2nd foot
    memcpy( FComm2, FSymbol.c_str(), 8 );
    strncpy_zero( FComm2+8, FSymbol.c_str()+11, 2 );
    strcpy( FExcercisePrice2, FExcercisePrice1 );
    if ( GetMonthAndCP( FSymbol.c_str()+11, FSettleMonth2, &FCP_Code2 ) == FALSE )
        return FALSE;
    FBS_Code2 = FBS_Code;
    // check 1.CP_Code 2.SettleMonth
    if ( FCP_Code1 != 'C' || FCP_Code2 != 'P' )
        return FALSE;
    if ( atoi(FSettleMonth1) != atoi(FSettleMonth2) )
        return FALSE;
    return TRUE;
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetSymbol( UFC::AnsiString Symbol, char BS_Code )
{
    UFC::AnsiString Strategic;
    BOOL rtnVal;

    FSymbol = Symbol;
    FBS_Code = BS_Code;
    FSymbol.TrimRight();   
    if( FSymbol.Length() == 10 )	// Options Single
        rtnVal = SetSingle();
    else if( FSymbol.Length() == 19 )	// Options FLEX Single TXOOX231214P1603000 length 19
        rtnVal = SetFLEXSingle();
    else if( FSymbol.Length() == 5 )	// Futures single (New Version)
        rtnVal = SetFuturesSingle();
    else if( FSymbol.Length() == 11  && FSymbol[5] == '/' )// Futures Time Spread.New Version 2013/05 for weekly MXF. 
        rtnVal = SetWeeklyFUTTimeSpread();    
    else if( FSymbol.Length() == 11  && FSymbol[3] == 'F' && FSymbol[4] == 'X' )// Futures FLEX Single MXFFX231214 length 11. 
        rtnVal = SetFuturesFLEXSingle();      
    else if( FSymbol.Length() == 16 && FSymbol[8] == '/' ) // Price Spread
        rtnVal = SetPriceSpread();
    else if( FSymbol.Length() == 13 && FSymbol[10] == '/' )	// Time Spread
        rtnVal = SetTimeSpread();
    else if( FSymbol.Length() == 16 && FSymbol[10] == '/' )	// New Version Time Spread
        rtnVal = SetWeeklyOPTimeSpread();
    else if( FSymbol.Length() == 13 && FSymbol[10] == ':' )	// Straddle
        rtnVal = SetStraddle();
    else if( FSymbol.Length() == 18 && FSymbol[10] == ':' )	// Strangle
        rtnVal = SetStrangle();
    else if( FSymbol.Length() == 13 && FSymbol[10] == '-' )	// Conversion/Reversals
        rtnVal = SetConRev();
    else if( FSymbol.Length() == 8  && FSymbol[5] == '/' ) // Futures Time Spread
        rtnVal = SetFuturesTimeSpread();
    else
        rtnVal = FALSE;        
    switch( FStrategicType )
    {        
        case stSingle: Strategic = "Single";break;
        case stFLEXSingle: Strategic = "FLEXSingle";break;
        case stCallPriceSpread: Strategic = "CallPriceSpread";break;
        case stPutPriceSpread: Strategic = "PutPriceSpread";break;
        case stCallTimeSpread: Strategic = "CallTimeSpread";break;
        case stPutTimeSpread: Strategic = "PutTimeSpread";break;
        case stStraddle: Strategic = "Straddle";break;
        case stStrangle: Strategic = "Strangle";break;
        case stConRev: Strategic = "ConRev";break;
        case stFuturesTimeSpread: Strategic = "FuturesTimeSpread";break;
        case stFuturesSingle: Strategic = "FuturesSingle";break;
        case stFuturesFLEXSingle: Strategic = "FuturesFLEXSingle";break;
        case stUnKnown: Strategic = "Unknown Format";break;
    }    
    UFC::BufferedLog::Printf( " Symbol[%s] Length[%d] Strategic[%s] Result[%d]", FSymbol.c_str(),FSymbol.Length(),Strategic.c_str(), rtnVal );
    return rtnVal;
}
//------------------------------------------------------------------------------------------------------------------------
//  Functions to process Futures symbol. ( For TAIFEX protocol after version 20060607)
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetFuturesSingle( void )
{
    FStrategicType = stFuturesSingle;
    // 1st foot
    memset( FComm1, ' ', 10 ); FComm1[10] = 0;
    memcpy( FComm1, FSymbol.c_str(), 5 );
    strcpy( FExcercisePrice1, "000000000" );
    if ( GetMonthAndCP( FSymbol.c_str()+3, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;
    FBS_Code1 = FBS_Code;
    // 2nd foot
    memset( FComm2, ' ', 10 ); FComm2[10] = 0;
    strcpy( FExcercisePrice2, "000000000" );
    strcpy( FSettleMonth2, "      " );
    FBS_Code2 = ' ';
    FCP_Code2 = ' ';
    FCP_Code1 = ' ';
    return TRUE;    
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetFuturesFLEXSingle( void )
{   // Futures FLEX Single MXFFX231214 length 11. 
    FIsFLEX = TRUE;
    FStrategicType = stFuturesFLEXSingle;
    UFC::AnsiString SettleDate( FSymbol.c_str() + 5, 6 );    
    
    // 1st foot
    memset( FComm1, ' ', 11 ); FComm1[11] = 0;
    memcpy( FComm1, FSymbol.c_str(), 11 );
    strcpy( FExcercisePrice1, "000000000" );
    strcpy( FSettleMonth1, SettleDate.c_str() );
    FBS_Code1 = FBS_Code;
    FCP_Code1 = ' ';
    // 2nd foot
    memset( FComm2, ' ', 11 ); FComm2[11] = 0;
    strcpy( FExcercisePrice2, "000000000" );
    strcpy( FSettleMonth2, "      " );
    FBS_Code2 = ' ';
    FCP_Code2 = ' ';    
    return TRUE;    
}
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetFuturesTimeSpread( void )
{
    FStrategicType = stFuturesTimeSpread;
    ///< for example: TXFA7/C7
    //< 1st foot should be: TXFA7
    memset( FComm1, ' ', 10 ); FComm1[10] = 0;
    memcpy( FComm1, FSymbol.c_str(), 5 );       ///< Copy the TXFA7
    FBS_Code1 = (FBS_Code == 'B') ? 'S' : 'B';  ///< BS code is opposite to the B/S of this order.          	
    if( GetMonthAndCP( FSymbol.c_str()+3, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;        	
    FCP_Code1 = ' ';
    // 2nd foot should be: TXFC7
    memset( FComm2, ' ', 10 ); FComm2[10] = 0;
    memcpy( FComm2, FSymbol.c_str(), 3 );         ///< Copy the TXF
    memcpy( FComm2 + 3, FSymbol.c_str() + 6, 2 ); ///< Copy the C7
    FBS_Code2 = FBS_Code;                         ///< BS code equals the B/S of this order.        
    if( GetMonthAndCP( FSymbol.c_str()+6, FSettleMonth2, &FCP_Code2 ) == FALSE )
        return FALSE;	
    FCP_Code2 = ' ';
    ///< Check SettleMonth	
    if( atoi( FSettleMonth2 ) <= atoi( FSettleMonth1 ) )
        return FALSE;    
    strcpy( FExcercisePrice1, "000000000" );
    strcpy( FExcercisePrice2, "000000000" );
    return TRUE;        
}
//------------------------------------------------------------------------------------------------------------------------
//  Add Futures Time Spread.New Version 2013/05 for weekly MXF. 
//------------------------------------------------------------------------------------------------------------------------
BOOL BO_SymbolDeCompose::SetWeeklyFUTTimeSpread( void )
{
    FStrategicType = stFuturesTimeSpread;
    ///< for example:  MX1C3/MXFC3 MX1K7/MXFK7
    //< 1st foot should be: MX1C3
    memset( FComm1, ' ', 10 ); FComm1[10] = 0;
    memcpy( FComm1, FSymbol.c_str(), 5 );       ///< Copy the MX1C3
    FBS_Code1 = (FBS_Code == 'B') ? 'S' : 'B';  ///< BS code is opposite to the B/S of this order.          	
    if( GetMonthAndCP( FSymbol.c_str()+3, FSettleMonth1, &FCP_Code1 ) == FALSE )
        return FALSE;        	
    FCP_Code1 = ' ';
    // 2nd foot should be: MXFC3
    memset( FComm2, ' ', 10 ); FComm2[10] = 0;
    memcpy( FComm2, FSymbol.c_str()+6, 5 );       ///< Copy the MXFC3
    FBS_Code2 = FBS_Code;                         ///< BS code equals the B/S of this order.        
    if( GetMonthAndCP( FSymbol.c_str()+9, FSettleMonth2, &FCP_Code2 ) == FALSE )
        return FALSE;	
    FCP_Code2 = ' ';
    ///< Check SettleMonth	
    int IntMonth1 = atoi(FSettleMonth1);
    int IntMonth2 = atoi(FSettleMonth2);
    if ( IntMonth1 == IntMonth2 )
    {   // MX1 < MX2 < MXF(3) < MX4 < MX5
        char W1 = FComm1[2];
        char W2 = FComm2[2];
        
        if( W1 == 'F' )  W1 = '3';
        if( W2 == 'F' )  W2 = '3';
        if( W1 >= W2 )   
            return FALSE;    
    }
    else if ( IntMonth1 > IntMonth2 )
        return FALSE;
    strcpy( FExcercisePrice1, "000000000" );
    strcpy( FExcercisePrice2, "000000000" );
    return TRUE;        
}
//------------------------------------------------------------------------------------------------------------------------
