virtual HKSFT CreateKSftTraderApi( void* Owner );
virtual void ReleaseKSftTraderApi( HKSFT hKsft );
virtual void Init( HKSFT hKsft );
virtual const char *GetTradingDay( HKSFT hKsft );
virtual void RegisterFront( HKSFT hKsft, char *pszFrontAddress );
virtual void RegisterNameServer( HKSFT hKsft, char *pszNameServerAddress );
virtual void RegisterSpi( HKSFT hKsft, KS_::CThostFtdcTraderSpi *pSpi );
virtual void SubscribePrivateTopic( HKSFT hKsft, KS_::THOST_TE_RESUME_TYPE nResumeType );
virtual void SubscribePublicTopic( HKSFT hKsft, KS_::THOST_TE_RESUME_TYPE nResumeType );
virtual int ReqAuthenticate( HKSFT hKsft, KS_::CThostFtdcReqAuthenticateField *pReqAuthenticateField, int nRequestID );
virtual int ReqUserLogin( HKSFT hKsft, KS_::CThostFtdcReqUserLoginField *pReqUserLoginField, int nRequestID );
virtual int ReqUserLogout( HKSFT hKsft, KS_::CThostFtdcUserLogoutField *pUserLogout, int nRequestID );
virtual int ReqUserPasswordUpdate( HKSFT hKsft, KS_::CThostFtdcUserPasswordUpdateField *pUserPasswordUpdate, int nRequestID );
virtual int ReqTradingAccountPasswordUpdate( HKSFT hKsft, KS_::CThostFtdcTradingAccountPasswordUpdateField *pTradingAccountPasswordUpdate, int nRequestID );
virtual int ReqOrderInsert( HKSFT hKsft, KS_::CThostFtdcInputOrderField *pInputOrder, int nRequestID );
virtual int ReqParkedOrderInsert( HKSFT hKsft, KS_::CThostFtdcParkedOrderField *pParkedOrder, int nRequestID );
virtual int ReqParkedOrderAction( HKSFT hKsft, KS_::CThostFtdcParkedOrderActionField *pParkedOrderAction, int nRequestID );
virtual int ReqOrderAction( HKSFT hKsft, KS_::CThostFtdcInputOrderActionField *pInputOrderAction, int nRequestID );
virtual int ReqQueryMaxOrderVolume( HKSFT hKsft, KS_::CThostFtdcQueryMaxOrderVolumeField *pQueryMaxOrderVolume, int nRequestID );
virtual int ReqSettlementInfoConfirm( HKSFT hKsft, KS_::CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirm, int nRequestID );
virtual int ReqRemoveParkedOrder( HKSFT hKsft, KS_::CThostFtdcRemoveParkedOrderField *pRemoveParkedOrder, int nRequestID );
virtual int ReqRemoveParkedOrderAction( HKSFT hKsft, KS_::CThostFtdcRemoveParkedOrderActionField *pRemoveParkedOrderAction, int nRequestID );
virtual int ReqQryOrder( HKSFT hKsft, KS_::CThostFtdcQryOrderField *pQryOrder, int nRequestID );
virtual int ReqQryTrade( HKSFT hKsft, KS_::CThostFtdcQryTradeField *pQryTrade, int nRequestID );
virtual int ReqQryInvestorPosition( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionField *pQryInvestorPosition, int nRequestID );
virtual int ReqQryTradingAccount( HKSFT hKsft, KS_::CThostFtdcQryTradingAccountField *pQryTradingAccount, int nRequestID );
virtual int ReqQryInvestor( HKSFT hKsft, KS_::CThostFtdcQryInvestorField *pQryInvestor, int nRequestID );
virtual int ReqQryTradingCode( HKSFT hKsft, KS_::CThostFtdcQryTradingCodeField *pQryTradingCode, int nRequestID );
virtual int ReqQryInstrumentMarginRate( HKSFT hKsft, KS_::CThostFtdcQryInstrumentMarginRateField *pQryInstrumentMarginRate, int nRequestID );
virtual int ReqQryInstrumentCommissionRate( HKSFT hKsft, KS_::CThostFtdcQryInstrumentCommissionRateField *pQryInstrumentCommissionRate, int nRequestID );
virtual int ReqQryExchange( HKSFT hKsft, KS_::CThostFtdcQryExchangeField *pQryExchange, int nRequestID );
virtual int ReqQryInstrument( HKSFT hKsft, KS_::CThostFtdcQryInstrumentField *pQryInstrument, int nRequestID );
virtual int ReqQryDepthMarketData( HKSFT hKsft, KS_::CThostFtdcQryDepthMarketDataField *pQryDepthMarketData, int nRequestID );
virtual int ReqQrySettlementInfo( HKSFT hKsft, KS_::CThostFtdcQrySettlementInfoField *pQrySettlementInfo, int nRequestID );
virtual int ReqQryTransferBank( HKSFT hKsft, KS_::CThostFtdcQryTransferBankField *pQryTransferBank, int nRequestID );
virtual int ReqQryInvestorPositionDetail( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionDetailField *pQryInvestorPositionDetail, int nRequestID );
virtual int ReqQryNotice( HKSFT hKsft, KS_::CThostFtdcQryNoticeField *pQryNotice, int nRequestID );
virtual int ReqQrySettlementInfoConfirm( HKSFT hKsft, KS_::CThostFtdcQrySettlementInfoConfirmField *pQrySettlementInfoConfirm, int nRequestID );
virtual int ReqQryInvestorPositionCombineDetail( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionCombineDetailField *pQryInvestorPositionCombineDetail, int nRequestID );
virtual int ReqQryCFMMCTradingAccountKey( HKSFT hKsft, KS_::CThostFtdcQryCFMMCTradingAccountKeyField *pQryCFMMCTradingAccountKey, int nRequestID );
virtual int ReqQryEWarrantOffset( HKSFT hKsft, KS_::CThostFtdcQryEWarrantOffsetField *pQryEWarrantOffset, int nRequestID );
virtual int ReqQryTransferSerial( HKSFT hKsft, KS_::CThostFtdcQryTransferSerialField *pQryTransferSerial, int nRequestID );
virtual int ReqQryAccountregister( HKSFT hKsft, KS_::CThostFtdcQryAccountregisterField *pQryAccountregister, int nRequestID );
virtual int ReqQryContractBank( HKSFT hKsft, KS_::CThostFtdcQryContractBankField *pQryContractBank, int nRequestID );
virtual int ReqQryParkedOrder( HKSFT hKsft, KS_::CThostFtdcQryParkedOrderField *pQryParkedOrder, int nRequestID );
virtual int ReqQryParkedOrderAction( HKSFT hKsft, KS_::CThostFtdcQryParkedOrderActionField *pQryParkedOrderAction, int nRequestID );
virtual int ReqQryTradingNotice( HKSFT hKsft, KS_::CThostFtdcQryTradingNoticeField *pQryTradingNotice, int nRequestID );
virtual int ReqQryBrokerTradingParams( HKSFT hKsft, KS_::CThostFtdcQryBrokerTradingParamsField *pQryBrokerTradingParams, int nRequestID );
virtual int ReqQryBrokerTradingAlgos( HKSFT hKsft, KS_::CThostFtdcQryBrokerTradingAlgosField *pQryBrokerTradingAlgos, int nRequestID );
virtual int ReqFromBankToFutureByFuture( HKSFT hKsft, KS_::CThostFtdcReqTransferField *pReqTransfer, int nRequestID );
virtual int ReqFromFutureToBankByFuture( HKSFT hKsft, KS_::CThostFtdcReqTransferField *pReqTransfer, int nRequestID );
virtual int ReqQueryBankAccountMoneyByFuture( HKSFT hKsft, KS_::CThostFtdcReqQueryAccountField *pReqQueryAccount, int nRequestID );
virtual int ReqQueryInvestorOpenPosition( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionDetailField *pQryInvestorOpenPosition, int nRequestID );
virtual int ReqQueryInvestorOpenCombinePosition( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionCombineDetailField *pQryInvestorOpenCombinePosition, int nRequestID );
virtual int SetWritablePath( HKSFT hKsft, const char *szpath = "" );
virtual void* LoadExtApi( HKSFT hKsft, void * spi, const char *ExtApiName = "KSCosApi" );
virtual int ReqBulkCancelOrder ( HKSFT hKsft, KS_::CThostFtdcBulkCancelOrderField *pBulkCancelOrder, int nRequestID );
