virtual HKSFT CreateKSftTraderApi();
virtual void ReleaseKSftTraderApi();
virtual void Init();
virtual const char *GetTradingDay();
virtual void RegisterFront( char *pszFrontAddress );
virtual void RegisterNameServer( char *pszNameServerAddress );
virtual void RegisterSpi( KS_::CThostFtdcTraderSpi *pSpi );
virtual void SubscribePrivateTopic( KS_::THOST_TE_RESUME_TYPE nResumeType );
virtual void SubscribePublicTopic( KS_::THOST_TE_RESUME_TYPE nResumeType );
virtual int ReqAuthenticate( KS_::CThostFtdcReqAuthenticateField *pReqAuthenticateField, int nRequestID );
virtual int ReqUserLogin( KS_::CThostFtdcReqUserLoginField *pReqUserLoginField, int nRequestID );
virtual int ReqUserLogout( KS_::CThostFtdcUserLogoutField *pUserLogout, int nRequestID );
virtual int ReqUserPasswordUpdate( KS_::CThostFtdcUserPasswordUpdateField *pUserPasswordUpdate, int nRequestID );
virtual int ReqTradingAccountPasswordUpdate( KS_::CThostFtdcTradingAccountPasswordUpdateField *pTradingAccountPasswordUpdate, int nRequestID );
virtual int ReqOrderInsert( KS_::CThostFtdcInputOrderField *pInputOrder, int nRequestID );
virtual int ReqParkedOrderInsert( KS_::CThostFtdcParkedOrderField *pParkedOrder, int nRequestID );
virtual int ReqParkedOrderAction( KS_::CThostFtdcParkedOrderActionField *pParkedOrderAction, int nRequestID );
virtual int ReqOrderAction( KS_::CThostFtdcInputOrderActionField *pInputOrderAction, int nRequestID );
virtual int ReqQueryMaxOrderVolume( KS_::CThostFtdcQueryMaxOrderVolumeField *pQueryMaxOrderVolume, int nRequestID );
virtual int ReqSettlementInfoConfirm( KS_::CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirm, int nRequestID );
virtual int ReqRemoveParkedOrder( KS_::CThostFtdcRemoveParkedOrderField *pRemoveParkedOrder, int nRequestID );
virtual int ReqRemoveParkedOrderAction( KS_::CThostFtdcRemoveParkedOrderActionField *pRemoveParkedOrderAction, int nRequestID );
virtual int ReqQryOrder( KS_::CThostFtdcQryOrderField *pQryOrder, int nRequestID );
virtual int ReqQryTrade( KS_::CThostFtdcQryTradeField *pQryTrade, int nRequestID );
virtual int ReqQryInvestorPosition( KS_::CThostFtdcQryInvestorPositionField *pQryInvestorPosition, int nRequestID );
virtual int ReqQryTradingAccount( KS_::CThostFtdcQryTradingAccountField *pQryTradingAccount, int nRequestID );
virtual int ReqQryInvestor( KS_::CThostFtdcQryInvestorField *pQryInvestor, int nRequestID );
virtual int ReqQryTradingCode( KS_::CThostFtdcQryTradingCodeField *pQryTradingCode, int nRequestID );
virtual int ReqQryInstrumentMarginRate( KS_::CThostFtdcQryInstrumentMarginRateField *pQryInstrumentMarginRate, int nRequestID );
virtual int ReqQryInstrumentCommissionRate( KS_::CThostFtdcQryInstrumentCommissionRateField *pQryInstrumentCommissionRate, int nRequestID );
virtual int ReqQryExchange( KS_::CThostFtdcQryExchangeField *pQryExchange, int nRequestID );
virtual int ReqQryInstrument( KS_::CThostFtdcQryInstrumentField *pQryInstrument, int nRequestID );
virtual int ReqQryDepthMarketData( KS_::CThostFtdcQryDepthMarketDataField *pQryDepthMarketData, int nRequestID );
virtual int ReqQrySettlementInfo( KS_::CThostFtdcQrySettlementInfoField *pQrySettlementInfo, int nRequestID );
virtual int ReqQryTransferBank( KS_::CThostFtdcQryTransferBankField *pQryTransferBank, int nRequestID );
virtual int ReqQryInvestorPositionDetail( KS_::CThostFtdcQryInvestorPositionDetailField *pQryInvestorPositionDetail, int nRequestID );
virtual int ReqQryNotice( KS_::CThostFtdcQryNoticeField *pQryNotice, int nRequestID );
virtual int ReqQrySettlementInfoConfirm( KS_::CThostFtdcQrySettlementInfoConfirmField *pQrySettlementInfoConfirm, int nRequestID );
virtual int ReqQryInvestorPositionCombineDetail( KS_::CThostFtdcQryInvestorPositionCombineDetailField *pQryInvestorPositionCombineDetail, int nRequestID );
virtual int ReqQryCFMMCTradingAccountKey( KS_::CThostFtdcQryCFMMCTradingAccountKeyField *pQryCFMMCTradingAccountKey, int nRequestID );
virtual int ReqQryEWarrantOffset( KS_::CThostFtdcQryEWarrantOffsetField *pQryEWarrantOffset, int nRequestID );
virtual int ReqQryTransferSerial( KS_::CThostFtdcQryTransferSerialField *pQryTransferSerial, int nRequestID );
virtual int ReqQryAccountregister( KS_::CThostFtdcQryAccountregisterField *pQryAccountregister, int nRequestID );
virtual int ReqQryContractBank( KS_::CThostFtdcQryContractBankField *pQryContractBank, int nRequestID );
virtual int ReqQryParkedOrder( KS_::CThostFtdcQryParkedOrderField *pQryParkedOrder, int nRequestID );
virtual int ReqQryParkedOrderAction( KS_::CThostFtdcQryParkedOrderActionField *pQryParkedOrderAction, int nRequestID );
virtual int ReqQryTradingNotice( KS_::CThostFtdcQryTradingNoticeField *pQryTradingNotice, int nRequestID );
virtual int ReqQryBrokerTradingParams( KS_::CThostFtdcQryBrokerTradingParamsField *pQryBrokerTradingParams, int nRequestID );
virtual int ReqQryBrokerTradingAlgos( KS_::CThostFtdcQryBrokerTradingAlgosField *pQryBrokerTradingAlgos, int nRequestID );
virtual int ReqFromBankToFutureByFuture( KS_::CThostFtdcReqTransferField *pReqTransfer, int nRequestID );
virtual int ReqFromFutureToBankByFuture( KS_::CThostFtdcReqTransferField *pReqTransfer, int nRequestID );
virtual int ReqQueryBankAccountMoneyByFuture( KS_::CThostFtdcReqQueryAccountField *pReqQueryAccount, int nRequestID );
virtual int ReqQueryInvestorOpenPosition( KS_::CThostFtdcQryInvestorPositionDetailField *pQryInvestorOpenPosition, int nRequestID );
virtual int ReqQueryInvestorOpenCombinePosition( KS_::CThostFtdcQryInvestorPositionCombineDetailField *pQryInvestorOpenCombinePosition, int nRequestID );
virtual int SetWritablePath( const char *szpath = "" );
virtual void * LoadExtApi( void * spi, const char *ExtApiName = "KSCosApi" );
virtual int ReqBulkCancelOrder ( KS_::CThostFtdcBulkCancelOrderField *pBulkCancelOrder, int nRequestID );
