//------------------------------------------------------------------------------------------------------------------------
#ifndef __KSftAPIDynamic_H
#define __KSftAPIDynamic_H
//------------------------------------------------------------------------------------------------------------------------
#include "KSUserApiDataTypeEx.h"
#include "KSUserApiStructEx.h"
//------------------------------------------------------------------------------------------------------------------------
typedef void* HKSFT;
//------------------------------------------------------------------------------------------------------------------------
#ifndef Namespace__KingstarAPI_
#define Namespace__KingstarAPI_
#define KS_ KingstarAPI
#endif
//------------------------------------------------------------------------------------------------------------------------
extern "C"
{
//------------------------------------------------------------------------------------------------------------------------
// Define all callback functions.
//------------------------------------------------------------------------------------------------------------------------
typedef void (__cdecl *pfOnFrontConnected) ( HKSFT Owner );
typedef void (__cdecl *pfOnFrontDisconnected) ( HKSFT Owner, int nReason );
typedef void (__cdecl *pfOnHeartBeatWarning) ( HKSFT Owner, int nTimeLapse );
typedef void (__cdecl *pfOnRspAuthenticate) ( HKSFT Owner, KS_::CThostFtdcRspAuthenticateField *pRspAuthenticateField, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspUserLogin) ( HKSFT Owner, KS_::CThostFtdcRspUserLoginField *pRspUserLogin, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspUserLogout) ( HKSFT Owner, KS_::CThostFtdcUserLogoutField *pUserLogout, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspUserPasswordUpdate) ( HKSFT Owner, KS_::CThostFtdcUserPasswordUpdateField *pUserPasswordUpdate, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspTradingAccountPasswordUpdate) ( HKSFT Owner, KS_::CThostFtdcTradingAccountPasswordUpdateField *pTradingAccountPasswordUpdate, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspOrderInsert) ( HKSFT Owner, KS_::CThostFtdcInputOrderField *pInputOrder, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspParkedOrderInsert) ( HKSFT Owner, KS_::CThostFtdcParkedOrderField *pParkedOrder, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspParkedOrderAction) ( HKSFT Owner, KS_::CThostFtdcParkedOrderActionField *pParkedOrderAction, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspOrderAction) ( HKSFT Owner, KS_::CThostFtdcInputOrderActionField *pInputOrderAction, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQueryMaxOrderVolume) ( HKSFT Owner, KS_::CThostFtdcQueryMaxOrderVolumeField *pQueryMaxOrderVolume, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspSettlementInfoConfirm) ( HKSFT Owner, KS_::CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirm, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspRemoveParkedOrder) ( HKSFT Owner, KS_::CThostFtdcRemoveParkedOrderField *pRemoveParkedOrder, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspRemoveParkedOrderAction) ( HKSFT Owner, KS_::CThostFtdcRemoveParkedOrderActionField *pRemoveParkedOrderAction, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspExecOrderInsert) ( HKSFT Owner, KS_::CThostFtdcInputExecOrderField *pInputExecOrder, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspExecOrderAction) ( HKSFT Owner, KS_::CThostFtdcInputExecOrderActionField *pInputExecOrderAction, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspForQuoteInsert) ( HKSFT Owner, KS_::CThostFtdcInputForQuoteField *pInputForQuote, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQuoteInsert) ( HKSFT Owner, KS_::CThostFtdcInputQuoteField *pInputQuote, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQuoteAction) ( HKSFT Owner, KS_::CThostFtdcInputQuoteActionField *pInputQuoteAction, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryOrder) ( HKSFT Owner, KS_::CThostFtdcOrderField *pOrder, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryTrade) ( HKSFT Owner, KS_::CThostFtdcTradeField *pTrade, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInvestorPosition) ( HKSFT Owner, KS_::CThostFtdcInvestorPositionField *pInvestorPosition, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryTradingAccount) ( HKSFT Owner, KS_::CThostFtdcTradingAccountField *pTradingAccount, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInvestor) ( HKSFT Owner, KS_::CThostFtdcInvestorField *pInvestor, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryTradingCode) ( HKSFT Owner, KS_::CThostFtdcTradingCodeField *pTradingCode, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInstrumentMarginRate) ( HKSFT Owner, KS_::CThostFtdcInstrumentMarginRateField *pInstrumentMarginRate, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInstrumentCommissionRate) ( HKSFT Owner, KS_::CThostFtdcInstrumentCommissionRateField *pInstrumentCommissionRate, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryExchange) ( HKSFT Owner, KS_::CThostFtdcExchangeField *pExchange, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryProduct) ( HKSFT Owner, KS_::CThostFtdcProductField *pProduct, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInstrument) ( HKSFT Owner, KS_::CThostFtdcInstrumentField *pInstrument, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryDepthMarketData) ( HKSFT Owner, KS_::CThostFtdcDepthMarketDataField *pDepthMarketData, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQrySettlementInfo) ( HKSFT Owner, KS_::CThostFtdcSettlementInfoField *pSettlementInfo, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryTransferBank) ( HKSFT Owner, KS_::CThostFtdcTransferBankField *pTransferBank, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInvestorPositionDetail) ( HKSFT Owner, KS_::CThostFtdcInvestorPositionDetailField *pInvestorPositionDetail, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryNotice) ( HKSFT Owner, KS_::CThostFtdcNoticeField *pNotice, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQrySettlementInfoConfirm) ( HKSFT Owner, KS_::CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirm, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInvestorPositionCombineDetail) ( HKSFT Owner, KS_::CThostFtdcInvestorPositionCombineDetailField *pInvestorPositionCombineDetail, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryCFMMCTradingAccountKey) ( HKSFT Owner, KS_::CThostFtdcCFMMCTradingAccountKeyField *pCFMMCTradingAccountKey, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryEWarrantOffset) ( HKSFT Owner, KS_::CThostFtdcEWarrantOffsetField *pEWarrantOffset, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInvestorProductGroupMargin) ( HKSFT Owner, KS_::CThostFtdcInvestorProductGroupMarginField *pInvestorProductGroupMargin, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryExchangeMarginRate) ( HKSFT Owner, KS_::CThostFtdcExchangeMarginRateField *pExchangeMarginRate, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryExchangeMarginRateAdjust) ( HKSFT Owner, KS_::CThostFtdcExchangeMarginRateAdjustField *pExchangeMarginRateAdjust, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryExchangeRate) ( HKSFT Owner, KS_::CThostFtdcExchangeRateField *pExchangeRate, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQrySecAgentACIDMap) ( HKSFT Owner, KS_::CThostFtdcSecAgentACIDMapField *pSecAgentACIDMap, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryOptionInstrTradeCost) ( HKSFT Owner, KS_::CThostFtdcOptionInstrTradeCostField *pOptionInstrTradeCost, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryOptionInstrCommRate) ( HKSFT Owner, KS_::CThostFtdcOptionInstrCommRateField *pOptionInstrCommRate, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryExecOrder) ( HKSFT Owner, KS_::CThostFtdcExecOrderField *pExecOrder, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryForQuote) ( HKSFT Owner, KS_::CThostFtdcForQuoteField *pForQuote, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryQuote) ( HKSFT Owner, KS_::CThostFtdcQuoteField *pQuote, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryTransferSerial) ( HKSFT Owner, KS_::CThostFtdcTransferSerialField *pTransferSerial, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryAccountregister) ( HKSFT Owner, KS_::CThostFtdcAccountregisterField *pAccountregister, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspError) ( HKSFT Owner, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRtnOrder) ( HKSFT Owner, KS_::CThostFtdcOrderField *pOrder );
typedef void (__cdecl *pfOnRtnTrade) ( HKSFT Owner, KS_::CThostFtdcTradeField *pTrade );
typedef void (__cdecl *pfOnErrRtnOrderInsert) ( HKSFT Owner, KS_::CThostFtdcInputOrderField *pInputOrder, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnErrRtnOrderAction) ( HKSFT Owner, KS_::CThostFtdcOrderActionField *pOrderAction, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnRtnInstrumentStatus) ( HKSFT Owner, KS_::CThostFtdcInstrumentStatusField *pInstrumentStatus );
typedef void (__cdecl *pfOnRtnTradingNotice) ( HKSFT Owner, KS_::CThostFtdcTradingNoticeInfoField *pTradingNoticeInfo );
typedef void (__cdecl *pfOnRtnErrorConditionalOrder) ( HKSFT Owner, KS_::CThostFtdcErrorConditionalOrderField *pErrorConditionalOrder );
typedef void (__cdecl *pfOnRtnExecOrder) ( HKSFT Owner, KS_::CThostFtdcExecOrderField *pExecOrder );
typedef void (__cdecl *pfOnErrRtnExecOrderInsert) ( HKSFT Owner, KS_::CThostFtdcInputExecOrderField *pInputExecOrder, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnErrRtnExecOrderAction) ( HKSFT Owner, KS_::CThostFtdcExecOrderActionField *pExecOrderAction, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnErrRtnForQuoteInsert) ( HKSFT Owner, KS_::CThostFtdcInputExecOrderField *pInputExecOrder, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnRtnQuote) ( HKSFT Owner, KS_::CThostFtdcQuoteField *pQuote );
typedef void (__cdecl *pfOnErrRtnQuoteInsert) ( HKSFT Owner, KS_::CThostFtdcInputQuoteField *pInputQuote, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnErrRtnQuoteAction) ( HKSFT Owner, KS_::CThostFtdcQuoteActionField *pQuoteAction, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnRspQryContractBank) ( HKSFT Owner, KS_::CThostFtdcContractBankField *pContractBank, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryParkedOrder) ( HKSFT Owner, KS_::CThostFtdcParkedOrderField *pParkedOrder, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryParkedOrderAction) ( HKSFT Owner, KS_::CThostFtdcParkedOrderActionField *pParkedOrderAction, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryTradingNotice) ( HKSFT Owner, KS_::CThostFtdcTradingNoticeField *pTradingNotice, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryBrokerTradingParams) ( HKSFT Owner, KS_::CThostFtdcBrokerTradingParamsField *pBrokerTradingParams, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryBrokerTradingAlgos) ( HKSFT Owner, KS_::CThostFtdcBrokerTradingAlgosField *pBrokerTradingAlgos, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRtnFromBankToFutureByBank) ( HKSFT Owner, KS_::CThostFtdcRspTransferField *pRspTransfer );
typedef void (__cdecl *pfOnRtnFromFutureToBankByBank) ( HKSFT Owner, KS_::CThostFtdcRspTransferField *pRspTransfer );
typedef void (__cdecl *pfOnRtnRepealFromBankToFutureByBank) ( HKSFT Owner, KS_::CThostFtdcRspRepealField *pRspRepeal );
typedef void (__cdecl *pfOnRtnRepealFromFutureToBankByBank) ( HKSFT Owner, KS_::CThostFtdcRspRepealField *pRspRepeal );
typedef void (__cdecl *pfOnRtnFromBankToFutureByFuture) ( HKSFT Owner, KS_::CThostFtdcRspTransferField *pRspTransfer );
typedef void (__cdecl *pfOnRtnFromFutureToBankByFuture) ( HKSFT Owner, KS_::CThostFtdcRspTransferField *pRspTransfer );
typedef void (__cdecl *pfOnRtnRepealFromBankToFutureByFutureManual) ( HKSFT Owner, KS_::CThostFtdcRspRepealField *pRspRepeal );
typedef void (__cdecl *pfOnRtnRepealFromFutureToBankByFutureManual) ( HKSFT Owner, KS_::CThostFtdcRspRepealField *pRspRepeal );
typedef void (__cdecl *pfOnRtnQueryBankBalanceByFuture) ( HKSFT Owner, KS_::CThostFtdcNotifyQueryAccountField *pNotifyQueryAccount );
typedef void (__cdecl *pfOnErrRtnBankToFutureByFuture) ( HKSFT Owner, KS_::CThostFtdcReqTransferField *pReqTransfer, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnErrRtnFutureToBankByFuture) ( HKSFT Owner, KS_::CThostFtdcReqTransferField *pReqTransfer, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnErrRtnRepealBankToFutureByFutureManual) ( HKSFT Owner, KS_::CThostFtdcReqRepealField *pReqRepeal, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnErrRtnRepealFutureToBankByFutureManual) ( HKSFT Owner, KS_::CThostFtdcReqRepealField *pReqRepeal, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnErrRtnQueryBankBalanceByFuture) ( HKSFT Owner, KS_::CThostFtdcReqQueryAccountField *pReqQueryAccount, KS_::CThostFtdcRspInfoField *pRspInfo );
typedef void (__cdecl *pfOnRtnRepealFromBankToFutureByFuture) ( HKSFT Owner, KS_::CThostFtdcRspRepealField *pRspRepeal );
typedef void (__cdecl *pfOnRtnRepealFromFutureToBankByFuture) ( HKSFT Owner, KS_::CThostFtdcRspRepealField *pRspRepeal );
typedef void (__cdecl *pfOnRspFromBankToFutureByFuture) ( HKSFT Owner, KS_::CThostFtdcReqTransferField *pReqTransfer, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspFromFutureToBankByFuture) ( HKSFT Owner, KS_::CThostFtdcReqTransferField *pReqTransfer, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQueryBankAccountMoneyByFuture) ( HKSFT Owner, KS_::CThostFtdcReqQueryAccountField *pReqQueryAccount, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRtnOpenAccountByBank) ( HKSFT Owner, KS_::CThostFtdcOpenAccountField *pOpenAccount );
typedef void (__cdecl *pfOnRtnCancelAccountByBank) ( HKSFT Owner, KS_::CThostFtdcCancelAccountField *pCancelAccount );
typedef void (__cdecl *pfOnRtnChangeAccountByBank) ( HKSFT Owner, KS_::CThostFtdcChangeAccountField *pChangeAccount );
typedef void (__cdecl *pfOnRspQryInvestorOpenPosition) ( HKSFT Owner, KS_::CThostFtdcInvestorPositionDetailField *pInvestorPositionDetail, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspQryInvestorOpenCombinePosition) ( HKSFT Owner, KS_::CThostFtdcInvestorPositionCombineDetailField *pInvestorPositionCombineDetail, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
typedef void (__cdecl *pfOnRspBulkCancelOrder) ( HKSFT Owner, KS_::CThostFtdcBulkCancelOrderField *pBulkCancelOrder, KS_::CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast );
//------------------------------------------------------------------------------------------------------------------------
// Define all export function pointors
//------------------------------------------------------------------------------------------------------------------------
typedef HKSFT (__cdecl *lpCreateKSftTraderApi) ( void* Owner );
typedef void (__cdecl *lpReleaseKSftTraderApi) ( HKSFT hKsft );
typedef void (__cdecl *lpInit) ( HKSFT hKsft );
typedef const char* (__cdecl *lpGetTradingDay) ( HKSFT hKsft );
typedef void (__cdecl *lpRegisterFront) ( HKSFT hKsft, char *pszFrontAddress );
typedef void (__cdecl *lpRegisterNameServer) ( HKSFT hKsft, char *pszNsAddress );
typedef void (__cdecl *lpRegisterFensUserInfo) ( HKSFT hKsft, KS_::CThostFtdcFensUserInfoField * pFensUserInfo );
//typedef void (__cdecl *lpRegisterSpi) ( HKSFT hKsft, KS_::CThostFtdcTraderSpi *pSpi );
typedef void (__cdecl *lpSubscribePrivateTopic) ( HKSFT hKsft, KS_::THOST_TE_RESUME_TYPE nResumeType );
typedef void (__cdecl *lpSubscribePublicTopic) ( HKSFT hKsft, KS_::THOST_TE_RESUME_TYPE nResumeType );
typedef int  (__cdecl *lpReqAuthenticate) ( HKSFT hKsft, KS_::CThostFtdcReqAuthenticateField *pReqAuthenticateField, int nRequestID );
typedef int  (__cdecl *lpReqUserLogin) ( HKSFT hKsft, KS_::CThostFtdcReqUserLoginField *pReqUserLoginField, int nRequestID );
typedef int  (__cdecl *lpReqUserLogout) ( HKSFT hKsft, KS_::CThostFtdcUserLogoutField *pUserLogout, int nRequestID );
typedef int  (__cdecl *lpReqUserPasswordUpdate) ( HKSFT hKsft, KS_::CThostFtdcUserPasswordUpdateField *pUserPasswordUpdate, int nRequestID );
typedef int  (__cdecl *lpReqTradingAccountPasswordUpdate) ( HKSFT hKsft, KS_::CThostFtdcTradingAccountPasswordUpdateField *pTradingAccountPasswordUpdate, int nRequestID );
typedef int  (__cdecl *lpReqOrderInsert) ( HKSFT hKsft, KS_::CThostFtdcInputOrderField *pInputOrder, int nRequestID );
typedef int  (__cdecl *lpReqParkedOrderInsert) ( HKSFT hKsft, KS_::CThostFtdcParkedOrderField *pParkedOrder, int nRequestID );
typedef int  (__cdecl *lpReqParkedOrderAction) ( HKSFT hKsft, KS_::CThostFtdcParkedOrderActionField *pParkedOrderAction, int nRequestID );
typedef int  (__cdecl *lpReqOrderAction) ( HKSFT hKsft, KS_::CThostFtdcInputOrderActionField *pInputOrderAction, int nRequestID );
typedef int  (__cdecl *lpReqQueryMaxOrderVolume) ( HKSFT hKsft, KS_::CThostFtdcQueryMaxOrderVolumeField *pQueryMaxOrderVolume, int nRequestID );
typedef int  (__cdecl *lpReqSettlementInfoConfirm) ( HKSFT hKsft, KS_::CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirm, int nRequestID );
typedef int  (__cdecl *lpReqRemoveParkedOrder) ( HKSFT hKsft, KS_::CThostFtdcRemoveParkedOrderField *pRemoveParkedOrder, int nRequestID );
typedef int  (__cdecl *lpReqRemoveParkedOrderAction) ( HKSFT hKsft, KS_::CThostFtdcRemoveParkedOrderActionField *pRemoveParkedOrderAction, int nRequestID );
typedef int  (__cdecl *lpReqExecOrderInsert) ( HKSFT hKsft, KS_::CThostFtdcInputExecOrderField *pInputExecOrder, int nRequestID );
typedef int  (__cdecl *lpReqExecOrderAction) ( HKSFT hKsft, KS_::CThostFtdcInputExecOrderActionField *pInputExecOrderAction, int nRequestID );
typedef int  (__cdecl *lpReqForQuoteInsert) ( HKSFT hKsft, KS_::CThostFtdcInputForQuoteField *pInputForQuote, int nRequestID );
typedef int  (__cdecl *lpReqQuoteInsert) ( HKSFT hKsft, KS_::CThostFtdcInputQuoteField *pInputQuote, int nRequestID );
typedef int  (__cdecl *lpReqQuoteAction) ( HKSFT hKsft, KS_::CThostFtdcInputQuoteActionField *pInputQuoteAction, int nRequestID );
typedef int  (__cdecl *lpReqQryOrder) ( HKSFT hKsft, KS_::CThostFtdcQryOrderField *pQryOrder, int nRequestID );
typedef int  (__cdecl *lpReqQryTrade) ( HKSFT hKsft, KS_::CThostFtdcQryTradeField *pQryTrade, int nRequestID );
typedef int  (__cdecl *lpReqQryInvestorPosition) ( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionField *pQryInvestorPosition, int nRequestID );
typedef int  (__cdecl *lpReqQryTradingAccount) ( HKSFT hKsft, KS_::CThostFtdcQryTradingAccountField *pQryTradingAccount, int nRequestID );
typedef int  (__cdecl *lpReqQryInvestor) ( HKSFT hKsft, KS_::CThostFtdcQryInvestorField *pQryInvestor, int nRequestID );
typedef int  (__cdecl *lpReqQryTradingCode) ( HKSFT hKsft, KS_::CThostFtdcQryTradingCodeField *pQryTradingCode, int nRequestID );
typedef int  (__cdecl *lpReqQryInstrumentMarginRate) ( HKSFT hKsft, KS_::CThostFtdcQryInstrumentMarginRateField *pQryInstrumentMarginRate, int nRequestID );
typedef int  (__cdecl *lpReqQryInstrumentCommissionRate) ( HKSFT hKsft, KS_::CThostFtdcQryInstrumentCommissionRateField *pQryInstrumentCommissionRate, int nRequestID );
typedef int  (__cdecl *lpReqQryExchange) ( HKSFT hKsft, KS_::CThostFtdcQryExchangeField *pQryExchange, int nRequestID );
typedef int  (__cdecl *lpReqQryProduct) ( HKSFT hKsft, KS_::CThostFtdcQryProductField *pQryProduct, int nRequestID );
typedef int  (__cdecl *lpReqQryInstrument) ( HKSFT hKsft, KS_::CThostFtdcQryInstrumentField *pQryInstrument, int nRequestID );
typedef int  (__cdecl *lpReqQryDepthMarketData) ( HKSFT hKsft, KS_::CThostFtdcQryDepthMarketDataField *pQryDepthMarketData, int nRequestID );
typedef int  (__cdecl *lpReqQrySettlementInfo) ( HKSFT hKsft, KS_::CThostFtdcQrySettlementInfoField *pQrySettlementInfo, int nRequestID );
typedef int  (__cdecl *lpReqQryTransferBank) ( HKSFT hKsft, KS_::CThostFtdcQryTransferBankField *pQryTransferBank, int nRequestID );
typedef int  (__cdecl *lpReqQryInvestorPositionDetail) ( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionDetailField *pQryInvestorPositionDetail, int nRequestID );
typedef int  (__cdecl *lpReqQryNotice) ( HKSFT hKsft, KS_::CThostFtdcQryNoticeField *pQryNotice, int nRequestID );
typedef int  (__cdecl *lpReqQrySettlementInfoConfirm) ( HKSFT hKsft, KS_::CThostFtdcQrySettlementInfoConfirmField *pQrySettlementInfoConfirm, int nRequestID );
typedef int  (__cdecl *lpReqQryInvestorPositionCombineDetail) ( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionCombineDetailField *pQryInvestorPositionCombineDetail, int nRequestID );
typedef int  (__cdecl *lpReqQryCFMMCTradingAccountKey) ( HKSFT hKsft, KS_::CThostFtdcQryCFMMCTradingAccountKeyField *pQryCFMMCTradingAccountKey, int nRequestID );
typedef int  (__cdecl *lpReqQryEWarrantOffset) ( HKSFT hKsft, KS_::CThostFtdcQryEWarrantOffsetField *pQryEWarrantOffset, int nRequestID );
typedef int  (__cdecl *lpReqQryInvestorProductGroupMargin) ( HKSFT hKsft, KS_::CThostFtdcQryInvestorProductGroupMarginField *pQryInvestorProductGroupMargin, int nRequestID );
typedef int  (__cdecl *lpReqQryExchangeMarginRate) ( HKSFT hKsft, KS_::CThostFtdcQryExchangeMarginRateField *pQryExchangeMarginRate, int nRequestID);
typedef int  (__cdecl *lpReqQryExchangeMarginRateAdjust) ( HKSFT hKsft, KS_::CThostFtdcQryExchangeMarginRateAdjustField *pQryExchangeMarginRateAdjust, int nRequestID );
typedef int  (__cdecl *lpReqQryExchangeRate) ( HKSFT hKsft, KS_::CThostFtdcQryExchangeRateField *pQryExchangeRate, int nRequestID );
typedef int  (__cdecl *lpReqQrySecAgentACIDMap) ( HKSFT hKsft, KS_::CThostFtdcQrySecAgentACIDMapField *pQrySecAgentACIDMap, int nRequestID );
typedef int  (__cdecl *lpReqQryOptionInstrTradeCost) ( HKSFT hKsft, KS_::CThostFtdcQryOptionInstrTradeCostField *pQryOptionInstrTradeCost, int nRequestID );
typedef int  (__cdecl *lpReqQryOptionInstrCommRate) ( HKSFT hKsft, KS_::CThostFtdcQryOptionInstrCommRateField *pQryOptionInstrCommRate, int nRequestID );
typedef int  (__cdecl *lpReqQryExecOrder) ( HKSFT hKsft, KS_::CThostFtdcQryExecOrderField *pQryExecOrder, int nRequestID );
typedef int  (__cdecl *lpReqQryForQuote) ( HKSFT hKsft, KS_::CThostFtdcQryForQuoteField *pQryForQuote, int nRequestID );
typedef int  (__cdecl *lpReqQryQuote) ( HKSFT hKsft, KS_::CThostFtdcQryQuoteField *pQryQuote, int nRequestID );
typedef int  (__cdecl *lpReqQryTransferSerial) ( HKSFT hKsft, KS_::CThostFtdcQryTransferSerialField *pQryTransferSerial, int nRequestID );
typedef int  (__cdecl *lpReqQryAccountregister) ( HKSFT hKsft, KS_::CThostFtdcQryAccountregisterField *pQryAccountregister, int nRequestID );
typedef int  (__cdecl *lpReqQryContractBank) ( HKSFT hKsft, KS_::CThostFtdcQryContractBankField *pQryContractBank, int nRequestID );
typedef int  (__cdecl *lpReqQryParkedOrder) ( HKSFT hKsft, KS_::CThostFtdcQryParkedOrderField *pQryParkedOrder, int nRequestID );
typedef int  (__cdecl *lpReqQryParkedOrderAction) ( HKSFT hKsft, KS_::CThostFtdcQryParkedOrderActionField *pQryParkedOrderAction, int nRequestID );
typedef int  (__cdecl *lpReqQryTradingNotice) ( HKSFT hKsft, KS_::CThostFtdcQryTradingNoticeField *pQryTradingNotice, int nRequestID );
typedef int  (__cdecl *lpReqQryBrokerTradingParams) ( HKSFT hKsft, KS_::CThostFtdcQryBrokerTradingParamsField *pQryBrokerTradingParams, int nRequestID );
typedef int  (__cdecl *lpReqQryBrokerTradingAlgos) ( HKSFT hKsft, KS_::CThostFtdcQryBrokerTradingAlgosField *pQryBrokerTradingAlgos, int nRequestID );
typedef int  (__cdecl *lpReqFromBankToFutureByFuture) ( HKSFT hKsft, KS_::CThostFtdcReqTransferField *pReqTransfer, int nRequestID );
typedef int  (__cdecl *lpReqFromFutureToBankByFuture) ( HKSFT hKsft, KS_::CThostFtdcReqTransferField *pReqTransfer, int nRequestID );
typedef int  (__cdecl *lpReqQueryBankAccountMoneyByFuture) ( HKSFT hKsft, KS_::CThostFtdcReqQueryAccountField *pReqQueryAccount, int nRequestID );
typedef int  (__cdecl *lpReqQueryInvestorOpenPosition) ( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionDetailField *pQryInvestorOpenPosition, int nRequestID );
typedef int  (__cdecl *lpReqQueryInvestorOpenCombinePosition) ( HKSFT hKsft, KS_::CThostFtdcQryInvestorPositionCombineDetailField *pQryInvestorOpenCombinePosition, int nRequestID );
typedef void* (__cdecl *lpLoadExtApi) ( HKSFT hKsft, void * spi, const char *ExtApiName );
typedef int  (__cdecl *lpReqBulkCancelOrder) ( HKSFT hKsft, KS_::CThostFtdcBulkCancelOrderField *pBulkCancelOrder, int nRequestID );
//------------------------------------------------------------------------------------------------------------------------
// Define all RegOnXXXXXX register callback function functions.
//------------------------------------------------------------------------------------------------------------------------
typedef void (__cdecl *lpRegOnFrontConnected)							( HKSFT hKsft, pfOnFrontConnected callback );
typedef void (__cdecl *lpRegOnFrontDisconnected)						( HKSFT hKsft, pfOnFrontDisconnected callback );
typedef void (__cdecl *lpRegOnHeartBeatWarning)							( HKSFT hKsft, pfOnHeartBeatWarning callback );
typedef void (__cdecl *lpRegOnRspAuthenticate)							( HKSFT hKsft, pfOnRspAuthenticate callback );
typedef void (__cdecl *lpRegOnRspUserLogin)								( HKSFT hKsft, pfOnRspUserLogin callback );
typedef void (__cdecl *lpRegOnRspUserLogout)							( HKSFT hKsft, pfOnRspUserLogout callback );
typedef void (__cdecl *lpRegOnRspUserPasswordUpdate)					( HKSFT hKsft, pfOnRspUserPasswordUpdate callback );
typedef void (__cdecl *lpRegOnRspTradingAccountPasswordUpdate)			( HKSFT hKsft, pfOnRspTradingAccountPasswordUpdate callback );
typedef void (__cdecl *lpRegOnRspOrderInsert)							( HKSFT hKsft, pfOnRspOrderInsert callback );
typedef void (__cdecl *lpRegOnRspParkedOrderInsert)						( HKSFT hKsft, pfOnRspParkedOrderInsert callback );
typedef void (__cdecl *lpRegOnRspParkedOrderAction)						( HKSFT hKsft, pfOnRspParkedOrderAction callback );
typedef void (__cdecl *lpRegOnRspOrderAction)							( HKSFT hKsft, pfOnRspOrderAction callback );
typedef void (__cdecl *lpRegOnRspQueryMaxOrderVolume)					( HKSFT hKsft, pfOnRspQueryMaxOrderVolume callback );
typedef void (__cdecl *lpRegOnRspSettlementInfoConfirm)					( HKSFT hKsft, pfOnRspSettlementInfoConfirm callback );
typedef void (__cdecl *lpRegOnRspRemoveParkedOrder)						( HKSFT hKsft, pfOnRspRemoveParkedOrder callback );
typedef void (__cdecl *lpRegOnRspRemoveParkedOrderAction)				( HKSFT hKsft, pfOnRspRemoveParkedOrderAction callback );
typedef void (__cdecl *lpRegOnRspExecOrderInsert)						( HKSFT hKsft, pfOnRspExecOrderInsert callback );
typedef void (__cdecl *lpRegOnRspExecOrderAction)						( HKSFT hKsft, pfOnRspExecOrderAction callback );
typedef void (__cdecl *lpRegOnRspForQuoteInsert)						( HKSFT hKsft, pfOnRspForQuoteInsert callback );
typedef void (__cdecl *lpRegOnRspQuoteInsert)							( HKSFT hKsft, pfOnRspQuoteInsert callback );
typedef void (__cdecl *lpRegOnRspQuoteAction)							( HKSFT hKsft, pfOnRspQuoteAction callback );
typedef void (__cdecl *lpRegOnRspQryOrder)								( HKSFT hKsft, pfOnRspQryOrder callback );
typedef void (__cdecl *lpRegOnRspQryTrade)								( HKSFT hKsft, pfOnRspQryTrade callback );
typedef void (__cdecl *lpRegOnRspQryInvestorPosition)					( HKSFT hKsft, pfOnRspQryInvestorPosition callback );
typedef void (__cdecl *lpRegOnRspQryTradingAccount)						( HKSFT hKsft, pfOnRspQryTradingAccount callback );
typedef void (__cdecl *lpRegOnRspQryInvestor)							( HKSFT hKsft, pfOnRspQryInvestor callback );
typedef void (__cdecl *lpRegOnRspQryTradingCode)						( HKSFT hKsft, pfOnRspQryTradingCode callback );
typedef void (__cdecl *lpRegOnRspQryInstrumentMarginRate)				( HKSFT hKsft, pfOnRspQryInstrumentMarginRate callback );
typedef void (__cdecl *lpRegOnRspQryInstrumentCommissionRate)			( HKSFT hKsft, pfOnRspQryInstrumentCommissionRate callback );
typedef void (__cdecl *lpRegOnRspQryExchange)							( HKSFT hKsft, pfOnRspQryExchange callback );
typedef void (__cdecl *lpRegOnRspQryProduct)							( HKSFT hKsft, pfOnRspQryProduct callback );
typedef void (__cdecl *lpRegOnRspQryInstrument)							( HKSFT hKsft, pfOnRspQryInstrument callback );
typedef void (__cdecl *lpRegOnRspQryDepthMarketData)					( HKSFT hKsft, pfOnRspQryDepthMarketData callback );
typedef void (__cdecl *lpRegOnRspQrySettlementInfo)						( HKSFT hKsft, pfOnRspQrySettlementInfo callback );
typedef void (__cdecl *lpRegOnRspQryTransferBank)						( HKSFT hKsft, pfOnRspQryTransferBank callback );
typedef void (__cdecl *lpRegOnRspQryInvestorPositionDetail)				( HKSFT hKsft, pfOnRspQryInvestorPositionDetail callback );
typedef void (__cdecl *lpRegOnRspQryNotice)								( HKSFT hKsft, pfOnRspQryNotice callback );
typedef void (__cdecl *lpRegOnRspQrySettlementInfoConfirm)				( HKSFT hKsft, pfOnRspQrySettlementInfoConfirm callback );
typedef void (__cdecl *lpRegOnRspQryInvestorPositionCombineDetail)		( HKSFT hKsft, pfOnRspQryInvestorPositionCombineDetail callback );
typedef void (__cdecl *lpRegOnRspQryCFMMCTradingAccountKey)				( HKSFT hKsft, pfOnRspQryCFMMCTradingAccountKey callback );
typedef void (__cdecl *lpRegOnRspQryEWarrantOffset)						( HKSFT hKsft, pfOnRspQryEWarrantOffset callback );
typedef void (__cdecl *lpRegOnRspQryInvestorProductGroupMargin)			( HKSFT hKsft, pfOnRspQryInvestorProductGroupMargin callback );
typedef void (__cdecl *lpRegOnRspQryExchangeMarginRate)					( HKSFT hKsft, pfOnRspQryExchangeMarginRate callback );
typedef void (__cdecl *lpRegOnRspQryExchangeMarginRateAdjust)			( HKSFT hKsft, pfOnRspQryExchangeMarginRateAdjust callback );
typedef void (__cdecl *lpRegOnRspQryExchangeRate)						( HKSFT hKsft, pfOnRspQryExchangeRate callback );
typedef void (__cdecl *lpRegOnRspQrySecAgentACIDMap)					( HKSFT hKsft, pfOnRspQrySecAgentACIDMap callback );
typedef void (__cdecl *lpRegOnRspQryOptionInstrTradeCost)				( HKSFT hKsft, pfOnRspQryOptionInstrTradeCost callback );
typedef void (__cdecl *lpRegOnRspQryOptionInstrCommRate)				( HKSFT hKsft, pfOnRspQryOptionInstrCommRate callback );
typedef void (__cdecl *lpRegOnRspQryExecOrder)							( HKSFT hKsft, pfOnRspQryExecOrder callback );
typedef void (__cdecl *lpRegOnRspQryForQuote)							( HKSFT hKsft, pfOnRspQryForQuote callback );
typedef void (__cdecl *lpRegOnRspQryQuote)								( HKSFT hKsft, pfOnRspQryQuote callback );
typedef void (__cdecl *lpRegOnRspQryTransferSerial)						( HKSFT hKsft, pfOnRspQryTransferSerial callback );
typedef void (__cdecl *lpRegOnRspQryAccountregister)					( HKSFT hKsft, pfOnRspQryAccountregister callback );
typedef void (__cdecl *lpRegOnRspError)									( HKSFT hKsft, pfOnRspError callback );
typedef void (__cdecl *lpRegOnRtnOrder)									( HKSFT hKsft, pfOnRtnOrder callback );
typedef void (__cdecl *lpRegOnRtnTrade)									( HKSFT hKsft, pfOnRtnTrade callback );
typedef void (__cdecl *lpRegOnErrRtnOrderInsert)						( HKSFT hKsft, pfOnErrRtnOrderInsert callback );
typedef void (__cdecl *lpRegOnErrRtnOrderAction)						( HKSFT hKsft, pfOnErrRtnOrderAction callback );
typedef void (__cdecl *lpRegOnRtnInstrumentStatus)						( HKSFT hKsft, pfOnRtnInstrumentStatus callback );
typedef void (__cdecl *lpRegOnRtnTradingNotice)							( HKSFT hKsft, pfOnRtnTradingNotice callback );
typedef void (__cdecl *lpRegOnRtnErrorConditionalOrder)					( HKSFT hKsft, pfOnRtnErrorConditionalOrder callback );
typedef void (__cdecl *lpRegOnRtnExecOrder)								( HKSFT hKsft, pfOnRtnExecOrder callback );
typedef void (__cdecl *lpRegOnErrRtnExecOrderInsert)					( HKSFT hKsft, pfOnErrRtnExecOrderInsert callback );
typedef void (__cdecl *lpRegOnErrRtnExecOrderAction)					( HKSFT hKsft, pfOnErrRtnExecOrderAction callback );
typedef void (__cdecl *lpRegOnErrRtnForQuoteInsert)						( HKSFT hKsft, pfOnErrRtnForQuoteInsert callback );
typedef void (__cdecl *lpRegOnRtnQuote)									( HKSFT hKsft, pfOnRtnQuote callback );
typedef void (__cdecl *lpRegOnErrRtnQuoteInsert)						( HKSFT hKsft, pfOnErrRtnQuoteInsert callback );
typedef void (__cdecl *lpRegOnErrRtnQuoteAction)						( HKSFT hKsft, pfOnErrRtnQuoteAction callback );
typedef void (__cdecl *lpRegOnRspQryContractBank)						( HKSFT hKsft, pfOnRspQryContractBank callback );
typedef void (__cdecl *lpRegOnRspQryParkedOrder)						( HKSFT hKsft, pfOnRspQryParkedOrder callback );
typedef void (__cdecl *lpRegOnRspQryParkedOrderAction)					( HKSFT hKsft, pfOnRspQryParkedOrderAction callback );
typedef void (__cdecl *lpRegOnRspQryTradingNotice)						( HKSFT hKsft, pfOnRspQryTradingNotice callback );
typedef void (__cdecl *lpRegOnRspQryBrokerTradingParams)				( HKSFT hKsft, pfOnRspQryBrokerTradingParams callback );
typedef void (__cdecl *lpRegOnRspQryBrokerTradingAlgos)					( HKSFT hKsft, pfOnRspQryBrokerTradingAlgos callback );
typedef void (__cdecl *lpRegOnRtnFromBankToFutureByBank)				( HKSFT hKsft, pfOnRtnFromBankToFutureByBank callback );
typedef void (__cdecl *lpRegOnRtnFromFutureToBankByBank)				( HKSFT hKsft, pfOnRtnFromFutureToBankByBank callback );
typedef void (__cdecl *lpRegOnRtnRepealFromBankToFutureByBank)			( HKSFT hKsft, pfOnRtnRepealFromBankToFutureByBank callback );
typedef void (__cdecl *lpRegOnRtnRepealFromFutureToBankByBank)			( HKSFT hKsft, pfOnRtnRepealFromFutureToBankByBank callback );
typedef void (__cdecl *lpRegOnRtnFromBankToFutureByFuture)				( HKSFT hKsft, pfOnRtnFromBankToFutureByFuture callback );
typedef void (__cdecl *lpRegOnRtnFromFutureToBankByFuture)				( HKSFT hKsft, pfOnRtnFromFutureToBankByFuture callback );
typedef void (__cdecl *lpRegOnRtnRepealFromBankToFutureByFutureManual)	( HKSFT hKsft, pfOnRtnRepealFromBankToFutureByFutureManual callback );
typedef void (__cdecl *lpRegOnRtnRepealFromFutureToBankByFutureManual)	( HKSFT hKsft, pfOnRtnRepealFromFutureToBankByFutureManual callback );
typedef void (__cdecl *lpRegOnRtnQueryBankBalanceByFuture)				( HKSFT hKsft, pfOnRtnQueryBankBalanceByFuture callback );
typedef void (__cdecl *lpRegOnErrRtnBankToFutureByFuture)				( HKSFT hKsft, pfOnErrRtnBankToFutureByFuture callback );
typedef void (__cdecl *lpRegOnErrRtnFutureToBankByFuture)				( HKSFT hKsft, pfOnErrRtnFutureToBankByFuture callback );
typedef void (__cdecl *lpRegOnErrRtnRepealBankToFutureByFutureManual)	( HKSFT hKsft, pfOnErrRtnRepealBankToFutureByFutureManual callback );
typedef void (__cdecl *lpRegOnErrRtnRepealFutureToBankByFutureManual)	( HKSFT hKsft, pfOnErrRtnRepealFutureToBankByFutureManual callback );
typedef void (__cdecl *lpRegOnErrRtnQueryBankBalanceByFuture)			( HKSFT hKsft, pfOnErrRtnQueryBankBalanceByFuture callback );
typedef void (__cdecl *lpRegOnRtnRepealFromBankToFutureByFuture)		( HKSFT hKsft, pfOnRtnRepealFromBankToFutureByFuture callback );
typedef void (__cdecl *lpRegOnRtnRepealFromFutureToBankByFuture)		( HKSFT hKsft, pfOnRtnRepealFromFutureToBankByFuture callback );
typedef void (__cdecl *lpRegOnRspFromBankToFutureByFuture)				( HKSFT hKsft, pfOnRspFromBankToFutureByFuture callback );
typedef void (__cdecl *lpRegOnRspFromFutureToBankByFuture)				( HKSFT hKsft, pfOnRspFromFutureToBankByFuture callback );
typedef void (__cdecl *lpRegOnRspQueryBankAccountMoneyByFuture)			( HKSFT hKsft, pfOnRspQueryBankAccountMoneyByFuture callback );
typedef void (__cdecl *lpRegOnRtnOpenAccountByBank)						( HKSFT hKsft, pfOnRtnOpenAccountByBank callback );
typedef void (__cdecl *lpRegOnRtnCancelAccountByBank)					( HKSFT hKsft, pfOnRtnCancelAccountByBank callback );
typedef void (__cdecl *lpRegOnRtnChangeAccountByBank)					( HKSFT hKsft, pfOnRtnChangeAccountByBank callback );
typedef void (__cdecl *lpRegOnRspQryInvestorOpenPosition)				( HKSFT hKsft, pfOnRspQryInvestorOpenPosition callback );
typedef void (__cdecl *lpRegOnRspQryInvestorOpenCombinePosition)		( HKSFT hKsft, pfOnRspQryInvestorOpenCombinePosition callback );
typedef void (__cdecl *lpRegOnRspBulkCancelOrder)						( HKSFT hKsft, pfOnRspBulkCancelOrder callback );
//------------------------------------------------------------------------------------------------------------------------
};
//------------------------------------------------------------------------------------------------------------------------
#endif
//------------------------------------------------------------------------------------------------------------------------
