object ConnectionFrame: TConnectionFrame
  Left = 0
  Top = 0
  Width = 546
  Height = 334
  Margins.Left = 4
  Margins.Top = 4
  Margins.Right = 4
  Margins.Bottom = 4
  Align = alTop
  TabOrder = 0
  DesignSize = (
    546
    334)
  object Panel5: TPanel
    Left = 400
    Top = 39
    Width = 143
    Height = 206
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Anchors = [akLeft, akTop, akRight]
    BevelOuter = bvNone
    Color = 2311680
    ParentBackground = False
    TabOrder = 0
    object Label50: TLabel
      Left = 8
      Top = 39
      Width = 133
      Height = 25
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Caption = #26368#22823#22996#35351#27969#37327':'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clGreen
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label51: TLabel
      Left = 8
      Top = 71
      Width = 91
      Height = 25
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Caption = #22996#35351#27969#37327':'
      Color = clYellow
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clYellow
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label52: TLabel
      Left = 8
      Top = 104
      Width = 91
      Height = 25
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Caption = #22238#22577#27969#37327':'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clLime
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label53: TLabel
      Left = 8
      Top = 8
      Width = 91
      Height = 25
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Caption = #36899#32218#29376#24907':'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clGreen
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object PATSMaxTPLabel: TLabel
      Left = 151
      Top = 39
      Width = 133
      Height = 26
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taRightJustify
      AutoSize = False
      Caption = '0.0 '#31558'/'#31186
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = cl3DLight
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object PATSOrderTPLabel: TLabel
      Left = 106
      Top = 71
      Width = 178
      Height = 27
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taRightJustify
      AutoSize = False
      Caption = '0.0 '#31558'/'#31186
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = cl3DLight
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object PATSExecTPLabel: TLabel
      Left = 108
      Top = 104
      Width = 177
      Height = 26
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taRightJustify
      AutoSize = False
      Caption = '0.0 '#31558'/'#31186
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = cl3DLight
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label54: TLabel
      Left = 8
      Top = 136
      Width = 91
      Height = 25
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Caption = #32317#22996#35351#37327':'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clGreen
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object PATSOrderTotalLabel: TLabel
      Left = 151
      Top = 136
      Width = 133
      Height = 27
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taRightJustify
      AutoSize = False
      Caption = '0 '#31558
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = cl3DLight
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label56: TLabel
      Left = 8
      Top = 169
      Width = 91
      Height = 25
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Caption = #32317#22238#22577#37327':'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clGreen
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object PATSExecTotalLabel: TLabel
      Left = 151
      Top = 169
      Width = 133
      Height = 26
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taRightJustify
      AutoSize = False
      Caption = '0 '#31558
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = cl3DLight
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object PATSStateText: TStaticText
      Left = 106
      Top = 5
      Width = 178
      Height = 31
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taCenter
      AutoSize = False
      BorderStyle = sbsSunken
      Caption = #26039#32218
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = cl3DLight
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 0
      Transparent = False
    end
  end
  object PatsPerformanceGauge: TPerformanceGauge
    Left = 5
    Top = 39
    Width = 395
    Height = 206
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    DrawFill = True
    MaxValue = 3000
    BackgroundColor = 2311680
    GridColor = clGreen
    LineColor = clLime
    SecondLineColor = clYellow
  end
  object TitleStaticText: TStaticText
    Left = 6
    Top = 5
    Width = 565
    Height = 33
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    AutoSize = False
    Caption = 'Speedy PATS'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -24
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
  end
  object TimeoutTimer: TTimer
    Enabled = False
    OnTimer = TimeoutTimerTimer
    Left = 704
    Top = 176
  end
end
