// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2004/4/2 ¤U¤È 04:52:05 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\WINNT\system32\msnetobj.dll (1)
// LIBID: {8AA720BF-7468-4DA1-97DA-66D2E41B3DDA}
// LCID: 0
// Helpfile: 
// HelpString: msnetobj 1.0 Type Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\system32\stdole2.tlb)
// ************************************************************************ //
#ifndef   MSNETOBJLib_OCXH
#define   MSNETOBJLib_OCXH

#pragma option push -b -w-inl

#include <olectrls.hpp>
#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "MSNETOBJLib_TLB.h"
namespace Msnetobjlib_tlb
{

// *********************************************************************//
// HelpString: msnetobj 1.0 Type Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TRMGetLicense
// Help String      : RMGetLicense Class
// Default Interface: IRMGetLicense
// Def. Intf. Object: IRMGetLicensePtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TRMGetLicense : public Oleserver::TOleServer
{
  IRMGetLicensePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TRMGetLicense(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IRMGetLicensePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IRMGetLicensePtr intf);


  void __fastcall GetLicenseFromURL(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/)
  {
    GetDefaultInterface()->GetLicenseFromURL(bstrXMLDoc/*[in]*/, bstrURL/*[in]*/);
  }

  BSTR __fastcall GetSystemInfo(void)
  {
    return GetDefaultInterface()->GetSystemInfo();
  }

  void __fastcall StoreLicense(BSTR bstrXMLDoc/*[in]*/)
  {
    GetDefaultInterface()->StoreLicense(bstrXMLDoc/*[in]*/);
  }

  BSTR __fastcall GetDRMVersion(void)
  {
    return GetDefaultInterface()->GetDRMVersion();
  }

  BSTR __fastcall GetDRMSecurityVersion(void)
  {
    return GetDefaultInterface()->GetDRMSecurityVersion();
  }

  void __fastcall GetLicenseFromURLAsync(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/)
  {
    GetDefaultInterface()->GetLicenseFromURLAsync(bstrXMLDoc/*[in]*/, bstrURL/*[in]*/);
  }

  void __fastcall GetAsyncCallStatus(VARIANT* pvarStatus/*[in,out]*/, 
                                     VARIANT* pvarHResult/*[in,out]*/)
  {
    GetDefaultInterface()->GetAsyncCallStatus(pvarStatus/*[in,out]*/, pvarHResult/*[in,out]*/);
  }

};

};     // namespace Msnetobjlib_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Msnetobjlib_tlb;
#endif

#pragma option pop

#endif // MSNETOBJLib_OCXH
