// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2004/4/2 ¤U¤È 04:52:05 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\WINNT\system32\msnetobj.dll (1)
// LIBID: {8AA720BF-7468-4DA1-97DA-66D2E41B3DDA}
// LCID: 0
// Helpfile: 
// HelpString: msnetobj 1.0 Type Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\system32\stdole2.tlb)
// ************************************************************************ //
#ifndef   MSNETOBJLib_TLBH
#define   MSNETOBJLib_TLBH

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif


// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)    
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Msnetobjlib_tlb
{

// *********************************************************************//
// HelpString: msnetobj 1.0 Type Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLSID_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
extern __declspec (package) const GUID LIBID_MSNETOBJLib;
extern __declspec (package) const GUID IID_IRMGetLicense;
extern __declspec (package) const GUID CLSID_RMGetLicense;

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
interface DECLSPEC_UUID("{9EA69F99-F8FF-415E-8B90-35D6DFAF160E}") IRMGetLicense;
typedef TComInterface<IRMGetLicense, &IID_IRMGetLicense> IRMGetLicensePtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library                       
// (NOTE: Here we map each CoClass to its Default Interface)              
//                                                                        
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this  
// TypeLibrary. It simplifies the updating of macros when CoClass name    
// change.                                                                
// *********************************************************************//
typedef IRMGetLicense RMGetLicense;
typedef IRMGetLicensePtr RMGetLicensePtr;

#define LIBID_OF_RMGetLicense (&LIBID_MSNETOBJLib)
// *********************************************************************//
// Interface: IRMGetLicense
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {9EA69F99-F8FF-415E-8B90-35D6DFAF160E}
// *********************************************************************//
interface IRMGetLicense  : public IDispatch
{
public:
  // [-1] method GetLicenseFromURL
  virtual HRESULT STDMETHODCALLTYPE GetLicenseFromURL(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/) = 0;
  // [-1] method GetSystemInfo
  virtual HRESULT STDMETHODCALLTYPE GetSystemInfo(BSTR* pbstrXMLDoc/*[out,retval]*/) = 0;
  // [-1] method StoreLicense
  virtual HRESULT STDMETHODCALLTYPE StoreLicense(BSTR bstrXMLDoc/*[in]*/) = 0;
  // [-1] method GetDRMVersion
  virtual HRESULT STDMETHODCALLTYPE GetDRMVersion(BSTR* pbstrDRMVersion/*[out,retval]*/) = 0;
  // [-1] method GetDRMSecurityVersion
  virtual HRESULT STDMETHODCALLTYPE GetDRMSecurityVersion(BSTR* pbstrDRMSecurityVersion/*[out,retval]*/) = 0;
  // [-1] method GetLicenseFromURLAsync
  virtual HRESULT STDMETHODCALLTYPE GetLicenseFromURLAsync(BSTR bstrXMLDoc/*[in]*/, 
                                                           BSTR bstrURL/*[in]*/) = 0;
  // [-1] method GetAsyncCallStatus
  virtual HRESULT STDMETHODCALLTYPE GetAsyncCallStatus(VARIANT* pvarStatus/*[in,out]*/, 
                                                       VARIANT* pvarHResult/*[in,out]*/) = 0;

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  BSTR __fastcall GetSystemInfo(void)
  {
    BSTR pbstrXMLDoc = 0;
    OLECHECK(this->GetSystemInfo((BSTR*)&pbstrXMLDoc));
    return pbstrXMLDoc;
  }

  BSTR __fastcall GetDRMVersion(void)
  {
    BSTR pbstrDRMVersion = 0;
    OLECHECK(this->GetDRMVersion((BSTR*)&pbstrDRMVersion));
    return pbstrDRMVersion;
  }

  BSTR __fastcall GetDRMSecurityVersion(void)
  {
    BSTR pbstrDRMSecurityVersion = 0;
    OLECHECK(this->GetDRMSecurityVersion((BSTR*)&pbstrDRMSecurityVersion));
    return pbstrDRMSecurityVersion;
  }



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMIRMGetLicense
// Interface: IRMGetLicense
// *********************************************************************//
template <class T /* IRMGetLicense */ >
class TCOMIRMGetLicenseT : public TComInterface<IRMGetLicense>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMIRMGetLicenseT() {}
  TCOMIRMGetLicenseT(IRMGetLicense *intf, bool addRef = false) : TComInterface<IRMGetLicense>(intf, addRef) {}
  TCOMIRMGetLicenseT(const TCOMIRMGetLicenseT& src) : TComInterface<IRMGetLicense>(src) {}
  TCOMIRMGetLicenseT& operator=(const TCOMIRMGetLicenseT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall GetLicenseFromURL(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/);
  HRESULT         __fastcall GetSystemInfo(BSTR* pbstrXMLDoc/*[out,retval]*/);
  BSTR            __fastcall GetSystemInfo(void);
  HRESULT         __fastcall StoreLicense(BSTR bstrXMLDoc/*[in]*/);
  HRESULT         __fastcall GetDRMVersion(BSTR* pbstrDRMVersion/*[out,retval]*/);
  BSTR            __fastcall GetDRMVersion(void);
  HRESULT         __fastcall GetDRMSecurityVersion(BSTR* pbstrDRMSecurityVersion/*[out,retval]*/);
  BSTR            __fastcall GetDRMSecurityVersion(void);
  HRESULT         __fastcall GetLicenseFromURLAsync(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/);
  HRESULT         __fastcall GetAsyncCallStatus(VARIANT* pvarStatus/*[in,out]*/, 
                                                VARIANT* pvarHResult/*[in,out]*/);

};
typedef TCOMIRMGetLicenseT<IRMGetLicense> TCOMIRMGetLicense;

// *********************************************************************//
// DispIntf:  IRMGetLicense
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {9EA69F99-F8FF-415E-8B90-35D6DFAF160E}
// *********************************************************************//
template<class T>
class IRMGetLicenseDispT : public TAutoDriver<IRMGetLicense>
{
public:
  IRMGetLicenseDispT(){}

  IRMGetLicenseDispT(IRMGetLicense *pintf)
  {
    TAutoDriver<IRMGetLicense>::Bind(pintf, false);
  }

  IRMGetLicenseDispT(IRMGetLicensePtr pintf)
  {
    TAutoDriver<IRMGetLicense>::Bind(pintf, true);
  }

  IRMGetLicenseDispT& operator=(IRMGetLicense *pintf)
  {
    TAutoDriver<IRMGetLicense>::Bind(pintf, false);
    return *this;
  }

  IRMGetLicenseDispT& operator=(IRMGetLicensePtr pintf)
  {
    TAutoDriver<IRMGetLicense>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_RMGetLicense));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_RMGetLicense);
  }

  HRESULT         __fastcall GetLicenseFromURL(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/);
  HRESULT         __fastcall GetSystemInfo(BSTR* pbstrXMLDoc/*[out,retval]*/);
  BSTR            __fastcall GetSystemInfo(void);
  HRESULT         __fastcall StoreLicense(BSTR bstrXMLDoc/*[in]*/);
  HRESULT         __fastcall GetDRMVersion(BSTR* pbstrDRMVersion/*[out,retval]*/);
  BSTR            __fastcall GetDRMVersion(void);
  HRESULT         __fastcall GetDRMSecurityVersion(BSTR* pbstrDRMSecurityVersion/*[out,retval]*/);
  BSTR            __fastcall GetDRMSecurityVersion(void);
  HRESULT         __fastcall GetLicenseFromURLAsync(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/);
  HRESULT         __fastcall GetAsyncCallStatus(VARIANT* pvarStatus/*[in,out]*/, 
                                                VARIANT* pvarHResult/*[in,out]*/);

};
typedef IRMGetLicenseDispT<IRMGetLicense> IRMGetLicenseDisp;

// *********************************************************************//
// SmartIntf: TCOMIRMGetLicense
// Interface: IRMGetLicense
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMIRMGetLicenseT<T>::GetLicenseFromURL(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/)
{
  return (*this)->GetLicenseFromURL(bstrXMLDoc, bstrURL);
}

template <class T> HRESULT __fastcall
TCOMIRMGetLicenseT<T>::GetSystemInfo(BSTR* pbstrXMLDoc/*[out,retval]*/)
{
  return (*this)->GetSystemInfo(pbstrXMLDoc);
}

template <class T> BSTR __fastcall
TCOMIRMGetLicenseT<T>::GetSystemInfo(void)
{
  BSTR pbstrXMLDoc = 0;
  OLECHECK(this->GetSystemInfo((BSTR*)&pbstrXMLDoc));
  return pbstrXMLDoc;
}

template <class T> HRESULT __fastcall
TCOMIRMGetLicenseT<T>::StoreLicense(BSTR bstrXMLDoc/*[in]*/)
{
  return (*this)->StoreLicense(bstrXMLDoc);
}

template <class T> HRESULT __fastcall
TCOMIRMGetLicenseT<T>::GetDRMVersion(BSTR* pbstrDRMVersion/*[out,retval]*/)
{
  return (*this)->GetDRMVersion(pbstrDRMVersion);
}

template <class T> BSTR __fastcall
TCOMIRMGetLicenseT<T>::GetDRMVersion(void)
{
  BSTR pbstrDRMVersion = 0;
  OLECHECK(this->GetDRMVersion((BSTR*)&pbstrDRMVersion));
  return pbstrDRMVersion;
}

template <class T> HRESULT __fastcall
TCOMIRMGetLicenseT<T>::GetDRMSecurityVersion(BSTR* pbstrDRMSecurityVersion/*[out,retval]*/)
{
  return (*this)->GetDRMSecurityVersion(pbstrDRMSecurityVersion);
}

template <class T> BSTR __fastcall
TCOMIRMGetLicenseT<T>::GetDRMSecurityVersion(void)
{
  BSTR pbstrDRMSecurityVersion = 0;
  OLECHECK(this->GetDRMSecurityVersion((BSTR*)&pbstrDRMSecurityVersion));
  return pbstrDRMSecurityVersion;
}

template <class T> HRESULT __fastcall
TCOMIRMGetLicenseT<T>::GetLicenseFromURLAsync(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/)
{
  return (*this)->GetLicenseFromURLAsync(bstrXMLDoc, bstrURL);
}

template <class T> HRESULT __fastcall
TCOMIRMGetLicenseT<T>::GetAsyncCallStatus(VARIANT* pvarStatus/*[in,out]*/, 
                                          VARIANT* pvarHResult/*[in,out]*/)
{
  return (*this)->GetAsyncCallStatus(pvarStatus, pvarHResult);
}

// *********************************************************************//
// DispIntf:  IRMGetLicense
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {9EA69F99-F8FF-415E-8B90-35D6DFAF160E}
// *********************************************************************//
template <class T> HRESULT __fastcall
IRMGetLicenseDispT<T>::GetLicenseFromURL(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetLicenseFromURL"), DISPID(DISPID_UNKNOWN/*[1610743808]*/));
  TAutoArgs<2> _args;
  _args[1] = bstrXMLDoc /*[VT_BSTR:0]*/;
  _args[2] = bstrURL /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IRMGetLicenseDispT<T>::GetSystemInfo(BSTR* pbstrXMLDoc/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetSystemInfo"), DISPID(DISPID_UNKNOWN/*[1610743809]*/));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(pbstrXMLDoc /*[VT_BSTR:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> BSTR __fastcall
IRMGetLicenseDispT<T>::GetSystemInfo(void)
{
  BSTR pbstrXMLDoc;
  this->GetSystemInfo((BSTR*)&pbstrXMLDoc);
  return pbstrXMLDoc;
}

template <class T> HRESULT __fastcall
IRMGetLicenseDispT<T>::StoreLicense(BSTR bstrXMLDoc/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("StoreLicense"), DISPID(DISPID_UNKNOWN/*[1610743810]*/));
  TAutoArgs<1> _args;
  _args[1] = bstrXMLDoc /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IRMGetLicenseDispT<T>::GetDRMVersion(BSTR* pbstrDRMVersion/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetDRMVersion"), DISPID(DISPID_UNKNOWN/*[1610743811]*/));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(pbstrDRMVersion /*[VT_BSTR:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> BSTR __fastcall
IRMGetLicenseDispT<T>::GetDRMVersion(void)
{
  BSTR pbstrDRMVersion;
  this->GetDRMVersion((BSTR*)&pbstrDRMVersion);
  return pbstrDRMVersion;
}

template <class T> HRESULT __fastcall
IRMGetLicenseDispT<T>::GetDRMSecurityVersion(BSTR* pbstrDRMSecurityVersion/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetDRMSecurityVersion"), DISPID(DISPID_UNKNOWN/*[1610743812]*/));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(pbstrDRMSecurityVersion /*[VT_BSTR:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> BSTR __fastcall
IRMGetLicenseDispT<T>::GetDRMSecurityVersion(void)
{
  BSTR pbstrDRMSecurityVersion;
  this->GetDRMSecurityVersion((BSTR*)&pbstrDRMSecurityVersion);
  return pbstrDRMSecurityVersion;
}

template <class T> HRESULT __fastcall
IRMGetLicenseDispT<T>::GetLicenseFromURLAsync(BSTR bstrXMLDoc/*[in]*/, BSTR bstrURL/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetLicenseFromURLAsync"), DISPID(DISPID_UNKNOWN/*[1610743813]*/));
  TAutoArgs<2> _args;
  _args[1] = bstrXMLDoc /*[VT_BSTR:0]*/;
  _args[2] = bstrURL /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IRMGetLicenseDispT<T>::GetAsyncCallStatus(VARIANT* pvarStatus/*[in,out]*/, 
                                          VARIANT* pvarHResult/*[in,out]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetAsyncCallStatus"), DISPID(DISPID_UNKNOWN/*[1610743814]*/));
  TAutoArgs<2> _args;
  _args[1] = pvarStatus /*[VT_VARIANT:1]*/;
  _args[2] = pvarHResult /*[VT_VARIANT:1]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that       
// provide static Create() and CreateRemote(LPWSTR machineName) methods   
// for creating an instance of an exposed object. These functions can     
// be used by client wishing to automate CoClasses exposed by this        
// typelibrary.                                                           
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : RMGetLicense
// Interface: TCOMIRMGetLicense
// *********************************************************************//
typedef TCoClassCreatorT<TCOMIRMGetLicense, IRMGetLicense, &CLSID_RMGetLicense, &IID_IRMGetLicense> CoRMGetLicense;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


};     // namespace Msnetobjlib_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Msnetobjlib_tlb;
#endif

#pragma option pop

#endif // MSNETOBJLib_TLBH
