// ************************************************************************ //
// WARNING
// -------
// The types declared in this file were generated from data read from a
// Type Library. If this type library is explicitly or indirectly (via
// another type library referring to this type library) re-imported, or the
// 'Refresh' command of the Type Library Editor activated while editing the
// Type Library, the contents of this file will be regenerated and all
// manual modifications will be lost.
// ************************************************************************ //

// $Rev: 52393 $
// File generated on 2016/6/4 ¤W¤È 12:23:58 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\src\COM\MBusCOMAPI\MBusAPI (1)
// LIBID: {80657B39-789C-44B3-B6FD-7B1E0EEA8DCE}
// LCID: 0
// Helpfile:
// HelpString: MBusAPI COM API
// DepndLst:
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
// SYS_KIND: SYS_WIN32
// ************************************************************************ //
#ifndef   MBusAPI_TLBH
#define   MBusAPI_TLBH

#pragma option push -b -a4 -w-inl -w-8118

#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif

#include <StdVCL.hpp>

typedef TComInterface<System::Win::Stdvcl::IStrings> IStringsPtr;
typedef TComInterface<System::Win::Stdvcl::IStringsDisp> IStringsDispPtr;

namespace Mbusapi_tlb
{

// *********************************************************************//
// HelpString: MBusAPI COM API
// Version:    2.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:
//   Type Libraries     : LIBID_xxxx
//   CoClasses          : CLSID_xxxx
//   DISPInterfaces     : DIID_xxxx
//   Non-DISP interfaces: IID_xxxx
// *********************************************************************//
extern __declspec (package) const GUID LIBID_MBusAPI;
extern __declspec (package) const GUID IID_IMdTransport;
extern __declspec (package) const GUID DIID_IMdTransportEvents;
extern __declspec (package) const GUID CLSID_MdTransport;
extern __declspec (package) const GUID IID_IMdMessage;
extern __declspec (package) const GUID CLSID_MdMessage;
extern __declspec (package) const GUID IID_IMdListener;
extern __declspec (package) const GUID DIID_IMdListenerEvents;
extern __declspec (package) const GUID CLSID_MdListener;
extern __declspec (package) const GUID GUID_ProcessStatusEnum;
extern __declspec (package) const GUID GUID_DataTypeEnum;

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary
// *********************************************************************//
enum class    ProcessStatusEnum;
enum class    DataTypeEnum;
interface DECLSPEC_UUID("{5CA7595B-B4F6-49D7-891A-97081AF24A84}") IMdTransport;
typedef TComInterface<IMdTransport, &IID_IMdTransport> IMdTransportPtr;

interface DECLSPEC_UUID("{6690CD53-07CE-46C2-BAD4-9B61418E9AC6}") IMdTransportEvents;
typedef TComInterface<IMdTransportEvents, &DIID_IMdTransportEvents> IMdTransportEventsPtr;

interface DECLSPEC_UUID("{8B002554-D036-4782-BA8A-95F4A7A03ADE}") IMdMessage;
typedef TComInterface<IMdMessage, &IID_IMdMessage> IMdMessagePtr;

interface DECLSPEC_UUID("{05D6B349-66FB-4FFF-9DDD-338670AC443B}") IMdListener;
typedef TComInterface<IMdListener, &IID_IMdListener> IMdListenerPtr;

interface DECLSPEC_UUID("{73696846-D471-4A49-9D07-FB799406C3B3}") IMdListenerEvents;
typedef TComInterface<IMdListenerEvents, &DIID_IMdListenerEvents> IMdListenerEventsPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library
// (NOTE: Here we map each CoClass to its Default Interface)
//
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this
// TypeLibrary. It simplifies the updating of macros when CoClass name
// change.
// *********************************************************************//
typedef IMdTransport MdTransport;
typedef IMdTransportPtr MdTransportPtr;
typedef IMdMessage MdMessage;
typedef IMdMessagePtr MdMessagePtr;
typedef IMdListener MdListener;
typedef IMdListenerPtr MdListenerPtr;

#define LIBID_OF_MdTransport (&LIBID_MBusAPI)
#define LIBID_OF_MdMessage (&LIBID_MBusAPI)
#define LIBID_OF_MdListener (&LIBID_MBusAPI)

// *********************************************************************//
// Declaration of Enumerations defined in Type Library
// *********************************************************************//
enum class ProcessStatusEnum
{
  psFirstTime = 0,
  psAlreadyExists = 1
};

enum class DataTypeEnum
{
  dtString = 0,
  dtInteger = 1,
  dtDouble = 2,
  dtRowData = 3,
  dtUnknown = 4
};

// *********************************************************************//
// Interface: IMdTransport
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {5CA7595B-B4F6-49D7-891A-97081AF24A84}
// *********************************************************************//
interface IMdTransport  : public IDispatch
{
public:
  virtual HRESULT STDMETHODCALLTYPE Create(BSTR Vendor/*[in]*/, BSTR Name/*[in]*/, BSTR IP/*[in]*/,
                                           long Port/*[in]*/, VARIANT_BOOL IsGUIApp/*[in]*/) = 0; // [201]
  virtual HRESULT STDMETHODCALLTYPE Destroy(void) = 0; // [202]
  virtual HRESULT STDMETHODCALLTYPE Connect(long Timeout/*[in]*/) = 0; // [203]
  virtual HRESULT STDMETHODCALLTYPE Disconnect(void) = 0; // [204]
  virtual HRESULT STDMETHODCALLTYPE Send(BSTR Subject/*[in]*/, BSTR Key/*[in]*/,
                                         Mbusapi_tlb::IMdMessage* Msg/*[in]*/) = 0; // [205]
  virtual HRESULT STDMETHODCALLTYPE IsConnected(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [206]
  virtual HRESULT STDMETHODCALLTYPE IsValid(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [207]
  virtual HRESULT STDMETHODCALLTYPE GetTransportInstance(VARIANT* Value/*[out,retval]*/) = 0; // [208]
  virtual HRESULT STDMETHODCALLTYPE get_AppName(BSTR* Value/*[out,retval]*/) = 0; // [209]
  virtual HRESULT STDMETHODCALLTYPE get_Host(BSTR* Value/*[out,retval]*/) = 0; // [210]
  virtual HRESULT STDMETHODCALLTYPE get_Port(long* Value/*[out,retval]*/) = 0; // [211]
  virtual HRESULT STDMETHODCALLTYPE get_LocalHostname(BSTR* Value/*[out,retval]*/) = 0; // [212]
  virtual HRESULT STDMETHODCALLTYPE get_LocalIPAddress(BSTR* Value/*[out,retval]*/) = 0; // [213]
  virtual HRESULT STDMETHODCALLTYPE get_SocketFD(long* Value/*[out,retval]*/) = 0; // [214]
  virtual HRESULT STDMETHODCALLTYPE AddMonitoringProcess(BSTR Host/*[in]*/, BSTR AppName/*[in]*/) = 0; // [215]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  VARIANT_BOOL __fastcall IsConnected(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->IsConnected((VARIANT_BOOL*)&Value));
    return Value;
  }

  VARIANT_BOOL __fastcall IsValid(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->IsValid((VARIANT_BOOL*)&Value));
    return Value;
  }

  VARIANT __fastcall GetTransportInstance(void)
  {
    VARIANT Value;
    OLECHECK(this->GetTransportInstance((VARIANT*)&Value));
    return Value;
  }

  BSTR __fastcall get_AppName(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_AppName((BSTR*)&Value));
    return Value;
  }

  BSTR __fastcall get_Host(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_Host((BSTR*)&Value));
    return Value;
  }

  long __fastcall get_Port(void)
  {
    long Value;
    OLECHECK(this->get_Port((long*)&Value));
    return Value;
  }

  BSTR __fastcall get_LocalHostname(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_LocalHostname((BSTR*)&Value));
    return Value;
  }

  BSTR __fastcall get_LocalIPAddress(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_LocalIPAddress((BSTR*)&Value));
    return Value;
  }

  long __fastcall get_SocketFD(void)
  {
    long Value;
    OLECHECK(this->get_SocketFD((long*)&Value));
    return Value;
  }


  __property   BSTR            AppName = {read = get_AppName};
  __property   BSTR            Host = {read = get_Host};
  __property   long            Port = {read = get_Port};
  __property   BSTR            LocalHostname = {read = get_LocalHostname};
  __property   BSTR            LocalIPAddress = {read = get_LocalIPAddress};
  __property   long            SocketFD = {read = get_SocketFD};

#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

// *********************************************************************//
// Interface: IMdTransportEvents
// Flags:     (0)
// GUID:      {6690CD53-07CE-46C2-BAD4-9B61418E9AC6}
// *********************************************************************//
interface IMdTransportEvents : public TDispWrapper<IDispatch>
{
  HRESULT __fastcall OnConnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/)
  {
    _TDispID _dispid(/* OnConnected */ DISPID(201));
    TAutoArgs<1> _args;
    _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
    return OleFunction(_dispid, _args);
  }

  HRESULT __fastcall OnDisconnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/)
  {
    _TDispID _dispid(/* OnDisconnected */ DISPID(202));
    TAutoArgs<1> _args;
    _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
    return OleFunction(_dispid, _args);
  }

  HRESULT __fastcall OnError(Mbusapi_tlb::IMdTransport* Transport/*[in]*/, BSTR ErrorMessage/*[in]*/)
  {
    _TDispID _dispid(/* OnError */ DISPID(203));
    TAutoArgs<2> _args;
    _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
    _args[2] = ErrorMessage /*[VT_BSTR:0]*/;
    return OleFunction(_dispid, _args);
  }

  HRESULT __fastcall OnProcessConnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                        Mbusapi_tlb::ProcessStatusEnum IsTheFirstOne/*[in]*/)
  {
    _TDispID _dispid(/* OnProcessConnected */ DISPID(204));
    TAutoArgs<2> _args;
    _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
    _args[2] = (int)IsTheFirstOne /*[VT_USERDEFINED:0]*/;
    return OleFunction(_dispid, _args);
  }

  HRESULT __fastcall OnProcessStartup(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                      BSTR Host/*[in]*/, BSTR AppName/*[in]*/)
  {
    _TDispID _dispid(/* OnProcessStartup */ DISPID(205));
    TAutoArgs<3> _args;
    _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
    _args[2] = Host /*[VT_BSTR:0]*/;
    _args[3] = AppName /*[VT_BSTR:0]*/;
    return OleFunction(_dispid, _args);
  }

  HRESULT __fastcall OnProcessStopped(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                      BSTR Host/*[in]*/, BSTR AppName/*[in]*/)
  {
    _TDispID _dispid(/* OnProcessStopped */ DISPID(206));
    TAutoArgs<3> _args;
    _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
    _args[2] = Host /*[VT_BSTR:0]*/;
    _args[3] = AppName /*[VT_BSTR:0]*/;
    return OleFunction(_dispid, _args);
  }


};
// *********************************************************************//
// Interface: IMdMessage
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {8B002554-D036-4782-BA8A-95F4A7A03ADE}
// *********************************************************************//
interface IMdMessage  : public IDispatch
{
public:
  virtual HRESULT STDMETHODCALLTYPE Create(void) = 0; // [201]
  virtual HRESULT STDMETHODCALLTYPE Destroy(void) = 0; // [202]
  virtual HRESULT STDMETHODCALLTYPE Attach(VARIANT* Instance/*[in]*/) = 0; // [203]
  virtual HRESULT STDMETHODCALLTYPE GetMessageInstance(VARIANT* Value/*[out]*/) = 0; // [204]
  virtual HRESULT STDMETHODCALLTYPE IsValid(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [205]
  virtual HRESULT STDMETHODCALLTYPE GetField(BSTR FieldName/*[in]*/, VARIANT* Value/*[out,retval]*/) = 0; // [206]
  virtual HRESULT STDMETHODCALLTYPE SetField(BSTR FieldName/*[in]*/, VARIANT FieldValue/*[in]*/) = 0; // [207]
  virtual HRESULT STDMETHODCALLTYPE GetStringValue(BSTR FieldName/*[in]*/,
                                                   BSTR* Value/*[out,retval]*/) = 0; // [208]
  virtual HRESULT STDMETHODCALLTYPE SetStringValue(BSTR FieldName/*[in]*/, BSTR FieldValue/*[in]*/) = 0; // [209]
  virtual HRESULT STDMETHODCALLTYPE GetIntegerValue(BSTR FieldName/*[in]*/,
                                                    long DefaultValue/*[in]*/,
                                                    long* Value/*[out,retval]*/) = 0; // [210]
  virtual HRESULT STDMETHODCALLTYPE SetIntegerValue(BSTR FieldName/*[in]*/, long FieldValue/*[in]*/) = 0; // [211]
  virtual HRESULT STDMETHODCALLTYPE GetDoubleValue(BSTR FieldName/*[in]*/,
                                                   double DefaultValue/*[in]*/,
                                                   double* Value/*[out,retval]*/) = 0; // [212]
  virtual HRESULT STDMETHODCALLTYPE SetDoubleValue(BSTR FieldName/*[in]*/, double FieldValue/*[in]*/) = 0; // [213]
  virtual HRESULT STDMETHODCALLTYPE GetFieldCount(long* Value/*[out,retval]*/) = 0; // [214]
  virtual HRESULT STDMETHODCALLTYPE GetName(long Index/*[in]*/, BSTR* Name/*[out,retval]*/) = 0; // [215]
  virtual HRESULT STDMETHODCALLTYPE GetValue(long Index/*[in]*/, VARIANT* Value/*[out,retval]*/) = 0; // [216]
  virtual HRESULT STDMETHODCALLTYPE GetType(long Index/*[in]*/,
                                            Mbusapi_tlb::DataTypeEnum* Type/*[out,retval]*/) = 0; // [217]
  virtual HRESULT STDMETHODCALLTYPE GetBytesValue(BSTR FieldName/*[in]*/,
                                                  VARIANT* FieldValue/*[out]*/) = 0; // [218]
  virtual HRESULT STDMETHODCALLTYPE SetBytesValue(BSTR FieldName/*[in]*/, VARIANT Value/*[in]*/,
                                                  VARIANT_BOOL Compress/*[in]*/) = 0; // [219]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  VARIANT_BOOL __fastcall IsValid(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->IsValid((VARIANT_BOOL*)&Value));
    return Value;
  }

  VARIANT __fastcall GetField(BSTR FieldName/*[in]*/)
  {
    VARIANT Value;
    OLECHECK(this->GetField(FieldName, (VARIANT*)&Value));
    return Value;
  }

  BSTR __fastcall GetStringValue(BSTR FieldName/*[in]*/)
  {
    BSTR Value = 0;
    OLECHECK(this->GetStringValue(FieldName, (BSTR*)&Value));
    return Value;
  }

  long __fastcall GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/)
  {
    long Value;
    OLECHECK(this->GetIntegerValue(FieldName, DefaultValue, (long*)&Value));
    return Value;
  }

  double __fastcall GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/)
  {
    double Value;
    OLECHECK(this->GetDoubleValue(FieldName, DefaultValue, (double*)&Value));
    return Value;
  }

  long __fastcall GetFieldCount(void)
  {
    long Value;
    OLECHECK(this->GetFieldCount((long*)&Value));
    return Value;
  }

  BSTR __fastcall GetName(long Index/*[in]*/)
  {
    BSTR Name = 0;
    OLECHECK(this->GetName(Index, (BSTR*)&Name));
    return Name;
  }

  VARIANT __fastcall GetValue(long Index/*[in]*/)
  {
    VARIANT Value;
    OLECHECK(this->GetValue(Index, (VARIANT*)&Value));
    return Value;
  }

  Mbusapi_tlb::DataTypeEnum __fastcall GetType(long Index/*[in]*/)
  {
    Mbusapi_tlb::DataTypeEnum Type;
    OLECHECK(this->GetType(Index, (Mbusapi_tlb::DataTypeEnum*)&Type));
    return Type;
  }



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

// *********************************************************************//
// Interface: IMdListener
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {05D6B349-66FB-4FFF-9DDD-338670AC443B}
// *********************************************************************//
interface IMdListener  : public IDispatch
{
public:
  virtual HRESULT STDMETHODCALLTYPE Create(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                           BSTR Subject/*[in]*/, BSTR Key/*[in]*/) = 0; // [201]
  virtual HRESULT STDMETHODCALLTYPE Destroy(void) = 0; // [202]
  virtual HRESULT STDMETHODCALLTYPE IsValid(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [203]
  virtual HRESULT STDMETHODCALLTYPE get_Subject(BSTR* Value/*[out,retval]*/) = 0; // [204]
  virtual HRESULT STDMETHODCALLTYPE set_Subject(BSTR Value/*[in]*/) = 0; // [204]
  virtual HRESULT STDMETHODCALLTYPE get_Key(BSTR* Value/*[out,retval]*/) = 0; // [205]
  virtual HRESULT STDMETHODCALLTYPE set_Key(BSTR Value/*[in]*/) = 0; // [205]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  VARIANT_BOOL __fastcall IsValid(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->IsValid((VARIANT_BOOL*)&Value));
    return Value;
  }

  BSTR __fastcall get_Subject(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_Subject((BSTR*)&Value));
    return Value;
  }

  BSTR __fastcall get_Key(void)
  {
    BSTR Value = 0;
    OLECHECK(this->get_Key((BSTR*)&Value));
    return Value;
  }


  __property   BSTR            Subject = {read = get_Subject, write = set_Subject};
  __property   BSTR            Key = {read = get_Key, write = set_Key};

#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

// *********************************************************************//
// Interface: IMdListenerEvents
// Flags:     (0)
// GUID:      {73696846-D471-4A49-9D07-FB799406C3B3}
// *********************************************************************//
interface IMdListenerEvents : public TDispWrapper<IDispatch>
{
  HRESULT __fastcall OnMessageReceived(BSTR Subject/*[in]*/, BSTR Key/*[in]*/,
                                       Mbusapi_tlb::IMdMessage* Msg/*[in]*/)
  {
    _TDispID _dispid(/* OnMessageReceived */ DISPID(201));
    TAutoArgs<3> _args;
    _args[1] = Subject /*[VT_BSTR:0]*/;
    _args[2] = Key /*[VT_BSTR:0]*/;
    _args[3] = (LPDISPATCH)(Mbusapi_tlb::IMdMessage*)Msg /*[VT_USERDEFINED:1]*/;
    return OleFunction(_dispid, _args);
  }


};
#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMIMdTransport
// Interface: IMdTransport
// *********************************************************************//
template <class T /* IMdTransport */ >
class TCOMIMdTransportT : public TComInterface<IMdTransport>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMIMdTransportT() {}
  TCOMIMdTransportT(IMdTransport *intf, bool addRef = false) : TComInterface<IMdTransport>(intf, addRef) {}
  TCOMIMdTransportT(const TCOMIMdTransportT& src) : TComInterface<IMdTransport>(src) {}
  TCOMIMdTransportT& operator=(const TCOMIMdTransportT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall Create(BSTR Vendor/*[in]*/, BSTR Name/*[in]*/, BSTR IP/*[in]*/,
                                    long Port/*[in]*/, VARIANT_BOOL IsGUIApp/*[in]*/);
  HRESULT         __fastcall Destroy(void);
  HRESULT         __fastcall Connect(long Timeout/*[in]*/);
  HRESULT         __fastcall Disconnect(void);
  HRESULT         __fastcall Send(BSTR Subject/*[in]*/, BSTR Key/*[in]*/,
                                  Mbusapi_tlb::IMdMessage* Msg/*[in]*/);
  HRESULT         __fastcall IsConnected(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall IsConnected(void);
  HRESULT         __fastcall IsValid(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall IsValid(void);
  HRESULT         __fastcall GetTransportInstance(VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall GetTransportInstance(void);
  HRESULT         __fastcall get_AppName(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_AppName(void);
  HRESULT         __fastcall get_Host(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_Host(void);
  HRESULT         __fastcall get_Port(long* Value/*[out,retval]*/);
  long            __fastcall get_Port(void);
  HRESULT         __fastcall get_LocalHostname(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_LocalHostname(void);
  HRESULT         __fastcall get_LocalIPAddress(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_LocalIPAddress(void);
  HRESULT         __fastcall get_SocketFD(long* Value/*[out,retval]*/);
  long            __fastcall get_SocketFD(void);
  HRESULT         __fastcall AddMonitoringProcess(BSTR Host/*[in]*/, BSTR AppName/*[in]*/);

  __property   BSTR            AppName = {read = get_AppName};
  __property   BSTR            Host = {read = get_Host};
  __property   long            Port = {read = get_Port};
  __property   BSTR            LocalHostname = {read = get_LocalHostname};
  __property   BSTR            LocalIPAddress = {read = get_LocalIPAddress};
  __property   long            SocketFD = {read = get_SocketFD};
};
typedef TCOMIMdTransportT<IMdTransport> TCOMIMdTransport;

// *********************************************************************//
// DispIntf:  IMdTransport
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {5CA7595B-B4F6-49D7-891A-97081AF24A84}
// *********************************************************************//
template<class T>
class IMdTransportDispT : public TAutoDriver<IMdTransport>
{
public:
  IMdTransportDispT(){}

  IMdTransportDispT(IMdTransport *pintf)
  {
    TAutoDriver<IMdTransport>::Bind(pintf, false);
  }

  IMdTransportDispT(IMdTransportPtr pintf)
  {
    TAutoDriver<IMdTransport>::Bind(pintf, true);
  }

  IMdTransportDispT& operator=(IMdTransport *pintf)
  {
    TAutoDriver<IMdTransport>::Bind(pintf, false);
    return *this;
  }

  IMdTransportDispT& operator=(IMdTransportPtr pintf)
  {
    TAutoDriver<IMdTransport>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_MdTransport));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_MdTransport);
  }

  HRESULT         __fastcall Create(BSTR Vendor/*[in]*/, BSTR Name/*[in]*/, BSTR IP/*[in]*/,
                                    long Port/*[in]*/, VARIANT_BOOL IsGUIApp/*[in]*/);
  HRESULT         __fastcall Destroy();
  HRESULT         __fastcall Connect(long Timeout/*[in]*/);
  HRESULT         __fastcall Disconnect();
  HRESULT         __fastcall Send(BSTR Subject/*[in]*/, BSTR Key/*[in]*/,
                                  Mbusapi_tlb::IMdMessage* Msg/*[in]*/);
  HRESULT         __fastcall IsConnected(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall IsConnected(void);
  HRESULT         __fastcall IsValid(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall IsValid(void);
  HRESULT         __fastcall GetTransportInstance(VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall GetTransportInstance(void);
  HRESULT         __fastcall get_AppName(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_AppName(void);
  HRESULT         __fastcall get_Host(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_Host(void);
  HRESULT         __fastcall get_Port(long* Value/*[out,retval]*/);
  long            __fastcall get_Port(void);
  HRESULT         __fastcall get_LocalHostname(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_LocalHostname(void);
  HRESULT         __fastcall get_LocalIPAddress(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_LocalIPAddress(void);
  HRESULT         __fastcall get_SocketFD(long* Value/*[out,retval]*/);
  long            __fastcall get_SocketFD(void);
  HRESULT         __fastcall AddMonitoringProcess(BSTR Host/*[in]*/, BSTR AppName/*[in]*/);

  __property   BSTR            AppName = {read = get_AppName};
  __property   BSTR            Host = {read = get_Host};
  __property   long            Port = {read = get_Port};
  __property   BSTR            LocalHostname = {read = get_LocalHostname};
  __property   BSTR            LocalIPAddress = {read = get_LocalIPAddress};
  __property   long            SocketFD = {read = get_SocketFD};
};
typedef IMdTransportDispT<IMdTransport> IMdTransportDisp;

// *********************************************************************//
// DispIntf:  IMdTransportEvents
// Flags:     (0)
// GUID:      {6690CD53-07CE-46C2-BAD4-9B61418E9AC6}
// *********************************************************************//
template <class T>
class IMdTransportEventsDispT : public TAutoDriver<IMdTransportEvents>
{
public:
  IMdTransportEventsDispT(){}

  void Attach(LPUNKNOWN punk)
  { m_Dispatch = static_cast<T*>(punk); }

  HRESULT         __fastcall OnConnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/);
  HRESULT         __fastcall OnDisconnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/);
  HRESULT         __fastcall OnError(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                     BSTR ErrorMessage/*[in]*/);
  HRESULT         __fastcall OnProcessConnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                                Mbusapi_tlb::ProcessStatusEnum IsTheFirstOne/*[in]*/);
  HRESULT         __fastcall OnProcessStartup(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                              BSTR Host/*[in]*/, BSTR AppName/*[in]*/);
  HRESULT         __fastcall OnProcessStopped(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                              BSTR Host/*[in]*/, BSTR AppName/*[in]*/);

};
typedef IMdTransportEventsDispT<IMdTransportEvents> IMdTransportEventsDisp;

// *********************************************************************//
// SmartIntf: TCOMIMdMessage
// Interface: IMdMessage
// *********************************************************************//
template <class T /* IMdMessage */ >
class TCOMIMdMessageT : public TComInterface<IMdMessage>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMIMdMessageT() {}
  TCOMIMdMessageT(IMdMessage *intf, bool addRef = false) : TComInterface<IMdMessage>(intf, addRef) {}
  TCOMIMdMessageT(const TCOMIMdMessageT& src) : TComInterface<IMdMessage>(src) {}
  TCOMIMdMessageT& operator=(const TCOMIMdMessageT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall Create(void);
  HRESULT         __fastcall Destroy(void);
  HRESULT         __fastcall Attach(VARIANT* Instance/*[in]*/);
  HRESULT         __fastcall GetMessageInstance(VARIANT* Value/*[out]*/);
  HRESULT         __fastcall IsValid(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall IsValid(void);
  HRESULT         __fastcall GetField(BSTR FieldName/*[in]*/, VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall GetField(BSTR FieldName/*[in]*/);
  HRESULT         __fastcall SetField(BSTR FieldName/*[in]*/, VARIANT FieldValue/*[in]*/);
  HRESULT         __fastcall GetStringValue(BSTR FieldName/*[in]*/, BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall GetStringValue(BSTR FieldName/*[in]*/);
  HRESULT         __fastcall SetStringValue(BSTR FieldName/*[in]*/, BSTR FieldValue/*[in]*/);
  HRESULT         __fastcall GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/,
                                             long* Value/*[out,retval]*/);
  long            __fastcall GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/);
  HRESULT         __fastcall SetIntegerValue(BSTR FieldName/*[in]*/, long FieldValue/*[in]*/);
  HRESULT         __fastcall GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/,
                                            double* Value/*[out,retval]*/);
  double          __fastcall GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/);
  HRESULT         __fastcall SetDoubleValue(BSTR FieldName/*[in]*/, double FieldValue/*[in]*/);
  HRESULT         __fastcall GetFieldCount(long* Value/*[out,retval]*/);
  long            __fastcall GetFieldCount(void);
  HRESULT         __fastcall GetName(long Index/*[in]*/, BSTR* Name/*[out,retval]*/);
  BSTR            __fastcall GetName(long Index/*[in]*/);
  HRESULT         __fastcall GetValue(long Index/*[in]*/, VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall GetValue(long Index/*[in]*/);
  HRESULT         __fastcall GetType(long Index/*[in]*/,
                                     Mbusapi_tlb::DataTypeEnum* Type/*[out,retval]*/);
  Mbusapi_tlb::DataTypeEnum __fastcall GetType(long Index/*[in]*/);
  HRESULT         __fastcall GetBytesValue(BSTR FieldName/*[in]*/, VARIANT* FieldValue/*[out]*/);
  HRESULT         __fastcall SetBytesValue(BSTR FieldName/*[in]*/, VARIANT Value/*[in]*/,
                                           VARIANT_BOOL Compress/*[in]*/);

};
typedef TCOMIMdMessageT<IMdMessage> TCOMIMdMessage;

// *********************************************************************//
// DispIntf:  IMdMessage
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {8B002554-D036-4782-BA8A-95F4A7A03ADE}
// *********************************************************************//
template<class T>
class IMdMessageDispT : public TAutoDriver<IMdMessage>
{
public:
  IMdMessageDispT(){}

  IMdMessageDispT(IMdMessage *pintf)
  {
    TAutoDriver<IMdMessage>::Bind(pintf, false);
  }

  IMdMessageDispT(IMdMessagePtr pintf)
  {
    TAutoDriver<IMdMessage>::Bind(pintf, true);
  }

  IMdMessageDispT& operator=(IMdMessage *pintf)
  {
    TAutoDriver<IMdMessage>::Bind(pintf, false);
    return *this;
  }

  IMdMessageDispT& operator=(IMdMessagePtr pintf)
  {
    TAutoDriver<IMdMessage>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_MdMessage));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_MdMessage);
  }

  HRESULT         __fastcall Create();
  HRESULT         __fastcall Destroy();
  HRESULT         __fastcall Attach(VARIANT* Instance/*[in]*/);
  HRESULT         __fastcall GetMessageInstance(VARIANT* Value/*[out]*/);
  HRESULT         __fastcall IsValid(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall IsValid(void);
  HRESULT         __fastcall GetField(BSTR FieldName/*[in]*/, VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall GetField(BSTR FieldName/*[in]*/);
  HRESULT         __fastcall SetField(BSTR FieldName/*[in]*/, VARIANT FieldValue/*[in]*/);
  HRESULT         __fastcall GetStringValue(BSTR FieldName/*[in]*/, BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall GetStringValue(BSTR FieldName/*[in]*/);
  HRESULT         __fastcall SetStringValue(BSTR FieldName/*[in]*/, BSTR FieldValue/*[in]*/);
  HRESULT         __fastcall GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/,
                                             long* Value/*[out,retval]*/);
  long            __fastcall GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/);
  HRESULT         __fastcall SetIntegerValue(BSTR FieldName/*[in]*/, long FieldValue/*[in]*/);
  HRESULT         __fastcall GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/,
                                            double* Value/*[out,retval]*/);
  double          __fastcall GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/);
  HRESULT         __fastcall SetDoubleValue(BSTR FieldName/*[in]*/, double FieldValue/*[in]*/);
  HRESULT         __fastcall GetFieldCount(long* Value/*[out,retval]*/);
  long            __fastcall GetFieldCount(void);
  HRESULT         __fastcall GetName(long Index/*[in]*/, BSTR* Name/*[out,retval]*/);
  BSTR            __fastcall GetName(long Index/*[in]*/);
  HRESULT         __fastcall GetValue(long Index/*[in]*/, VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall GetValue(long Index/*[in]*/);
  HRESULT         __fastcall GetType(long Index/*[in]*/,
                                     Mbusapi_tlb::DataTypeEnum* Type/*[out,retval]*/);
  Mbusapi_tlb::DataTypeEnum __fastcall GetType(long Index/*[in]*/);
  HRESULT         __fastcall GetBytesValue(BSTR FieldName/*[in]*/, VARIANT* FieldValue/*[out]*/);
  HRESULT         __fastcall SetBytesValue(BSTR FieldName/*[in]*/, VARIANT Value/*[in]*/,
                                           VARIANT_BOOL Compress/*[in]*/);

};
typedef IMdMessageDispT<IMdMessage> IMdMessageDisp;

// *********************************************************************//
// SmartIntf: TCOMIMdListener
// Interface: IMdListener
// *********************************************************************//
template <class T /* IMdListener */ >
class TCOMIMdListenerT : public TComInterface<IMdListener>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMIMdListenerT() {}
  TCOMIMdListenerT(IMdListener *intf, bool addRef = false) : TComInterface<IMdListener>(intf, addRef) {}
  TCOMIMdListenerT(const TCOMIMdListenerT& src) : TComInterface<IMdListener>(src) {}
  TCOMIMdListenerT& operator=(const TCOMIMdListenerT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall Create(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                    BSTR Subject/*[in]*/, BSTR Key/*[in]*/);
  HRESULT         __fastcall Destroy(void);
  HRESULT         __fastcall IsValid(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall IsValid(void);
  HRESULT         __fastcall get_Subject(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_Subject(void);
  HRESULT         __fastcall set_Subject(BSTR Value/*[in]*/);
  HRESULT         __fastcall get_Key(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_Key(void);
  HRESULT         __fastcall set_Key(BSTR Value/*[in]*/);

  __property   BSTR            Subject = {read = get_Subject, write = set_Subject};
  __property   BSTR            Key = {read = get_Key, write = set_Key};
};
typedef TCOMIMdListenerT<IMdListener> TCOMIMdListener;

// *********************************************************************//
// DispIntf:  IMdListener
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {05D6B349-66FB-4FFF-9DDD-338670AC443B}
// *********************************************************************//
template<class T>
class IMdListenerDispT : public TAutoDriver<IMdListener>
{
public:
  IMdListenerDispT(){}

  IMdListenerDispT(IMdListener *pintf)
  {
    TAutoDriver<IMdListener>::Bind(pintf, false);
  }

  IMdListenerDispT(IMdListenerPtr pintf)
  {
    TAutoDriver<IMdListener>::Bind(pintf, true);
  }

  IMdListenerDispT& operator=(IMdListener *pintf)
  {
    TAutoDriver<IMdListener>::Bind(pintf, false);
    return *this;
  }

  IMdListenerDispT& operator=(IMdListenerPtr pintf)
  {
    TAutoDriver<IMdListener>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_MdListener));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_MdListener);
  }

  HRESULT         __fastcall Create(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                    BSTR Subject/*[in]*/, BSTR Key/*[in]*/);
  HRESULT         __fastcall Destroy();
  HRESULT         __fastcall IsValid(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall IsValid(void);
  HRESULT         __fastcall get_Subject(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_Subject(void);
  HRESULT         __fastcall set_Subject(BSTR Value/*[in]*/);
  HRESULT         __fastcall get_Key(BSTR* Value/*[out,retval]*/);
  BSTR            __fastcall get_Key(void);
  HRESULT         __fastcall set_Key(BSTR Value/*[in]*/);

  __property   BSTR            Subject = {read = get_Subject, write = set_Subject};
  __property   BSTR            Key = {read = get_Key, write = set_Key};
};
typedef IMdListenerDispT<IMdListener> IMdListenerDisp;

// *********************************************************************//
// DispIntf:  IMdListenerEvents
// Flags:     (0)
// GUID:      {73696846-D471-4A49-9D07-FB799406C3B3}
// *********************************************************************//
template <class T>
class IMdListenerEventsDispT : public TAutoDriver<IMdListenerEvents>
{
public:
  IMdListenerEventsDispT(){}

  void Attach(LPUNKNOWN punk)
  { m_Dispatch = static_cast<T*>(punk); }

  HRESULT         __fastcall OnMessageReceived(BSTR Subject/*[in]*/, BSTR Key/*[in]*/,
                                               Mbusapi_tlb::IMdMessage* Msg/*[in]*/);

};
typedef IMdListenerEventsDispT<IMdListenerEvents> IMdListenerEventsDisp;

// *********************************************************************//
// SmartIntf: TCOMIMdTransport
// Interface: IMdTransport
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::Create(BSTR Vendor/*[in]*/, BSTR Name/*[in]*/, BSTR IP/*[in]*/,
                             long Port/*[in]*/, VARIANT_BOOL IsGUIApp/*[in]*/)
{
  return (*this)->Create(Vendor, Name, IP, Port, IsGUIApp);
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::Destroy(void)
{
  return (*this)->Destroy();
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::Connect(long Timeout/*[in]*/)
{
  return (*this)->Connect(Timeout);
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::Disconnect(void)
{
  return (*this)->Disconnect();
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::Send(BSTR Subject/*[in]*/, BSTR Key/*[in]*/,
                           Mbusapi_tlb::IMdMessage* Msg/*[in]*/)
{
  return (*this)->Send(Subject, Key, Msg);
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::IsConnected(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->IsConnected(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMIMdTransportT<T>::IsConnected(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->IsConnected((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::IsValid(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->IsValid(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMIMdTransportT<T>::IsValid(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->IsValid((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::GetTransportInstance(VARIANT* Value/*[out,retval]*/)
{
  return (*this)->GetTransportInstance(Value);
}

template <class T> VARIANT __fastcall
TCOMIMdTransportT<T>::GetTransportInstance(void)
{
  VARIANT Value;
  OLECHECK(this->GetTransportInstance((VARIANT*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::get_AppName(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_AppName(Value);
}

template <class T> BSTR __fastcall
TCOMIMdTransportT<T>::get_AppName(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_AppName((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::get_Host(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_Host(Value);
}

template <class T> BSTR __fastcall
TCOMIMdTransportT<T>::get_Host(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_Host((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::get_Port(long* Value/*[out,retval]*/)
{
  return (*this)->get_Port(Value);
}

template <class T> long __fastcall
TCOMIMdTransportT<T>::get_Port(void)
{
  long Value;
  OLECHECK(this->get_Port((long*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::get_LocalHostname(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_LocalHostname(Value);
}

template <class T> BSTR __fastcall
TCOMIMdTransportT<T>::get_LocalHostname(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_LocalHostname((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::get_LocalIPAddress(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_LocalIPAddress(Value);
}

template <class T> BSTR __fastcall
TCOMIMdTransportT<T>::get_LocalIPAddress(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_LocalIPAddress((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::get_SocketFD(long* Value/*[out,retval]*/)
{
  return (*this)->get_SocketFD(Value);
}

template <class T> long __fastcall
TCOMIMdTransportT<T>::get_SocketFD(void)
{
  long Value;
  OLECHECK(this->get_SocketFD((long*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdTransportT<T>::AddMonitoringProcess(BSTR Host/*[in]*/, BSTR AppName/*[in]*/)
{
  return (*this)->AddMonitoringProcess(Host, AppName);
}

// *********************************************************************//
// DispIntf:  IMdTransport
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {5CA7595B-B4F6-49D7-891A-97081AF24A84}
// *********************************************************************//
template <class T> HRESULT __fastcall
IMdTransportDispT<T>::Create(BSTR Vendor/*[in]*/, BSTR Name/*[in]*/, BSTR IP/*[in]*/,
                             long Port/*[in]*/, VARIANT_BOOL IsGUIApp/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Create"), DISPID(201));
  TAutoArgs<5> _args;
  _args[1] = Vendor /*[VT_BSTR:0]*/;
  _args[2] = Name /*[VT_BSTR:0]*/;
  _args[3] = IP /*[VT_BSTR:0]*/;
  _args[4] = Port /*[VT_I4:0]*/;
  _args[5] = IsGUIApp /*[VT_BOOL:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::Destroy()
{
  _TDispID _dispid(*this, OLETEXT("Destroy"), DISPID(202));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::Connect(long Timeout/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Connect"), DISPID(203));
  TAutoArgs<1> _args;
  _args[1] = Timeout /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::Disconnect()
{
  _TDispID _dispid(*this, OLETEXT("Disconnect"), DISPID(204));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::Send(BSTR Subject/*[in]*/, BSTR Key/*[in]*/,
                           Mbusapi_tlb::IMdMessage* Msg/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Send"), DISPID(205));
  TAutoArgs<3> _args;
  _args[1] = Subject /*[VT_BSTR:0]*/;
  _args[2] = Key /*[VT_BSTR:0]*/;
  _args[3] = (LPDISPATCH)(Mbusapi_tlb::IMdMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::IsConnected(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("IsConnected"), DISPID(206));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
IMdTransportDispT<T>::IsConnected(void)
{
  VARIANT_BOOL Value;
  this->IsConnected((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::IsValid(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("IsValid"), DISPID(207));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
IMdTransportDispT<T>::IsValid(void)
{
  VARIANT_BOOL Value;
  this->IsValid((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::GetTransportInstance(VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetTransportInstance"), DISPID(208));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IMdTransportDispT<T>::GetTransportInstance(void)
{
  VARIANT Value;
  this->GetTransportInstance((VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::get_AppName(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AppName"), DISPID(209));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
IMdTransportDispT<T>::get_AppName(void)
{
  BSTR Value;
  this->get_AppName((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::get_Host(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Host"), DISPID(210));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
IMdTransportDispT<T>::get_Host(void)
{
  BSTR Value;
  this->get_Host((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::get_Port(long* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Port"), DISPID(211));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_I4:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> long __fastcall
IMdTransportDispT<T>::get_Port(void)
{
  long Value;
  this->get_Port((long*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::get_LocalHostname(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("LocalHostname"), DISPID(212));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
IMdTransportDispT<T>::get_LocalHostname(void)
{
  BSTR Value;
  this->get_LocalHostname((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::get_LocalIPAddress(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("LocalIPAddress"), DISPID(213));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
IMdTransportDispT<T>::get_LocalIPAddress(void)
{
  BSTR Value;
  this->get_LocalIPAddress((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::get_SocketFD(long* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("SocketFD"), DISPID(214));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_I4:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> long __fastcall
IMdTransportDispT<T>::get_SocketFD(void)
{
  long Value;
  this->get_SocketFD((long*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdTransportDispT<T>::AddMonitoringProcess(BSTR Host/*[in]*/, BSTR AppName/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("AddMonitoringProcess"), DISPID(215));
  TAutoArgs<2> _args;
  _args[1] = Host /*[VT_BSTR:0]*/;
  _args[2] = AppName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// DispIntf:  IMdTransportEvents
// Flags:     (0)
// GUID:      {6690CD53-07CE-46C2-BAD4-9B61418E9AC6}
// *********************************************************************//
template <class T> HRESULT __fastcall
IMdTransportEventsDispT<T>::OnConnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/)
{
  _TDispID _dispid(/* OnConnected */ DISPID(201));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdTransportEventsDispT<T>::OnDisconnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/)
{
  _TDispID _dispid(/* OnDisconnected */ DISPID(202));
  TAutoArgs<1> _args;
  _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdTransportEventsDispT<T>::OnError(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                    BSTR ErrorMessage/*[in]*/)
{
  _TDispID _dispid(/* OnError */ DISPID(203));
  TAutoArgs<2> _args;
  _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
  _args[2] = ErrorMessage /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdTransportEventsDispT<T>::OnProcessConnected(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                               Mbusapi_tlb::ProcessStatusEnum IsTheFirstOne/*[in]*/)
{
  _TDispID _dispid(/* OnProcessConnected */ DISPID(204));
  TAutoArgs<2> _args;
  _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
  _args[2] = (int)IsTheFirstOne /*[VT_USERDEFINED:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdTransportEventsDispT<T>::OnProcessStartup(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                             BSTR Host/*[in]*/, BSTR AppName/*[in]*/)
{
  _TDispID _dispid(/* OnProcessStartup */ DISPID(205));
  TAutoArgs<3> _args;
  _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
  _args[2] = Host /*[VT_BSTR:0]*/;
  _args[3] = AppName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdTransportEventsDispT<T>::OnProcessStopped(Mbusapi_tlb::IMdTransport* Transport/*[in]*/,
                                             BSTR Host/*[in]*/, BSTR AppName/*[in]*/)
{
  _TDispID _dispid(/* OnProcessStopped */ DISPID(206));
  TAutoArgs<3> _args;
  _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
  _args[2] = Host /*[VT_BSTR:0]*/;
  _args[3] = AppName /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// SmartIntf: TCOMIMdMessage
// Interface: IMdMessage
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::Create(void)
{
  return (*this)->Create();
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::Destroy(void)
{
  return (*this)->Destroy();
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::Attach(VARIANT* Instance/*[in]*/)
{
  return (*this)->Attach(Instance);
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetMessageInstance(VARIANT* Value/*[out]*/)
{
  return (*this)->GetMessageInstance(Value);
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::IsValid(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->IsValid(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMIMdMessageT<T>::IsValid(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->IsValid((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetField(BSTR FieldName/*[in]*/, VARIANT* Value/*[out,retval]*/)
{
  return (*this)->GetField(FieldName, Value);
}

template <class T> VARIANT __fastcall
TCOMIMdMessageT<T>::GetField(BSTR FieldName/*[in]*/)
{
  VARIANT Value;
  OLECHECK(this->GetField(FieldName/*[in]*/, (VARIANT*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::SetField(BSTR FieldName/*[in]*/, VARIANT FieldValue/*[in]*/)
{
  return (*this)->SetField(FieldName, FieldValue);
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetStringValue(BSTR FieldName/*[in]*/, BSTR* Value/*[out,retval]*/)
{
  return (*this)->GetStringValue(FieldName, Value);
}

template <class T> BSTR __fastcall
TCOMIMdMessageT<T>::GetStringValue(BSTR FieldName/*[in]*/)
{
  BSTR Value = 0;
  OLECHECK(this->GetStringValue(FieldName/*[in]*/, (BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::SetStringValue(BSTR FieldName/*[in]*/, BSTR FieldValue/*[in]*/)
{
  return (*this)->SetStringValue(FieldName, FieldValue);
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/,
                                    long* Value/*[out,retval]*/)
{
  return (*this)->GetIntegerValue(FieldName, DefaultValue, Value);
}

template <class T> long __fastcall
TCOMIMdMessageT<T>::GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/)
{
  long Value;
  OLECHECK(this->GetIntegerValue(FieldName/*[in]*/, DefaultValue/*[in]*/, (long*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::SetIntegerValue(BSTR FieldName/*[in]*/, long FieldValue/*[in]*/)
{
  return (*this)->SetIntegerValue(FieldName, FieldValue);
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/,
                                   double* Value/*[out,retval]*/)
{
  return (*this)->GetDoubleValue(FieldName, DefaultValue, Value);
}

template <class T> double __fastcall
TCOMIMdMessageT<T>::GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/)
{
  double Value;
  OLECHECK(this->GetDoubleValue(FieldName/*[in]*/, DefaultValue/*[in]*/, (double*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::SetDoubleValue(BSTR FieldName/*[in]*/, double FieldValue/*[in]*/)
{
  return (*this)->SetDoubleValue(FieldName, FieldValue);
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetFieldCount(long* Value/*[out,retval]*/)
{
  return (*this)->GetFieldCount(Value);
}

template <class T> long __fastcall
TCOMIMdMessageT<T>::GetFieldCount(void)
{
  long Value;
  OLECHECK(this->GetFieldCount((long*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetName(long Index/*[in]*/, BSTR* Name/*[out,retval]*/)
{
  return (*this)->GetName(Index, Name);
}

template <class T> BSTR __fastcall
TCOMIMdMessageT<T>::GetName(long Index/*[in]*/)
{
  BSTR Name = 0;
  OLECHECK(this->GetName(Index/*[in]*/, (BSTR*)&Name));
  return Name;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetValue(long Index/*[in]*/, VARIANT* Value/*[out,retval]*/)
{
  return (*this)->GetValue(Index, Value);
}

template <class T> VARIANT __fastcall
TCOMIMdMessageT<T>::GetValue(long Index/*[in]*/)
{
  VARIANT Value;
  OLECHECK(this->GetValue(Index/*[in]*/, (VARIANT*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetType(long Index/*[in]*/, Mbusapi_tlb::DataTypeEnum* Type/*[out,retval]*/)
{
  return (*this)->GetType(Index, Type);
}

template <class T> Mbusapi_tlb::DataTypeEnum __fastcall
TCOMIMdMessageT<T>::GetType(long Index/*[in]*/)
{
  Mbusapi_tlb::DataTypeEnum Type;
  OLECHECK(this->GetType(Index/*[in]*/, (Mbusapi_tlb::DataTypeEnum*)&Type));
  return Type;
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::GetBytesValue(BSTR FieldName/*[in]*/, VARIANT* FieldValue/*[out]*/)
{
  return (*this)->GetBytesValue(FieldName, FieldValue);
}

template <class T> HRESULT __fastcall
TCOMIMdMessageT<T>::SetBytesValue(BSTR FieldName/*[in]*/, VARIANT Value/*[in]*/,
                                  VARIANT_BOOL Compress/*[in]*/)
{
  return (*this)->SetBytesValue(FieldName, Value, Compress);
}

// *********************************************************************//
// DispIntf:  IMdMessage
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {8B002554-D036-4782-BA8A-95F4A7A03ADE}
// *********************************************************************//
template <class T> HRESULT __fastcall
IMdMessageDispT<T>::Create()
{
  _TDispID _dispid(*this, OLETEXT("Create"), DISPID(201));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::Destroy()
{
  _TDispID _dispid(*this, OLETEXT("Destroy"), DISPID(202));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::Attach(VARIANT* Instance/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Attach"), DISPID(203));
  TAutoArgs<1> _args;
  _args[1] = Instance /*[VT_VARIANT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetMessageInstance(VARIANT* Value/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetMessageInstance"), DISPID(204));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_VARIANT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::IsValid(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("IsValid"), DISPID(205));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
IMdMessageDispT<T>::IsValid(void)
{
  VARIANT_BOOL Value;
  this->IsValid((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetField(BSTR FieldName/*[in]*/, VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetField"), DISPID(206));
  TAutoArgs<1> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IMdMessageDispT<T>::GetField(BSTR FieldName/*[in]*/)
{
  VARIANT Value;
  this->GetField(FieldName, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::SetField(BSTR FieldName/*[in]*/, VARIANT FieldValue/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetField"), DISPID(207));
  TAutoArgs<2> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = FieldValue /*[VT_VARIANT:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetStringValue(BSTR FieldName/*[in]*/, BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetStringValue"), DISPID(208));
  TAutoArgs<1> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> BSTR __fastcall
IMdMessageDispT<T>::GetStringValue(BSTR FieldName/*[in]*/)
{
  BSTR Value;
  this->GetStringValue(FieldName, (BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::SetStringValue(BSTR FieldName/*[in]*/, BSTR FieldValue/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetStringValue"), DISPID(209));
  TAutoArgs<2> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = FieldValue /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/,
                                    long* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetIntegerValue"), DISPID(210));
  TAutoArgs<2> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = DefaultValue /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_I4:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> long __fastcall
IMdMessageDispT<T>::GetIntegerValue(BSTR FieldName/*[in]*/, long DefaultValue/*[in]*/)
{
  long Value;
  this->GetIntegerValue(FieldName, DefaultValue, (long*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::SetIntegerValue(BSTR FieldName/*[in]*/, long FieldValue/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetIntegerValue"), DISPID(211));
  TAutoArgs<2> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = FieldValue /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/,
                                   double* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetDoubleValue"), DISPID(212));
  TAutoArgs<2> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = DefaultValue /*[VT_R8:0]*/;
  return OutRetValSetterPtr(Value /*[VT_R8:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> double __fastcall
IMdMessageDispT<T>::GetDoubleValue(BSTR FieldName/*[in]*/, double DefaultValue/*[in]*/)
{
  double Value;
  this->GetDoubleValue(FieldName, DefaultValue, (double*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::SetDoubleValue(BSTR FieldName/*[in]*/, double FieldValue/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetDoubleValue"), DISPID(213));
  TAutoArgs<2> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = FieldValue /*[VT_R8:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetFieldCount(long* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetFieldCount"), DISPID(214));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_I4:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> long __fastcall
IMdMessageDispT<T>::GetFieldCount(void)
{
  long Value;
  this->GetFieldCount((long*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetName(long Index/*[in]*/, BSTR* Name/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetName"), DISPID(215));
  TAutoArgs<1> _args;
  _args[1] = Index /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Name /*[VT_BSTR:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> BSTR __fastcall
IMdMessageDispT<T>::GetName(long Index/*[in]*/)
{
  BSTR Name;
  this->GetName(Index, (BSTR*)&Name);
  return Name;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetValue(long Index/*[in]*/, VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetValue"), DISPID(216));
  TAutoArgs<1> _args;
  _args[1] = Index /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IMdMessageDispT<T>::GetValue(long Index/*[in]*/)
{
  VARIANT Value;
  this->GetValue(Index, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetType(long Index/*[in]*/, Mbusapi_tlb::DataTypeEnum* Type/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetType"), DISPID(217));
  TAutoArgs<1> _args;
  _args[1] = Index /*[VT_I4:0]*/;
  return OutRetValSetterPtr((int*)Type /*[VT_USERDEFINED:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> Mbusapi_tlb::DataTypeEnum __fastcall
IMdMessageDispT<T>::GetType(long Index/*[in]*/)
{
  Mbusapi_tlb::DataTypeEnum Type;
  this->GetType(Index, (Mbusapi_tlb::DataTypeEnum*)&Type);
  return Type;
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::GetBytesValue(BSTR FieldName/*[in]*/, VARIANT* FieldValue/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetBytesValue"), DISPID(218));
  TAutoArgs<2> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = FieldValue /*[VT_VARIANT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdMessageDispT<T>::SetBytesValue(BSTR FieldName/*[in]*/, VARIANT Value/*[in]*/,
                                  VARIANT_BOOL Compress/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetBytesValue"), DISPID(219));
  TAutoArgs<3> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = Value /*[VT_VARIANT:0]*/;
  _args[3] = Compress /*[VT_BOOL:0]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// SmartIntf: TCOMIMdListener
// Interface: IMdListener
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMIMdListenerT<T>::Create(Mbusapi_tlb::IMdTransport* Transport/*[in]*/, BSTR Subject/*[in]*/,
                            BSTR Key/*[in]*/)
{
  return (*this)->Create(Transport, Subject, Key);
}

template <class T> HRESULT __fastcall
TCOMIMdListenerT<T>::Destroy(void)
{
  return (*this)->Destroy();
}

template <class T> HRESULT __fastcall
TCOMIMdListenerT<T>::IsValid(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->IsValid(Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMIMdListenerT<T>::IsValid(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->IsValid((VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdListenerT<T>::get_Subject(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_Subject(Value);
}

template <class T> BSTR __fastcall
TCOMIMdListenerT<T>::get_Subject(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_Subject((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdListenerT<T>::set_Subject(BSTR Value/*[in]*/)
{
  return (*this)->set_Subject(Value);
}

template <class T> HRESULT __fastcall
TCOMIMdListenerT<T>::get_Key(BSTR* Value/*[out,retval]*/)
{
  return (*this)->get_Key(Value);
}

template <class T> BSTR __fastcall
TCOMIMdListenerT<T>::get_Key(void)
{
  BSTR Value = 0;
  OLECHECK(this->get_Key((BSTR*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIMdListenerT<T>::set_Key(BSTR Value/*[in]*/)
{
  return (*this)->set_Key(Value);
}

// *********************************************************************//
// DispIntf:  IMdListener
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {05D6B349-66FB-4FFF-9DDD-338670AC443B}
// *********************************************************************//
template <class T> HRESULT __fastcall
IMdListenerDispT<T>::Create(Mbusapi_tlb::IMdTransport* Transport/*[in]*/, BSTR Subject/*[in]*/,
                            BSTR Key/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Create"), DISPID(201));
  TAutoArgs<3> _args;
  _args[1] = (LPDISPATCH)(Mbusapi_tlb::IMdTransport*)Transport /*[VT_USERDEFINED:1]*/;
  _args[2] = Subject /*[VT_BSTR:0]*/;
  _args[3] = Key /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdListenerDispT<T>::Destroy()
{
  _TDispID _dispid(*this, OLETEXT("Destroy"), DISPID(202));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
IMdListenerDispT<T>::IsValid(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("IsValid"), DISPID(203));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
IMdListenerDispT<T>::IsValid(void)
{
  VARIANT_BOOL Value;
  this->IsValid((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdListenerDispT<T>::get_Subject(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Subject"), DISPID(204));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
IMdListenerDispT<T>::get_Subject(void)
{
  BSTR Value;
  this->get_Subject((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdListenerDispT<T>::set_Subject(BSTR Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Subject"), DISPID(204));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BSTR:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
IMdListenerDispT<T>::get_Key(BSTR* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Key"), DISPID(205));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
IMdListenerDispT<T>::get_Key(void)
{
  BSTR Value;
  this->get_Key((BSTR*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IMdListenerDispT<T>::set_Key(BSTR Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Key"), DISPID(205));
  TAutoArgs<1> _args;
  _args[1] = Value /*[VT_BSTR:0]*/;
  return OlePropertyPut(_dispid, _args);
}

// *********************************************************************//
// DispIntf:  IMdListenerEvents
// Flags:     (0)
// GUID:      {73696846-D471-4A49-9D07-FB799406C3B3}
// *********************************************************************//
template <class T> HRESULT __fastcall
IMdListenerEventsDispT<T>::OnMessageReceived(BSTR Subject/*[in]*/, BSTR Key/*[in]*/,
                                             Mbusapi_tlb::IMdMessage* Msg/*[in]*/)
{
  _TDispID _dispid(/* OnMessageReceived */ DISPID(201));
  TAutoArgs<3> _args;
  _args[1] = Subject /*[VT_BSTR:0]*/;
  _args[2] = Key /*[VT_BSTR:0]*/;
  _args[3] = (LPDISPATCH)(Mbusapi_tlb::IMdMessage*)Msg /*[VT_USERDEFINED:1]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that
// provide static Create() and CreateRemote(LPWSTR machineName) methods
// for creating an instance of an exposed object. These functions can
// be used by client wishing to automate CoClasses exposed by this
// typelibrary.
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : MdTransport
// Interface: TCOMIMdTransport
// *********************************************************************//
typedef TCoClassCreatorT<TCOMIMdTransport, IMdTransport, &CLSID_MdTransport, &IID_IMdTransport> CoMdTransport;

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : MdMessage
// Interface: TCOMIMdMessage
// *********************************************************************//
typedef TCoClassCreatorT<TCOMIMdMessage, IMdMessage, &CLSID_MdMessage, &IID_IMdMessage> CoMdMessage;

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : MdListener
// Interface: TCOMIMdListener
// *********************************************************************//
typedef TCoClassCreatorT<TCOMIMdListener, IMdListener, &CLSID_MdListener, &IID_IMdListener> CoMdListener;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


#if !defined(__TLB_NO_EVENT_WRAPPERS) && defined(USING_ATLVCL)
// *********************************************************************//
// CONNECTIONPOINT/EVENT PROXY
// CoClass         : MdTransport
// Event Interface : IMdTransportEvents
// *********************************************************************//
template <class T>
class TEvents_MdTransport : public IConnectionPointImpl<T,
                                                 &DIID_IMdTransportEvents,
#if !defined(_TLB_DYNAMIC_CONNECTIONPOINT_ARRAY)
                                                 CComUnkArray<CONNECTIONPOINT_ARRAY_SIZE> >
#else
                                                 CComDynamicArray>
#endif
{
public:
  HRESULT         Fire_OnConnected(Mbusapi_tlb::IMdTransport* Transport);
  HRESULT         Fire_OnDisconnected(Mbusapi_tlb::IMdTransport* Transport);
  HRESULT         Fire_OnError(Mbusapi_tlb::IMdTransport* Transport, BSTR ErrorMessage);
  HRESULT         Fire_OnProcessConnected(Mbusapi_tlb::IMdTransport* Transport,
                                          Mbusapi_tlb::ProcessStatusEnum IsTheFirstOne);
  HRESULT         Fire_OnProcessStartup(Mbusapi_tlb::IMdTransport* Transport, BSTR Host,
                                        BSTR AppName);
  HRESULT         Fire_OnProcessStopped(Mbusapi_tlb::IMdTransport* Transport, BSTR Host,
                                        BSTR AppName);
protected:
  IMdTransportEventsDisp m_EventIntfObj;
};

template <class T> HRESULT
TEvents_MdTransport<T>::Fire_OnConnected(Mbusapi_tlb::IMdTransport* Transport)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnConnected(Transport);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

template <class T> HRESULT
TEvents_MdTransport<T>::Fire_OnDisconnected(Mbusapi_tlb::IMdTransport* Transport)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnDisconnected(Transport);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

template <class T> HRESULT
TEvents_MdTransport<T>::Fire_OnError(Mbusapi_tlb::IMdTransport* Transport, BSTR ErrorMessage)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnError(Transport, ErrorMessage);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

template <class T> HRESULT
TEvents_MdTransport<T>::Fire_OnProcessConnected(Mbusapi_tlb::IMdTransport* Transport,
                                                Mbusapi_tlb::ProcessStatusEnum IsTheFirstOne)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnProcessConnected(Transport, IsTheFirstOne);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

template <class T> HRESULT
TEvents_MdTransport<T>::Fire_OnProcessStartup(Mbusapi_tlb::IMdTransport* Transport, BSTR Host,
                                              BSTR AppName)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnProcessStartup(Transport, Host, AppName);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

template <class T> HRESULT
TEvents_MdTransport<T>::Fire_OnProcessStopped(Mbusapi_tlb::IMdTransport* Transport, BSTR Host,
                                              BSTR AppName)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnProcessStopped(Transport, Host, AppName);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

// *********************************************************************//
// CONNECTIONPOINT/EVENT PROXY
// CoClass         : MdListener
// Event Interface : IMdListenerEvents
// *********************************************************************//
template <class T>
class TEvents_MdListener : public IConnectionPointImpl<T,
                                                 &DIID_IMdListenerEvents,
#if !defined(_TLB_DYNAMIC_CONNECTIONPOINT_ARRAY)
                                                 CComUnkArray<CONNECTIONPOINT_ARRAY_SIZE> >
#else
                                                 CComDynamicArray>
#endif
{
public:
  HRESULT         Fire_OnMessageReceived(BSTR Subject, BSTR Key, Mbusapi_tlb::IMdMessage* Msg);
protected:
  IMdListenerEventsDisp m_EventIntfObj;
};

template <class T> HRESULT
TEvents_MdListener<T>::Fire_OnMessageReceived(BSTR Subject, BSTR Key, Mbusapi_tlb::IMdMessage* Msg)
{
  T * pT = (T*)this;
  pT->Lock();
  IUnknown ** pp = m_vec.begin();
  while (pp < m_vec.end())
  {
    if (*pp != NULL)
    {
      m_EventIntfObj.Attach(*pp);
      m_EventIntfObj.OnMessageReceived(Subject, Key, Msg);
      m_EventIntfObj.Attach(0);
    }
    pp++;
  }
  pT->Unlock();
  return S_OK;
}

#endif    //   __TLB_NO_EVENT_WRAPPERS

#if !defined(__TLB_NO_EVENT_WRAPPERS) && defined(USING_DAX)
// *********************************************************************//
// CONNECTIONPOINT/EVENT PROXY
// CoClass         : MdTransport
// Event Interface : IMdTransportEvents
// *********************************************************************//
template <typename T>
class IMdTransport_EventsDispatcher : public IUnknown
{
public:
  HRESULT Fire_OnConnected(Mbusapi_tlb::IMdTransport* Transport)
  {
    IMdTransportEventsDisp dispInvoker;
    T* pClass = static_cast<T*>(this);
    TConnectionPointSinkList<T> cpsl(pClass->ConnectionPoint);
    if (cpsl.HasConnectionPoint()) {
      for (int i=0; i<cpsl.GetCount(); i++) {
        _di_IInterface punk;
        if (cpsl.GetSink(i, punk) && (dispInvoker.Bind(punk)==S_OK))
          dispInvoker.OnConnected(Transport);
      }
    }
    return S_OK;
  }

  HRESULT Fire_OnDisconnected(Mbusapi_tlb::IMdTransport* Transport)
  {
    IMdTransportEventsDisp dispInvoker;
    T* pClass = static_cast<T*>(this);
    TConnectionPointSinkList<T> cpsl(pClass->ConnectionPoint);
    if (cpsl.HasConnectionPoint()) {
      for (int i=0; i<cpsl.GetCount(); i++) {
        _di_IInterface punk;
        if (cpsl.GetSink(i, punk) && (dispInvoker.Bind(punk)==S_OK))
          dispInvoker.OnDisconnected(Transport);
      }
    }
    return S_OK;
  }

  HRESULT Fire_OnError(Mbusapi_tlb::IMdTransport* Transport, BSTR ErrorMessage)
  {
    IMdTransportEventsDisp dispInvoker;
    T* pClass = static_cast<T*>(this);
    TConnectionPointSinkList<T> cpsl(pClass->ConnectionPoint);
    if (cpsl.HasConnectionPoint()) {
      for (int i=0; i<cpsl.GetCount(); i++) {
        _di_IInterface punk;
        if (cpsl.GetSink(i, punk) && (dispInvoker.Bind(punk)==S_OK))
          dispInvoker.OnError(Transport, ErrorMessage);
      }
    }
    return S_OK;
  }

  HRESULT Fire_OnProcessConnected(Mbusapi_tlb::IMdTransport* Transport,
                                  Mbusapi_tlb::ProcessStatusEnum IsTheFirstOne)
  {
    IMdTransportEventsDisp dispInvoker;
    T* pClass = static_cast<T*>(this);
    TConnectionPointSinkList<T> cpsl(pClass->ConnectionPoint);
    if (cpsl.HasConnectionPoint()) {
      for (int i=0; i<cpsl.GetCount(); i++) {
        _di_IInterface punk;
        if (cpsl.GetSink(i, punk) && (dispInvoker.Bind(punk)==S_OK))
          dispInvoker.OnProcessConnected(Transport, IsTheFirstOne);
      }
    }
    return S_OK;
  }

  HRESULT Fire_OnProcessStartup(Mbusapi_tlb::IMdTransport* Transport, BSTR Host, BSTR AppName)
  {
    IMdTransportEventsDisp dispInvoker;
    T* pClass = static_cast<T*>(this);
    TConnectionPointSinkList<T> cpsl(pClass->ConnectionPoint);
    if (cpsl.HasConnectionPoint()) {
      for (int i=0; i<cpsl.GetCount(); i++) {
        _di_IInterface punk;
        if (cpsl.GetSink(i, punk) && (dispInvoker.Bind(punk)==S_OK))
          dispInvoker.OnProcessStartup(Transport, Host, AppName);
      }
    }
    return S_OK;
  }

  HRESULT Fire_OnProcessStopped(Mbusapi_tlb::IMdTransport* Transport, BSTR Host, BSTR AppName)
  {
    IMdTransportEventsDisp dispInvoker;
    T* pClass = static_cast<T*>(this);
    TConnectionPointSinkList<T> cpsl(pClass->ConnectionPoint);
    if (cpsl.HasConnectionPoint()) {
      for (int i=0; i<cpsl.GetCount(); i++) {
        _di_IInterface punk;
        if (cpsl.GetSink(i, punk) && (dispInvoker.Bind(punk)==S_OK))
          dispInvoker.OnProcessStopped(Transport, Host, AppName);
      }
    }
    return S_OK;
  }

};

// *********************************************************************//
// CONNECTIONPOINT/EVENT PROXY
// CoClass         : MdListener
// Event Interface : IMdListenerEvents
// *********************************************************************//
template <typename T>
class IMdListener_EventsDispatcher : public IUnknown
{
public:
  HRESULT Fire_OnMessageReceived(BSTR Subject, BSTR Key, Mbusapi_tlb::IMdMessage* Msg)
  {
    IMdListenerEventsDisp dispInvoker;
    T* pClass = static_cast<T*>(this);
    TConnectionPointSinkList<T> cpsl(pClass->ConnectionPoint);
    if (cpsl.HasConnectionPoint()) {
      for (int i=0; i<cpsl.GetCount(); i++) {
        _di_IInterface punk;
        if (cpsl.GetSink(i, punk) && (dispInvoker.Bind(punk)==S_OK))
          dispInvoker.OnMessageReceived(Subject, Key, Msg);
      }
    }
    return S_OK;
  }

};

#endif    //   __TLB_NO_EVENT_WRAPPERS

};     // namespace Mbusapi_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Mbusapi_tlb;
#endif

#pragma option pop

#endif // MBusAPI_TLBH

