[LoginErrorCode]
00=認證成功
###02 大陸
02=Not authorized to access Super888
11=userid is empty
12=password empty
14=internal connection open error
22=password error
23=非合法帳號
26=UK invalid
27=internal connection error 
28=首次登入
2a=帳號已暫停使用
2b=Not authorized to access Super888
#Tandem 後台:

#錯誤碼	錯誤原因
#========================================================
#絕大部分執行結果的回傳值
#--------------------------------------------------------
21=非合法帳號
20000=執行失敗!

#告知客戶錯誤的原因,屬於狀態或是操作錯誤的訊息
#--------------------------------------------------------
20101=查無資料
20102=密碼凍結或未啟用
20103=新密碼太過簡單
20104=密碼錯誤,請重新輸入
20105=密碼已凍結，請洽分公司開戶櫃檯重新申請
20106=帳號使用時間超過期限
20107=參數不足
20108=測試帳號期限已過
20109=已過下單日
20110=密碼只能為數字
20111=新密碼的長度過長或不足
20112=無此權限使用此功能
20113=CA憑證認證失敗
20114=CA憑證重複申請
20115=個人資料檢核失敗

#系統錯誤,請客戶稍後再試,並提示錯誤來源以供工程師排除問題
#--------------------------------------------------------
20900=系統錯誤
20901=資料庫讀寫錯誤
20902=電子護照執行錯誤
20903=執行登入發生錯誤
20904=等候逾時

#回復狀態並提供操作指示
#--------------------------------------------------------
21001=請更改密碼
21002=請輸入下兩組電子護照
21003=請設電子護照自設密碼
21004=請先開通期貨帳號

[CA]
#FSCAPI Error Code
 
0=成功 
5001= 一般錯誤
5002=配置記憶體發生錯誤
5003=FS_RTN_BUFFER_TOO_SMALL
5004=FS_RTN_FUNCTION_UNSUPPORT
5005=錯誤的參數 
5006=FS_RTN_INVALID_HANDLE
5007=試用版期限已過 
5008=Base64編碼錯誤 
5010=無法在MS CryptoAPI Database中找到指定憑證
5011=憑證已過期
5012=憑證尚未合法,無法使用 
5013=憑證可能過期或無法使用
5014=憑證主旨錯誤
5015=無法找到憑證發行者
5016=不合法的憑證簽章
5017=憑證用途(加解密,簽驗章)不合適
5020=憑證已撤銷
5021=憑證已撤銷(金鑰洩露)
5022=憑證已撤銷(CA compromised)
5023=憑證已撤銷(聯盟已變更)
#MLB升上大聯盟?
5024=憑證已撤銷(已取代) 
5025=憑證已撤銷(已停止)
5026=憑證保留或暫禁
5030=CRL已過期
5031=不合法的CRL
5032=無法找到CRL
5035=Digest錯誤
5036=不合法的簽章
5037=內容錯誤
5040=憑證格式錯誤
5041=CRL格式錯誤
5042=錯誤的PKCS7格式
5043=Key的格式錯誤
5044=不合法的PKCS10格式
5045=不合適的格式
5050=FS_RTN_OBJ_NOT_FOUND
5051=FS_RTN_PKCS7_NO_CONTENT
5052=FS_RTN_PKCS7_NO_CERTIFICATE
5053=FS_RTN_PKCS7_NO_SIGNERINFO
5060=錯誤的憑證或金鑰
5061=簽章失敗
5062=驗章失敗
5063=加密失敗
5064=解密失敗
5065=產生金鑰失敗
5070=使用者按下 "取消" 按鈕
5080=無法剖析XML文件
5081=無法在XML中,找到指定的標籤名稱
5201=FSCAPI_RTN_OPENSTORE_ERROR
5202=FSCAPI_RTN_CREATECHAIN_ERROR
5203=FSCAPI_RTN_CRYPTCONTEXT_ERROR
5204=找不到關聯的私密金鑰
5205=關聯的私密金鑰已被標記成 "不能匯出
5206=FSCAPI_RTN_STORE_ACCESSDENY
