

[SpeedyUnify.exe]
Version=3031600
SaveAs=SpeedyUnify.ex_
Compress=1
Size=4082142
Restart=1
ForceUpdate=1
ReInstall=0
Setup=https://mdbs-sharespace.mdevelop.com/SpeedyRelease/Unify/SpeedyUnify_Setup.exe

Line1=增加微型台指支援



[MEGASECCAPIATL.dll]
Version=1000000
Compress=1
Register=1
Size=934489

[ssleay32.dll]
Version=1000107
Compress=1
Size=134717

[libeay32.dll]
Version=1000107
Compress=1
Size=620181


[RestartAgent.exe]
Version=1000024
Compress=1
Size=1178151

[FMTMD.ini]
Version=everytime
Size=390

[FMTBroker.ini]
Version=everytime
Size=518

[ExchangeInfo.ini]
Version=everyday
Size=3070

[ProductInfo.cfg]
Version=everyday
#Version=everytime
Size=23687

[EquitySectors.ini]
Version=everyday
Size=1108

[DefImage.png]
Version=1000000
Size=4725

[TaifexFee.xml]
Version=1000000
Size=703

[TaifexTax.xml]
Version=1000000
Size=781

#---- for RoomMi ----

[lame_enc.dll]
Version=1000000
Size=162304

[libEGL.dll]
Version=1000000
Size=260608

[libGLES_CM.dll]
Version=1000000
Size=883712

[libGLESv2.dll]
Version=1000000
Size=2141184

[msvcp100.dll]
Version=1000000
Size=421200

[msvcr100.dll]
Version=1000000
Size=770384

[roome_client.dll]
Version=1030301
Size=4194303
Restart=1

[roome_assets.zip]
Version=1000000
Depenency=roome_client.dll
Size=70254592








