[UpdateHost]
URL=https://mdbs-sharespace.mdevelop.com/SpeedyRelease/emegafuture-pro/
URL1=https://unify-files.mpublic.net/

[Host]
#MD=60.250.82.135:34567
#Chart=60.250.82.135:34569

MD=10.0.5.132:34567
Chart=10.0.5.132:34569


[BackupHost]
#MD=60.250.82.135
#Chart=60.250.82.135
MD=10.0.5.132:34567
Chart=10.0.5.132:34569

[SimHost]

MD=35.206.250.143:34567
Chart=35.206.250.143:34569
Order=35.206.250.143:45678
Name=實戰班-網際網路
MaxLots = 300

MD1=35.206.250.143:34567
Chart1=35.206.250.143:34569
Order1=35.206.250.143:45678
Name1=實戰班-啟蒙教室
MaxLots1 = 300

MD2=10.0.5.132:34567
Chart2=10.0.5.132:34569
Order2=10.0.5.132:45678
Name2=模擬單-正式行情
MaxLots2 = 200

MD3=35.206.250.143:34567
Chart3=35.206.250.143:34569
Order3=35.206.250.143:45678
Name3=下午練習盤
MaxLots3 = 10

MD4=35.206.236.68:34567
Chart4=35.206.236.68:34569
Order4=35.206.236.68:45678
Name4=晚餐後挑戰
MaxLots4 = 10






[Test]
RegisterURL = https://unify.data-bee.com/UnifyStrategy/member/registerAP.do
ForgetPassword = https://unify.data-bee.com/UnifyStrategy/member/forgetPwdAP.do
EditURL = https://unify.data-bee.com/UnifyStrategy/member/myAccountAP.do
Report = https://unify.data-bee.com/UnifyStrategy/calendar/table.do
LogonURL = https://219.84.174.186/AOEApi/dataTrans.do
XFlashURL = https://219.84.174.186/AOEApi/projectByCp.do
PurchaseList = https://219.84.174.186/AOEApi/orderByMember.do
MegaCAURL = https://fugw01.emega.com.tw/ekey-VA/StockP1VerifySign.jsp
#MegaCAURL = http://ekeytest.emega.com.tw/VA/StockP1VerifySign.jsp
MegaBackendURL = https://rayin.emega.com.tw/query/indexf.jsp


[Prod]
RegisterURL = https://unify.data-bee.com/UnifyStrategy/member/registerAP.do
ForgetPassword = https://unify.data-bee.com/UnifyStrategy/member/forgetPwdAP.do
EditURL = https://unify.data-bee.com/UnifyStrategy/member/myAccountAP.do
Report = https://unify.data-bee.com/UnifyStrategy/calendar/table.do
LogonURL = https://219.84.174.186/AOEApi/dataTrans.do
XFlashURL = https://219.84.174.186/AOEApi/projectByCp.do
PurchaseList = https://219.84.174.186/AOEApi/orderByMember.do
#MegaCAURL = https://fugw01.emega.com.tw/ekey-VA/StockP1VerifySign.jsp
MegaCAURL = http://ekeytest.emega.com.tw:8080/VA/StockP1VerifySign.jsp
MegaBackendURL = https://rayin.emega.com.tw/query/indexf.jsp


[License]
IP1=211.23.46.216
IP2=60.248.161.187
IP3=60.248.161.189
IP4=60.248.161.121
IP5=60.248.161.122
IP6=60.248.161.123
IP7=118.163.107.223
IP8=118.163.107.224
IP9=118.163.107.225
IP10=118.163.107.226
IP11=118.163.107.227
IP12=118.163.107.228
IP13=211.21.155.59
IP14=211.23.46.215
IP15=60.248.161.188


[VIPServer]
#MD=10.0.5.132:34567
#Chart=10.0.5.132:34569
MD=fugw01.emega.com.tw:34567
Chart=fugw01.emega.com.tw:34569


#----- 魔王 -----
VIP1=0935696405
#----- Simon -----
VIP2=0922797985
#----- 順文 -----
VIP3=0912231285
VIP4=0932332287
VIP5=0956606389
#---兆豐期-----
VIP6=0920252480
VIP7=0981711767
VIP8=0932332287

[Parameter]
SkyLandOffset=0

[Signal]
0859=00000

[Throughput]
0922797985=66

[Disclaimer]
ExecutionForm=一、「預估可動用保證金」係依本系統自訂標準概算，僅供參考。\r\n二、因本系統未提供 16:15 收盤商品之交易與計算，且計算方式與公會標準公式不同，實際情形請至其他平台或洽所屬業務員查詢為準。\r\n一般交易時段收盤時間為16:15之商品如下：\r\n ‧ 東證期貨TJF\r\n ‧ 黃金期貨GDF\r\n ‧ 臺幣黃金期貨TGF/選擇權TGO\r\n ‧ 匯率類-大RHF小RTF美人、歐兌美XEF、美兌日XJF、英兌美XBF、澳兌美XAF\r\n ‧ 標的證券為國外成分證券指數股票型基金或境外指數股票型基金者之個股期貨/選擇權

